import assert from "node:assert/strict";
import test from "node:test";
import { mapCardPurchase,mapTransaction } from "./mappers";

test("transacao bancaria permanece vinculada somente a conta",()=>{const row=mapTransaction({id:"bank",accountId:"provider-bank",amount:-40,type:"DEBIT"},"owner","connection",{accountId:"account"});assert.equal(row.account_id,"account");assert.equal(row.credit_card_id,null);assert.equal(row.source_type,"bank")});
test("conta CREDIT gera compra com parcela e referencia de fatura",()=>{const row=mapCardPurchase({id:"tx-card",accountId:"provider-card",amount:50,date:"2026-07-10",creditCardMetadata:{purchaseDate:"2026-07-08",installmentNumber:3,totalInstallments:10,totalAmount:500,billForecastDate:"2026-07",billId:"bill"}},"owner","connection","card");assert.equal(row.card_id,"card");assert.equal(row.transaction_role,"consumption");assert.equal(row.installment_number,3);assert.equal(row.installment_count,10);assert.equal(row.total_amount,500);assert.equal(row.bill_forecast_date,"2026-07-01");assert.equal(row.provider_bill_id,"bill")});
test("estorno de cartao fica separado do consumo",()=>assert.equal(mapCardPurchase({id:"refund",accountId:"card",amount:-20,description:"Estorno compra"},"owner","connection","card").transaction_role,"refund"));
test("pagamento de fatura importado aguarda vinculo com cartao ou fatura",()=>{const row=mapTransaction({id:"invoice",accountId:"bank",amount:-100,description:"Pagamento de fatura"},"owner","connection",{accountId:"account"});assert.equal(row.transaction_role,"invoice_payment");assert.equal(row.review_status,"pending");assert.equal(row.account_id,"account");assert.equal(row.credit_card_id,null)});
test("identificador externo sustenta sincronizacao repetida",()=>{const one=mapCardPurchase({id:"stable",accountId:"card",amount:20},"owner","connection","card");const two=mapCardPurchase({id:"stable",accountId:"card",amount:25},"owner","connection","card");assert.equal(one.external_id,two.external_id)});
