import "server-only";

import { chunkForUrlFilter,shouldRecoverFullHistory } from "./batching";
import { getPluggyAccounts,getPluggyBills,getPluggyInvestments,getPluggyItem,getPluggyLoans,getPluggyTransactions } from "./client";
import { databaseFailure,logIntegrationFailure,maskId } from "./diagnostics";
import { IntegrationSyncError,mapPluggyError,PluggyApiError,normalizeIntegrationError,sanitizeDiagnostic } from "./errors";
import { buildLoanProjections } from "./loan-projections";
import { mergeManualInstallmentCorrection } from "./installment-merge";
import { assessSyncCompleteness,hasInterruptedPagination,type CompletenessAssessment,type SyncSnapshot } from "./resilience";
import { mergeInvoicePersistenceRow } from "./invoice-preservation";
import {persistOfficialBills,syncMinimalIdentity} from "./official-bill-sync";
import { accountCardInstrument,cursorFromNext,findSuspectedTransferIds,mapAccount,mapCard,mapCardPurchase,mapInvestment,mapPluggyLoanToFinancialLoan,mapTransaction,safeBillDiagnostic,safeCreditAccountDiagnostic,safeCreditTransactionDiagnostic,selectCurrentPluggyBill,transactionCardInstrument } from "./mappers";
import { BANK_CLASSIFIER_VERSION,providerBankDirection } from "./bank-classifier";
import type { PluggyAccount,PluggyBill,PluggyPage } from "./types";
import { analyzeInvoiceInclusion,buildCurrentCardInvoices } from "@/modules/finance/card-invoices";
import type { CardPurchase,CreditCard } from "@/modules/finance/types";

type DbClient=Awaited<ReturnType<typeof import("@/lib/supabase/server").createClient>>;
type SyncStage="connection_load"|"sync_run_begin"|"auth"|"item"|"accounts_fetch"|"accounts_upsert"|"bills_fetch"|"cards_fetch"|"cards_upsert"|"transactions_fetch"|"transactions_map"|"transactions_upsert"|"investments_fetch"|"investments_upsert"|"loans_fetch"|"loans_map"|"loans_upsert"|"connection_update"|"sync_run_finalize";
type Counts={accounts:number;cards:number;instruments:number;pendingInstruments:number;transactions:number;investments:number;loans:number;pages:number;accountsCreated:number;accountsUpdated:number;cardsCreated:number;cardsUpdated:number;instrumentsCreated:number;instrumentsUpdated:number;transactionsCreated:number;transactionsUpdated:number;transactionsSkipped:number;transactionFailures:number;investmentsCreated:number;investmentsUpdated:number;loansCreated:number;loansUpdated:number};
type CreditDiagnosticState={cardId:string;received:number;mapped:number;pages:number;pageSizes:number[];externalIds:Set<string>;duplicateIds:number;statusCounts:Record<string,number>;classificationCounts:Record<string,number>;referenceCounts:{withBillId:number;withoutBillId:number;withBillForecastDate:number;withoutBillForecastDate:number};instrumentCounts:Record<string,number>};
const emptyCounts=():Counts=>({accounts:0,cards:0,instruments:0,pendingInstruments:0,transactions:0,investments:0,loans:0,pages:0,accountsCreated:0,accountsUpdated:0,cardsCreated:0,cardsUpdated:0,instrumentsCreated:0,instrumentsUpdated:0,transactionsCreated:0,transactionsUpdated:0,transactionsSkipped:0,transactionFailures:0,investmentsCreated:0,investmentsUpdated:0,loansCreated:0,loansUpdated:0});
const chunks=chunkForUrlFilter;

function list<T>(value:T[]|PluggyPage<T>,stage:SyncStage){if(Array.isArray(value))return value;if(value&&typeof value==="object"&&Array.isArray(value.results))return value.results;throw new IntegrationSyncError("A Pluggy retornou uma lista em formato inesperado.",{operation:"response.parse",stage})}
function wrap(error:unknown,stage:SyncStage,message:string,operation="sync"){if(error instanceof IntegrationSyncError)return error;const normalized=normalizeIntegrationError(error);return new IntegrationSyncError(message,{code:normalized.code,status:normalized.status,operation:normalized.operation??operation,stage,cause:error})}

async function upsertMany(supabase:DbClient,table:string,rows:Record<string,unknown>[],stage:SyncStage,preserve:string[]=[],preserveWhenMissing:string[]=[]){
 let created=0,updated=0;
 for(const batch of chunks(rows)){if(!batch.length)continue;const ownerId=String(batch[0].owner_id);const ids=batch.map(row=>String(row.external_id));const selected=[...new Set(["external_id",...preserve,...preserveWhenMissing])];const existing=await supabase.from(table).select(selected.join(",")).eq("owner_id",ownerId).eq("source",String(batch[0].source??"pluggy")).in("external_id",ids);if(existing.error)databaseFailure(existing.error,stage,`${table}.select_existing`);const existingRows=(existing.data??[]) as unknown as Record<string,unknown>[];const previous=new Map(existingRows.map(row=>[String(row.external_id),row]));updated+=existingRows.length;created+=batch.length-existingRows.length;const safeRows=(preserve.length||preserveWhenMissing.length)?batch.map(row=>{const old=previous.get(String(row.external_id));if(!old)return row;return {...row,...Object.fromEntries(preserve.map(key=>[key,old[key]])),...Object.fromEntries(preserveWhenMissing.filter(key=>row[key]===null||row[key]===undefined).map(key=>[key,old[key]]))}}):batch;const result=await supabase.from(table).upsert(safeRows,{onConflict:"owner_id,source,external_id"});if(result.error)databaseFailure(result.error,stage,`${table}.upsert`)}
 return {created,updated};
}
async function targetMap(supabase:DbClient,table:"financial_accounts"|"credit_cards",userId:string,externalIds:string[],stage:SyncStage){const result=new Map<string,string>();for(const batch of chunks(externalIds)){if(!batch.length)continue;const query=await supabase.from(table).select("id,external_id").eq("owner_id",userId).eq("source","pluggy").in("external_id",batch);if(query.error)databaseFailure(query.error,stage,table);for(const row of query.data??[])result.set(String(row.external_id),String(row.id))}return result}
function optionalWarning(error:unknown,context:{stage:SyncStage;started:number;userId:string;itemId:string},fallback:string){const normalized=logIntegrationFailure(error,{operation:"sync.optional",stage:context.stage,durationMs:Date.now()-context.started,user:context.userId,item:context.itemId,label:"[Atlas Pluggy Optional Stage Failure]"});return `${fallback}${normalized.code?` (${normalized.code})`:""}`}
function sharedBalanceGroupSizes(accounts:PluggyAccount[]){const groups=new Map<number,number>();for(const account of accounts){if(typeof account.balance!=="number"||!Number.isFinite(account.balance))continue;groups.set(account.balance,(groups.get(account.balance)??0)+1)}return [...groups.values()].filter(count=>count>1).sort((left,right)=>right-left)}
function storedSnapshot(value:unknown):SyncSnapshot|null{if(!value||typeof value!=="object"||Array.isArray(value))return null;const row=value as Record<string,unknown>;const keys=["creditAccounts","cards","transactions","bills","instruments"] as const;if(!keys.every(key=>Number.isFinite(Number(row[key]))))return null;return {creditAccounts:Number(row.creditAccounts),cards:Number(row.cards),transactions:Number(row.transactions),bills:Number(row.bills),instruments:Number(row.instruments)}}
async function existingSnapshot(supabase:DbClient,userId:string,connectionId:string,stage:SyncStage):Promise<SyncSnapshot>{const [cards,purchases]=await Promise.all([supabase.from("credit_cards").select("id,provider_bill_id").eq("owner_id",userId).eq("bank_connection_id",connectionId).eq("source","pluggy"),supabase.from("card_purchases").select("id",{count:"exact",head:true}).eq("owner_id",userId).eq("bank_connection_id",connectionId).eq("source","pluggy")]);if(cards.error)databaseFailure(cards.error,stage,"credit_cards.baseline");if(purchases.error)databaseFailure(purchases.error,stage,"card_purchases.baseline");const cardIds=(cards.data??[]).map(card=>String(card.id));let instrumentCount=0;for(const batch of chunks(cardIds)){if(!batch.length)continue;const instruments=await supabase.from("credit_card_instruments").select("id",{count:"exact",head:true}).eq("owner_id",userId).eq("source","pluggy").in("credit_card_id",batch);if(instruments.error)databaseFailure(instruments.error,stage,"credit_card_instruments.baseline");instrumentCount+=instruments.count??0}return {creditAccounts:cardIds.length,cards:cardIds.length,transactions:purchases.count??0,bills:(cards.data??[]).filter(card=>Boolean(card.provider_bill_id)).length,instruments:instrumentCount}}

async function instrumentIdsForTransactions(supabase:DbClient,userId:string,cardId:string,account:PluggyAccount,transactions:import("./types").PluggyTransaction[],stage:SyncStage,counts:Counts){
 const candidates=[accountCardInstrument(account,userId,cardId),...transactions.map(transaction=>{const hint=transactionCardInstrument(transaction,account.id);return hint?{owner_id:userId,credit_card_id:cardId,external_id:hint.externalId,last_four_digits:hint.lastFour,card_kind:hint.cardKind,display_name:`Cartão ${hint.cardKind==="unknown"?"":hint.cardKind}`.trim(),provider_status:"active",source:"pluggy",raw_metadata:hint.metadata}:null})].filter((row):row is NonNullable<typeof row>=>Boolean(row));
 const unique=[...new Map(candidates.map(row=>[row.external_id,row])).values()];if(!unique.length)return new Map<string,string>();const changes=await upsertMany(supabase,"credit_card_instruments",unique,stage,["display_name","card_kind","user_archived_at"]);counts.instrumentsCreated+=changes.created;counts.instrumentsUpdated+=changes.updated;
 const result=await supabase.from("credit_card_instruments").select("id,external_id").eq("owner_id",userId).eq("credit_card_id",cardId).in("external_id",unique.map(row=>row.external_id));if(result.error)databaseFailure(result.error,stage,"credit_card_instruments");counts.instruments+=result.data?.length??0;return new Map((result.data??[]).map(row=>[String(row.external_id),String(row.id)]))
}
async function preserveManualInstrumentAssignments(supabase:DbClient,userId:string,rows:Record<string,unknown>[],stage:SyncStage){if(!rows.length)return rows;const existing=await supabase.from("card_purchases").select("external_id,instrument_id,instrument_last_four,assignment_status,assignment_source,assignment_confirmed_by_user,assigned_at").eq("owner_id",userId).eq("source","pluggy").in("external_id",rows.map(row=>String(row.external_id)));if(existing.error)databaseFailure(existing.error,stage,"card_purchases.manual_assignments");const confirmed=new Map((existing.data??[]).filter(row=>row.assignment_confirmed_by_user).map(row=>[String(row.external_id),row]));return rows.map(row=>{const old=confirmed.get(String(row.external_id));return old?{...row,instrument_id:old.instrument_id,instrument_last_four:old.instrument_last_four,assignment_status:old.assignment_status,assignment_source:old.assignment_source,assignment_confirmed_by_user:true,assigned_at:old.assigned_at}:row})}
async function preserveManualInstallmentCorrections(supabase:DbClient,userId:string,rows:Record<string,unknown>[],stage:SyncStage){if(!rows.length)return rows;const existing=await supabase.from("card_purchases").select("external_id,total_amount,total_purchase_amount,is_installment,installment_number,installment_count,installment_amount,installment_source,installment_confidence,installment_plan_id,installment_manually_confirmed").eq("owner_id",userId).eq("source","pluggy").in("external_id",rows.map(row=>String(row.external_id)));if(existing.error)databaseFailure(existing.error,stage,"card_purchases.manual_installments");const confirmed=new Map((existing.data??[]).filter(row=>row.installment_manually_confirmed).map(row=>[String(row.external_id),row as Record<string,unknown>]));return rows.map(row=>mergeManualInstallmentCorrection(row,confirmed.get(String(row.external_id))))}
async function preserveConfirmedForeignValues(supabase:DbClient,userId:string,rows:Record<string,unknown>[],stage:SyncStage){
 if(!rows.length)return rows;
 const fields=["amount_brl","provider_signed_amount","original_amount","original_currency_code","exchange_rate","foreign_iof_amount","conversion_source","conversion_confidence","converted_at"] as const;
 const existing=await supabase.from("card_purchases").select(["external_id","installment_amount","provider_metadata",...fields].join(",")).eq("owner_id",userId).eq("source","pluggy").in("external_id",rows.map(row=>String(row.external_id)));
 if(existing.error)databaseFailure(existing.error,stage,"card_purchases.foreign_values");
 const existingRows=(existing.data??[]) as unknown as Record<string,unknown>[];
 const confirmed=new Map(existingRows.filter(row=>["pdf","manual"].includes(String(row.conversion_source))).map(row=>[String(row.external_id),row]));
 return rows.map(row=>{
  const old=confirmed.get(String(row.external_id));
  if(!old)return row;
  const incomingMetadata=row.provider_metadata&&typeof row.provider_metadata==="object"&&!Array.isArray(row.provider_metadata)?row.provider_metadata as Record<string,unknown>:{};
  const oldMetadata=old.provider_metadata&&typeof old.provider_metadata==="object"&&!Array.isArray(old.provider_metadata)?old.provider_metadata as Record<string,unknown>:{};
  return {
   ...row,
   installment_amount:old.installment_amount,
   ...Object.fromEntries(fields.map(field=>[field,old[field]])),
   provider_metadata:{
    ...incomingMetadata,
    ...(oldMetadata.foreignManualCorrection?{
     foreignManualCorrection:oldMetadata.foreignManualCorrection,
    }:{}),
   },
  };
 });
}
async function preserveManualTransactionCorrections(supabase:DbClient,userId:string,rows:Record<string,unknown>[],stage:SyncStage){
 if(!rows.length)return rows;
 const fields=["external_id","category_id","transaction_type","transaction_role","financial_origin","cash_flow_kind","bank_direction","financial_nature","financial_role","classification_source","classification_confidence","classification_rule","classification_version","review_status","manually_confirmed","manual_override_at","manual_override_by","user_effective_at","date_source","date_confidence","date_override_reason","competence_date","realized_at"] as const;
 const existing=await supabase.from("financial_transactions").select(fields.join(",")).eq("owner_id",userId).eq("source","pluggy").in("external_id",rows.map(row=>String(row.external_id)));
 if(existing.error)databaseFailure(existing.error,stage,"financial_transactions.manual_overrides");
 const existingRows=(existing.data??[]) as unknown as Record<string,unknown>[];
 const confirmed=new Map(existingRows.filter(row=>row.manually_confirmed).map(row=>[String(row.external_id),row]));
 return rows.map(row=>{const old=confirmed.get(String(row.external_id));if(!old)return row;return {...row,...Object.fromEntries(fields.filter(field=>field!=="external_id").map(field=>[field,old[field]]))}});
}

async function materializeCurrentInvoices(supabase:DbClient,userId:string,connectionId:string,stage:SyncStage,assessment:CompletenessAssessment){
 const cards=await supabase.from("credit_cards").select("id,name,institution_name,last_four_digits,brand,credit_limit,used_limit,current_balance,provider_invoice_total,account_credit_balance,provider_bill_id,provider_bill_closing_date,provider_bill_due_date,provider_cycle_start_date,dates_source,closing_day,due_day,status,visibility,linked_account_id,last_sync_at,source,card_invoice_confirmations(id,card_id,reference_month,official_amount,source,informed_at,note)").eq("owner_id",userId).eq("bank_connection_id",connectionId).eq("status","active");if(cards.error)databaseFailure(cards.error,stage,"credit_cards.invoice_materialization");
 const purchases=await supabase.from("card_purchases").select("id,card_id,external_id,invoice_id,provider_bill_id,instrument_id,instrument_last_four,assignment_status,description,total_amount,total_purchase_amount,is_installment,installment_amount,amount_brl,provider_signed_amount,original_currency_code,exchange_rate,foreign_iof_amount,conversion_source,converted_at,installment_number,installment_count,installment_source,installment_confidence,installment_plan_id,installment_manually_confirmed,purchase_date,posting_date,competence_date,source,source_type,financial_origin,transaction_role,status,review_status,invoice_reference,bill_forecast_date,provider_category,merchant,visibility,category_id,original_amount").eq("owner_id",userId).eq("bank_connection_id",connectionId).order("competence_date",{ascending:false}).limit(5000);if(purchases.error)databaseFailure(purchases.error,stage,"card_purchases.invoice_materialization");
 const cardIds=(cards.data??[]).map(card=>String(card.id));const storedRows:Record<string,unknown>[]=[];for(const batch of chunks(cardIds)){if(!batch.length)continue;const stored=await supabase.from("card_invoices").select("id,card_id,reference_month,total_amount,invoice_total,outstanding_amount,purchase_count,provider_invoice_total,calculated_invoice_total,manual_invoice_total,confirmed_invoice_total,purchases_total,credits_total,adjustments_total,instruments_total,unassigned_total,unassigned_transactions_total,general_adjustments_total,reconciliation_difference,reconciliation_status,invoice_breakdown,last_reliable_invoice_total,current_display_total,last_reliable_purchase_count,last_sync_at,last_complete_sync_at,stale_since,provider_status,preservation_reason").eq("owner_id",userId).in("card_id",batch);if(stored.error)databaseFailure(stored.error,stage,"card_invoices.previous_state");storedRows.push(...(stored.data??[]) as Record<string,unknown>[])}
 const previousByKey=new Map(storedRows.map(row=>[`${row.card_id}:${String(row.reference_month).slice(0,7)}`,row]));
 const currentInvoices=buildCurrentCardInvoices((cards.data??[]) as CreditCard[],(purchases.data??[]) as CardPurchase[]);
 const invoices=[...currentInvoices,...currentInvoices.flatMap(invoice=>invoice.cycle?buildCurrentCardInvoices([invoice.card],(purchases.data??[]) as CardPurchase[],new Date(`${invoice.cycle.previousCycleEnd}T12:00:00Z`)):[])];
 const linkedPurchaseIds=new Set<string>();
 for(const invoice of invoices){if(!invoice.cycle)continue;const syncedAt=new Date().toISOString();const referenceMonth=`${invoice.cycle.referenceMonth}-01`;const incoming={owner_id:userId,card_id:invoice.card.id,reference_month:referenceMonth,cycle_start_date:invoice.cycle.cycleStart,cycle_end_date:invoice.cycle.cycleEnd,closing_date:invoice.cycle.closingDate,due_date:invoice.cycle.dueDate,total_amount:invoice.invoiceTotal,purchases_total:invoice.purchasesTotal,credits_total:invoice.creditsTotal,adjustments_total:invoice.adjustmentsTotal,instruments_total:invoice.instrumentsTotal,unassigned_total:invoice.unassignedTotal,unassigned_transactions_total:invoice.unassignedTotal,general_adjustments_total:invoice.generalAdjustmentsTotal,invoice_total:invoice.invoiceTotal,paid_amount:invoice.paidAmount,outstanding_amount:invoice.outstandingAmount,purchase_count:invoice.purchaseCount,status:invoice.paidAmount>=invoice.invoiceTotal&&invoice.invoiceTotal>0?"paid":invoice.paidAmount>0?"partially_paid":"open",source:invoice.totalSource==="provider_bill"?"pluggy_bill":invoice.totalSource==="manual_bank_confirmation"?"manual":"calculated",total_source:invoice.totalSource,external_id:`atlas:${invoice.card.id}:${invoice.cycle.referenceMonth}`,provider_updated_at:invoice.card.last_sync_at,provider_invoice_total:invoice.providerInvoiceTotal,account_credit_balance:invoice.accountCreditBalance,pending_transactions_total:invoice.pendingTransactionsTotal,calculated_invoice_total:invoice.calculatedInvoiceTotal,reconciliation_difference:invoice.reconciliationDifference,reconciliation_status:invoice.reconciliationStatus,invoice_breakdown:Object.fromEntries([...invoice.instrumentTotals.map(item=>[`instrument:${item.instrumentId}`,item.netTotal]),["unassigned",invoice.unassignedTotal]]),updated_at:syncedAt};const merged=mergeInvoicePersistenceRow({previous:previousByKey.get(`${invoice.card.id}:${invoice.cycle.referenceMonth}`)??null,incoming,completeness:assessment.completeness,reasons:assessment.reasons,syncedAt});if(merged.preserved)console.warn("[Atlas Invoice Preservation]",{card:maskId(invoice.card.id),...merged.diagnostic});const saved=await supabase.from("card_invoices").upsert(merged.row,{onConflict:"card_id,reference_month"}).select("id").single();if(saved.error)databaseFailure(saved.error,stage,"card_invoices.upsert");const ids=invoice.purchases.filter(purchase=>purchase.status!=="cancelled"&&!linkedPurchaseIds.has(purchase.id)).map(purchase=>purchase.id);for(const batch of chunks(ids)){if(!batch.length)continue;const linked=await supabase.from("card_purchases").update({invoice_id:String(saved.data.id)}).eq("owner_id",userId).eq("card_id",invoice.card.id).in("id",batch);if(linked.error)databaseFailure(linked.error,stage,"card_purchases.link_invoice");batch.forEach(id=>linkedPurchaseIds.add(id))}}
}

async function persistCreditSyncDiagnostics(supabase:DbClient,userId:string,runId:string,states:Map<string,CreditDiagnosticState>,stage:SyncStage){
 for(const state of states.values()){
  const persistedRows:Record<string,unknown>[]=[];for(const batch of chunks([...state.externalIds])){if(!batch.length)continue;const result=await supabase.from("card_purchases").select("id,card_id,external_id,invoice_id,provider_bill_id,instrument_id,instrument_review_status,description,total_amount,total_purchase_amount,is_installment,installment_amount,installment_number,installment_count,installment_source,installment_confidence,installment_plan_id,installment_manually_confirmed,purchase_date,competence_date,source,source_type,financial_origin,transaction_role,status,review_status,invoice_reference,bill_forecast_date,provider_category,merchant,visibility,category_id,original_amount").eq("owner_id",userId).eq("card_id",state.cardId).eq("source","pluggy").in("external_id",batch);if(result.error)databaseFailure(result.error,stage,"card_purchases.sync_diagnostics");persistedRows.push(...(result.data??[]) as Record<string,unknown>[])}
  const card=await supabase.from("credit_cards").select("id,name,institution_name,last_four_digits,brand,credit_limit,used_limit,current_balance,provider_invoice_total,account_credit_balance,provider_bill_id,provider_bill_closing_date,provider_bill_due_date,provider_cycle_start_date,dates_source,closing_day,due_day,status,visibility,linked_account_id,last_sync_at,source,card_invoice_confirmations(id,card_id,reference_month,official_amount,source,informed_at,note)").eq("id",state.cardId).eq("owner_id",userId).single();if(card.error)databaseFailure(card.error,stage,"credit_cards.sync_diagnostics");
  const inclusion=analyzeInvoiceInclusion(card.data as unknown as CreditCard,persistedRows as unknown as CardPurchase[]);const exclusionCounts={...inclusion.exclusionCounts,duplicate:inclusion.exclusionCounts.duplicate+state.duplicateIds,unsupported_type:Math.max(0,state.received-state.mapped),mapping_failure:Math.max(0,state.mapped-state.duplicateIds-persistedRows.length)};
  const saved=await supabase.from("credit_card_sync_diagnostics").insert({owner_id:userId,sync_run_id:runId,card_id:state.cardId,received_from_pluggy:state.received,mapped:state.mapped,persisted:persistedRows.length,included_in_invoice:inclusion.includedCount,excluded_from_invoice:Math.max(0,state.received-inclusion.includedCount),pages:state.pages,page_sizes:state.pageSizes,status_counts:state.statusCounts,classification_counts:state.classificationCounts,reference_counts:state.referenceCounts,instrument_counts:state.instrumentCounts,exclusion_counts:exclusionCounts});if(saved.error)databaseFailure(saved.error,stage,"credit_card_sync_diagnostics.insert");
 }
}

export async function syncPluggyItem(supabase:DbClient,userId:string,connectionId:string,full=false){
 const started=Date.now();let currentStage:SyncStage="connection_load";let itemId="unknown";let runId:string|null=null;let providerWarningCount=0;const counts=emptyCounts();const warnings:string[]=[];const creditDiagnostics=new Map<string,CreditDiagnosticState>();const transferCandidates:{id:string;accountId:string;amount:number;direction:"in"|"out";date:string;description:string}[]=[];
 try{
  const connection=await supabase.from("bank_connections").select("id,provider_connection_id,status,last_successful_sync_at,last_complete_counts,stale_since").eq("id",connectionId).eq("owner_id",userId).eq("provider","pluggy").single();if(connection.error)databaseFailure(connection.error,currentStage,"bank_connections");if(!connection.data)throw new IntegrationSyncError("Conexão Pluggy não encontrada.",{code:"connection_not_found",stage:currentStage});if(connection.data.status==="disabled")throw new IntegrationSyncError("Esta conexão foi removida.",{code:"connection_disabled",stage:currentStage});itemId=String(connection.data.provider_connection_id);
  const baselineSnapshot=storedSnapshot(connection.data.last_complete_counts)??await existingSnapshot(supabase,userId,connectionId,currentStage);
  let effectiveFull=full;if(!full){const history=await supabase.from("financial_sync_runs").select("mode,status,started_at").eq("owner_id",userId).eq("bank_connection_id",connectionId).order("started_at",{ascending:false}).limit(50);if(history.error)databaseFailure(history.error,currentStage,"financial_sync_runs.recovery_check");effectiveFull=shouldRecoverFullHistory((history.data??[]).map(run=>({mode:String(run.mode),status:String(run.status),started_at:String(run.started_at)})))}
  currentStage="sync_run_begin";const begin=await supabase.rpc("begin_financial_sync",{target_connection:connectionId,full_sync:effectiveFull});if(begin.error)databaseFailure(begin.error,currentStage,"rpc:begin_financial_sync");runId=String(begin.data);const lastSuccess=connection.data.last_successful_sync_at?new Date(String(connection.data.last_successful_sync_at)):null;const dateFrom=!effectiveFull&&lastSuccess&&!Number.isNaN(lastSuccess.valueOf())?new Date(lastSuccess.valueOf()-3*86400000).toISOString().slice(0,10):undefined;
  currentStage="auth";let item:Awaited<ReturnType<typeof getPluggyItem>>;try{item=await getPluggyItem(itemId)}catch(error){const normalized=normalizeIntegrationError(error);currentStage=normalized.operation==="POST /auth"?"auth":"item";throw error}
  try{await syncMinimalIdentity({supabase,ownerId:userId,connectionId,itemId})}catch(error){const normalized=normalizeIntegrationError(error);if(normalized.code==="ITEM_ORIGINAL_CONNECTED_WITH_DIFFERENT_ACCOUNT")throw error;warnings.push(optionalWarning(wrap(error,"item","Falha ao validar identidade mínima."),{stage:"item",started,userId,itemId},"A titularidade não pôde ser verificada nesta sincronização."))}
  if(String(item.executionStatus??"").toUpperCase()==="PARTIAL_SUCCESS")providerWarningCount++;
  currentStage="accounts_fetch";const providerAccounts=list(await getPluggyAccounts(itemId) as PluggyAccount[]|PluggyPage<PluggyAccount>,currentStage);const bankAccounts=providerAccounts.filter(account=>String(account.type).toUpperCase()!=="CREDIT");const cardAccounts=providerAccounts.filter(account=>String(account.type).toUpperCase()==="CREDIT");const institution=item.connector?.name??null;console.info("[Atlas Pluggy Credit Accounts]",{count:cardAccounts.length,sharedBalanceGroupSizes:sharedBalanceGroupSizes(cardAccounts),cards:cardAccounts.map(account=>{const diagnostic=safeCreditAccountDiagnostic(account);return {...diagnostic,externalId:maskId(diagnostic.externalId)}})});
  currentStage="accounts_upsert";const accountChanges=await upsertMany(supabase,"financial_accounts",bankAccounts.map(account=>({...mapAccount(account,userId,connectionId),institution_name:institution})),currentStage,["name","account_type","visibility","workspace_id","status","color","icon","opening_balance"],["current_balance"]);counts.accounts=bankAccounts.length;counts.accountsCreated=accountChanges.created;counts.accountsUpdated=accountChanges.updated;const accountMap=await targetMap(supabase,"financial_accounts",userId,bankAccounts.map(account=>account.id),currentStage);
  const billsByProviderAccount=new Map<string,PluggyBill[]>();const billContexts=new Map<string,ReturnType<typeof selectCurrentPluggyBill>>();for(const account of cardAccounts){try{currentStage="bills_fetch";const bills=list(await getPluggyBills(account.id) as PluggyBill[]|PluggyPage<PluggyBill>,currentStage);billsByProviderAccount.set(account.id,bills);const context=selectCurrentPluggyBill(bills,new Date(),account.id);billContexts.set(account.id,context);console.info("[Atlas Pluggy Credit Bills]",{account:maskId(account.id),...safeBillDiagnostic(bills,context.current)})}catch(error){providerWarningCount++;warnings.push(optionalWarning(wrap(error,currentStage,"Falha ao consultar faturas oficiais."),{stage:currentStage,started,userId,itemId},"Fatura oficial indisponível; será usada a soma conciliada do ciclo."))}}
  const billAccounts=new Map<string,string[]>();for(const [accountId,context] of billContexts){if(!context.current)continue;const accounts=billAccounts.get(context.current.id)??[];accounts.push(accountId);billAccounts.set(context.current.id,accounts)}for(const [billId,accounts] of billAccounts){if(accounts.length<2)continue;for(const accountId of accounts)billContexts.set(accountId,{current:null,previous:null,cycleStart:null});warnings.push(`Bill ${maskId(billId)} foi devolvida para mais de uma conta de crédito e não foi usada como total oficial.`)}
  let cardMap=new Map<string,string>();try{currentStage="cards_upsert";const providerValuesReliable=String(item.status??"").toUpperCase()==="UPDATED"&&providerWarningCount===0;const providerFields=["credit_limit","used_limit","current_balance","provider_invoice_total","account_credit_balance","provider_bill_id","provider_bill_closing_date","provider_bill_due_date","provider_cycle_start_date","closing_day","due_day","dates_source"];const mappedCards=cardAccounts.map(account=>{const row={...mapCard(account,userId,connectionId,billContexts.get(account.id)),institution_name:institution} as Record<string,unknown>;if(!providerValuesReliable)for(const field of providerFields)row[field]=undefined;return row});const cardChanges=await upsertMany(supabase,"credit_cards",mappedCards,currentStage,["name","visibility","workspace_id","status","linked_account_id"],providerFields);counts.cards=cardAccounts.length;counts.cardsCreated=cardChanges.created;counts.cardsUpdated=cardChanges.updated;cardMap=await targetMap(supabase,"credit_cards",userId,cardAccounts.map(account=>account.id),currentStage)}catch(error){providerWarningCount++;warnings.push(optionalWarning(wrap(error,currentStage,"Falha ao importar cartões."),{stage:currentStage,started,userId,itemId},"Cartões não puderam ser atualizados."))}
  for(const account of cardAccounts){const localCardId=cardMap.get(account.id);if(localCardId)await instrumentIdsForTransactions(supabase,userId,localCardId,account,[],currentStage,counts)}
  for(const account of providerAccounts){
   const isCreditCard=String(account.type).toUpperCase()==="CREDIT";
   const localId=isCreditCard?cardMap.get(account.id):accountMap.get(account.id);
   if(!localId){warnings.push(isCreditCard?"Card transactions were skipped because the card was not persisted.":"Bank transactions were skipped because the account was not persisted.");continue}
   if(isCreditCard)creditDiagnostics.set(account.id,{cardId:localId,received:0,mapped:0,pages:0,pageSizes:[],externalIds:new Set(),duplicateIds:0,statusCounts:{},classificationCounts:{},referenceCounts:{withBillId:0,withoutBillId:0,withBillForecastDate:0,withoutBillForecastDate:0},instrumentCounts:{}});
   try{
    let after:string|undefined;let pageGuard=0;
    do{
     currentStage="transactions_fetch";const page=await getPluggyTransactions(account.id,after,dateFrom);const rawTransactions=list(page,currentStage);const transactions=rawTransactions.filter(transaction=>Math.abs(Number(transaction.amount??0))>0);counts.transactionsSkipped+=rawTransactions.length-transactions.length;
     if(isCreditCard){
      const diagnostic=creditDiagnostics.get(account.id)!;
      diagnostic.received+=rawTransactions.length;diagnostic.pages++;diagnostic.pageSizes.push(rawTransactions.length);
      for(const transaction of rawTransactions){
       if(diagnostic.externalIds.has(transaction.id))diagnostic.duplicateIds++;else diagnostic.externalIds.add(transaction.id);
       const status=String(transaction.status??"UNKNOWN");diagnostic.statusCounts[status]=(diagnostic.statusCounts[status]??0)+1;
       const metadata=transaction.creditCardMetadata&&typeof transaction.creditCardMetadata==="object"?transaction.creditCardMetadata:{};
       for(const field of ["installmentNumber","totalInstallments","totalAmount"] as const)if(metadata[field]!==undefined){const key=`field_${field}`;diagnostic.classificationCounts[key]=(diagnostic.classificationCounts[key]??0)+1}
       if(typeof metadata.billId==="string"&&metadata.billId)diagnostic.referenceCounts.withBillId++;else diagnostic.referenceCounts.withoutBillId++;
       if(typeof metadata.billForecastDate==="string"&&metadata.billForecastDate)diagnostic.referenceCounts.withBillForecastDate++;else diagnostic.referenceCounts.withoutBillForecastDate++;
       const hint=transactionCardInstrument(transaction,account.id);const instrument=hint?.lastFour??"unassigned";diagnostic.instrumentCounts[instrument]=(diagnostic.instrumentCounts[instrument]??0)+1;
      }
     }
     currentStage="transactions_map";
     if(isCreditCard){console.info("[Atlas Pluggy Credit Transactions]",{account:maskId(account.id),page:creditDiagnostics.get(account.id)?.pages,pageSize:rawTransactions.length,hasNext:Boolean(page.next),...safeCreditTransactionDiagnostic(transactions)});currentStage="transactions_upsert";const instrumentIds=await instrumentIdsForTransactions(supabase,userId,localId,account,transactions,currentStage,counts);const mappedRows=transactions.map(transaction=>{const hint=transactionCardInstrument(transaction,account.id);const instrumentId=hint?instrumentIds.get(hint.externalId)??null:null;if(!instrumentId)counts.pendingInstruments++;return {...mapCardPurchase(transaction,userId,connectionId,localId),instrument_id:instrumentId,instrument_last_four:hint?.lastFour??null,instrument_review_status:instrumentId?"identified":"pending",assignment_status:instrumentId?"assigned":"unassigned",assignment_source:instrumentId?"provider_last_four":"provider_not_provided",assignment_confirmed_by_user:false,assigned_at:instrumentId?new Date().toISOString():null}});const diagnostic=creditDiagnostics.get(account.id)!;diagnostic.mapped+=mappedRows.length;for(const row of mappedRows){const role=String(row.transaction_role);diagnostic.classificationCounts[role]=(diagnostic.classificationCounts[role]??0)+1;if(row.is_installment)diagnostic.classificationCounts.installment=(diagnostic.classificationCounts.installment??0)+1;if(row.installment_source==="provider_structured")diagnostic.classificationCounts.installment_structured=(diagnostic.classificationCounts.installment_structured??0)+1;if(row.installment_source==="provider_description")diagnostic.classificationCounts.installment_description=(diagnostic.classificationCounts.installment_description??0)+1;if(row.installment_confidence==="unknown")diagnostic.classificationCounts.installment_unknown=(diagnostic.classificationCounts.installment_unknown??0)+1;if(row.status==="cancelled")diagnostic.classificationCounts.cancelled=(diagnostic.classificationCounts.cancelled??0)+1}const assigned=await preserveManualInstrumentAssignments(supabase,userId,mappedRows,currentStage);const installmentRows=await preserveManualInstallmentCorrections(supabase,userId,assigned,currentStage);const rows=await preserveConfirmedForeignValues(supabase,userId,installmentRows,currentStage);const changes=await upsertMany(supabase,"card_purchases",rows,currentStage,["category_id","visibility"]);counts.transactionsCreated+=changes.created;counts.transactionsUpdated+=changes.updated}
     else{currentStage="transactions_upsert";const mapped=transactions.map(transaction=>mapTransaction(transaction,userId,connectionId,{accountId:localId,accountType:account.type}));if(process.env.NODE_ENV==="development"){for(const row of mapped){if(!String(row.classification_rule).includes("type_sign_conflict")&&row.classification_confidence!=="low")continue;console.warn("[Atlas Bank Classification]",{external:maskId(String(row.external_id)),accountType:account.type??null,providerType:row.provider_type,operationType:row.operation_type,rule:row.classification_rule,newRole:row.financial_role,dateSource:row.date_source})}}const rows=await preserveManualTransactionCorrections(supabase,userId,mapped,currentStage);const changes=await upsertMany(supabase,"financial_transactions",rows,currentStage);counts.transactionsCreated+=changes.created;counts.transactionsUpdated+=changes.updated;for(const transaction of transactions)transferCandidates.push({id:transaction.id,accountId:account.id,amount:Math.abs(Number(transaction.amount??0)),direction:providerBankDirection(transaction)==="inflow"?"in":"out",date:String(transaction.date??""),description:String(transaction.description??"")})}
     counts.transactions+=transactions.length;counts.pages++;after=cursorFromNext(page.next);const received=isCreditCard?creditDiagnostics.get(account.id)?.received??rawTransactions.length:counts.transactions;if(hasInterruptedPagination({page:page.page,totalPages:page.totalPages,total:page.total,totalResults:page.totalResults,received,hasNext:Boolean(after)}))throw new IntegrationSyncError("Transaction pagination ended before all results were loaded.",{code:"pluggy_pagination_incomplete",stage:currentStage});if(++pageGuard>=200)throw new IntegrationSyncError("Transaction pagination exceeded the safety limit.",{code:"pluggy_pagination_limit",stage:currentStage});
    }while(after)
   }catch(error){counts.transactionFailures++;warnings.push(optionalWarning(wrap(error,currentStage,"Failed to import transactions."),{stage:currentStage,started,userId,itemId},"Some transactions could not be updated."))}
  }
  if(!effectiveFull&&dateFrom){for(const state of creditDiagnostics.values()){if(state.received>0)continue;const recent=await supabase.from("card_purchases").select("id",{count:"exact",head:true}).eq("owner_id",userId).eq("card_id",state.cardId).eq("source","pluggy").gte("competence_date",dateFrom);if(recent.error)databaseFailure(recent.error,currentStage,"card_purchases.partial_detection");if((recent.count??0)>0){providerWarningCount++;warnings.push("Uma conta de cartão anteriormente populada retornou sem transações recentes; os dados anteriores foram preservados.")}}}
  try{if(runId)await persistCreditSyncDiagnostics(supabase,userId,runId,creditDiagnostics,currentStage)}catch(error){warnings.push(optionalWarning(wrap(error,currentStage,"Falha ao registrar diagnóstico das faturas."),{stage:currentStage,started,userId,itemId},"Diagnóstico detalhado das faturas não pôde ser persistido."))}
  try{currentStage="transactions_upsert";for(const batch of chunks([...findSuspectedTransferIds(transferCandidates)])){const result=await supabase.from("financial_transactions").update({transaction_type:"transfer",transaction_role:"transfer",financial_origin:"transfer",cash_flow_kind:"transfer_internal",bank_direction:"neutral",financial_nature:"transfer_internal",financial_role:"transfer",classification_source:"provider_structured",classification_confidence:"high",classification_rule:"bank.internal_transfer.matched_counterpart",classification_version:BANK_CLASSIFIER_VERSION,suspected_transfer:false,review_status:"reviewed"}).eq("owner_id",userId).eq("source","pluggy").eq("manually_confirmed",false).in("external_id",batch);if(result.error)databaseFailure(result.error,currentStage,"financial_transactions")}}catch(error){warnings.push(optionalWarning(wrap(error,currentStage,"Falha ao classificar transferências internas."),{stage:currentStage,started,userId,itemId},"Possíveis transferências aguardam nova análise."))}
  try{for(let pageNumber=1;pageNumber<=100;pageNumber++){currentStage="investments_fetch";const page=await getPluggyInvestments(itemId,pageNumber);const rows=list(page,currentStage);currentStage="investments_upsert";const changes=await upsertMany(supabase,"financial_investments",rows.map(row=>mapInvestment(row,userId,connectionId)),currentStage,["name","visibility","workspace_id"]);counts.investmentsCreated+=changes.created;counts.investmentsUpdated+=changes.updated;counts.investments+=rows.length;counts.pages++;if(!rows.length||rows.length<500||(page.totalPages&&pageNumber>=page.totalPages))break}}catch(error){const unavailable=error instanceof PluggyApiError&&[403,404].includes(error.status??0);warnings.push(optionalWarning(wrap(error,currentStage,"Falha ao importar investimentos."),{stage:currentStage,started,userId,itemId},unavailable?"Investimentos indisponíveis para este conector.":"Investimentos não puderam ser atualizados."))}
  try{
   currentStage="loans_fetch";const providerLoans=list(await getPluggyLoans(itemId),currentStage);
   currentStage="loans_map";const loans=providerLoans.map(loan=>mapPluggyLoanToFinancialLoan(loan,userId,connectionId,institution));
   currentStage="loans_upsert";const changes=await upsertMany(supabase,"financial_loans",loans.map(loan=>({...loan,status:"active"})),currentStage,["name","visibility","workspace_id"]);counts.loans=loans.length;counts.loansCreated=changes.created;counts.loansUpdated=changes.updated;
   if(loans.length){const local=await supabase.from("financial_loans").select("id,external_id,name,installment_amount,installment_count,installments_paid,installments_remaining,first_installment_date,final_due_date,payroll_deducted").eq("owner_id",userId).eq("bank_connection_id",connectionId).eq("source","pluggy").eq("status","active");if(local.error)databaseFailure(local.error,currentStage,"financial_loans.projections");for(const loan of local.data??[]){const rows=buildLoanProjections({loanId:String(loan.id),ownerId:userId,externalId:String(loan.external_id),name:String(loan.name),installmentAmount:loan.installment_amount===null?null:Number(loan.installment_amount),installmentCount:loan.installment_count===null?null:Number(loan.installment_count),installmentsPaid:loan.installments_paid===null?null:Number(loan.installments_paid),installmentsRemaining:loan.installments_remaining===null?null:Number(loan.installments_remaining),firstInstallmentDate:loan.first_installment_date?String(loan.first_installment_date):null,finalDueDate:loan.final_due_date?String(loan.final_due_date):null,payrollDeducted:Boolean(loan.payroll_deducted),source:"pluggy"});if(rows.length){const forecasts=await upsertMany(supabase,"financial_transactions",rows,currentStage);counts.transactionsCreated+=forecasts.created;counts.transactionsUpdated+=forecasts.updated}}}
   const state=await supabase.from("bank_connections").update({loans_sync_status:loans.length?"available":"empty",loans_sync_message:loans.length?null:"Seu banco não disponibilizou contratos de empréstimo nesta conexão.",last_loans_sync_at:new Date().toISOString()}).eq("id",connectionId).eq("owner_id",userId);if(state.error)databaseFailure(state.error,currentStage,"bank_connections.loans_state");
  }catch(error){const unavailable=error instanceof PluggyApiError&&[403,404].includes(error.status??0);const state=await supabase.from("bank_connections").update({loans_sync_status:unavailable?"unavailable":"error",loans_sync_message:unavailable?"Empréstimos não estão disponíveis neste conector.":"Não foi possível atualizar os empréstimos agora.",last_loans_sync_at:new Date().toISOString()}).eq("id",connectionId).eq("owner_id",userId);if(state.error)console.error("[Atlas Supabase Failure]",{stage:currentStage,table:"bank_connections.loans_state",code:sanitizeDiagnostic(state.error.code),message:sanitizeDiagnostic(state.error.message)});warnings.push(optionalWarning(wrap(error,currentStage,"Falha ao importar empréstimos."),{stage:currentStage,started,userId,itemId},unavailable?"Empréstimos indisponíveis para este conector.":"Empréstimos não puderam ser atualizados."))}
  const previousSnapshot=baselineSnapshot;
  const instrumentKeys=new Set<string>();for(const account of cardAccounts){const instrument=accountCardInstrument(account,userId,cardMap.get(account.id)??"unknown");if(instrument)instrumentKeys.add(instrument.external_id)}for(const [accountId,state] of creditDiagnostics)for(const key of Object.keys(state.instrumentCounts))if(key!=="unassigned")instrumentKeys.add(`account:${accountId}:last4:${key}`);
  const observedTransactions=[...creditDiagnostics.values()].reduce((sum,state)=>sum+state.received,0);
  const currentSnapshot:SyncSnapshot={creditAccounts:cardAccounts.length,cards:cardMap.size,transactions:effectiveFull||!previousSnapshot?observedTransactions:previousSnapshot.transactions,bills:[...billsByProviderAccount.values()].reduce((sum,bills)=>sum+bills.length,0),instruments:effectiveFull||!previousSnapshot?instrumentKeys.size:previousSnapshot.instruments};
  const assessment=assessSyncCompleteness({previous:previousSnapshot,current:currentSnapshot,full:effectiveFull,warningCount:providerWarningCount,transactionFailures:counts.transactionFailures,itemStatus:item.status??null});
  if(assessment.completeness==="partial")warnings.push("Dados do provedor parcialmente indisponíveis; o último estado confiável foi preservado.");
  try{currentStage="transactions_upsert";await materializeCurrentInvoices(supabase,userId,connectionId,currentStage,assessment)}catch(error){warnings.push(optionalWarning(wrap(error,currentStage,"Falha ao recalcular faturas vigentes."),{stage:currentStage,started,userId,itemId},"Faturas vigentes não puderam ser atualizadas."))}
  currentStage="bills_fetch";await persistOfficialBills({supabase,ownerId:userId,connectionId,billsByProviderAccount,cardMap,complete:assessment.completeness==="complete"});
  currentStage="connection_update";
  const providerState=assessment.completeness==="partial"?"degraded":"available";
  const update=await supabase.from("bank_connections").update({connector_name:item.connector?.name??null,last_provider_update_at:item.updatedAt??null,sync_cursor:{lastWindowStart:dateFrom??null,transactionIncomplete:counts.transactionFailures>0},metadata:{itemStatus:item.status??null,executionStatus:item.executionStatus??null,partialReasons:assessment.reasons},provider_status:providerState,provider_sync_state:assessment.completeness==="partial"?"partial":"success",data_completeness:assessment.completeness,incident_message:assessment.completeness==="partial"?"O provedor retornou dados parciais. O último estado confiável foi mantido.":null,user_message:assessment.completeness==="partial"?"A atualização não trouxe todos os dados. O último valor confiável foi preservado.":null,action_required:null,is_complete:assessment.completeness==="complete",pages_received:counts.pages,total_pages:counts.pages,records_received:counts.transactions+currentSnapshot.bills,stale_since:assessment.completeness==="partial"?connection.data.stale_since??new Date().toISOString():null,partial_data_count:assessment.partialDataCount}).eq("id",connectionId).eq("owner_id",userId);if(update.error)databaseFailure(update.error,currentStage,"bank_connections");
  const resourceState=assessment.completeness==="partial"?"degraded":"active";for(const table of ["financial_accounts","credit_cards"] as const){const state=await supabase.from(table).update({provider_status:resourceState}).eq("owner_id",userId).eq("bank_connection_id",connectionId).eq("source","pluggy");if(state.error)databaseFailure(state.error,currentStage,`${table}.provider_status`)}
  currentStage="sync_run_finalize";const finalStatus=assessment.completeness==="partial"?"completed_with_warnings":"completed";const safeMessage=assessment.completeness==="partial"?"Dados do provedor parcialmente indisponíveis; o último estado confiável foi preservado.":null;const finish=await supabase.rpc("finish_financial_sync",{target_run:runId,final_status:finalStatus,counters:{...counts,...currentSnapshot},failure_code:assessment.completeness==="partial"?"partial_coverage":null,failure_message:safeMessage});if(finish.error)databaseFailure(finish.error,currentStage,"rpc:finish_financial_sync");if(counts.transactionFailures){const checkpoint=await supabase.from("bank_connections").update({last_successful_sync_at:connection.data.last_successful_sync_at??null,sync_cursor:{lastWindowStart:dateFrom??null,transactionIncomplete:true}}).eq("id",connectionId).eq("owner_id",userId);if(checkpoint.error)databaseFailure(checkpoint.error,currentStage,"bank_connections.checkpoint")}console.info("[Atlas Pluggy Sync]",{operation:"sync",stage:currentStage,status:finalStatus,mode:effectiveFull?"full":"incremental",completeness:assessment.completeness,partialReasons:assessment.reasons,durationMs:Date.now()-started,user:maskId(userId),item:maskId(itemId),counts,warnings:warnings.length});return {counts,warnings};
 }catch(error){const failure=wrap(error,currentStage,"A sincronização não pôde ser concluída.");const normalized=logIntegrationFailure(failure,{stage:currentStage,durationMs:Date.now()-started,user:userId,item:itemId});const mapped=mapPluggyError(normalized.code);try{await supabase.from("bank_connections").update({provider_sync_state:mapped?.syncStatus??"error",provider_status:mapped?.syncStatus==="connector_offline"?"unavailable":"degraded",user_message:mapped?.message??"Não foi possível atualizar a conexão agora.",action_required:mapped?.action??null,is_complete:false,stale_since:new Date().toISOString()}).eq("id",connectionId).eq("owner_id",userId)}catch{}if(runId){const finish=await supabase.rpc("finish_financial_sync",{target_run:runId,final_status:"failed",counters:counts,failure_code:normalized.code??"sync_failed",failure_message:mapped?.message??"Falha de sincronização."});if(finish.error)console.error("[Atlas Supabase Failure]",{stage:"sync_run_finalize",table:"rpc:finish_financial_sync",code:sanitizeDiagnostic(finish.error.code),message:sanitizeDiagnostic(finish.error.message),details:sanitizeDiagnostic(finish.error.details),hint:sanitizeDiagnostic(finish.error.hint)})}throw failure}
}
