import Link from "next/link";
import type { FlightScheduleImport } from "@/modules/flight/types";
import { FlightMonthCalendar, type CalendarLeg } from "./flight-month-calendar";

type ActivityData = { counts: Record<string, number>; days: Array<{ date: string; events: Array<{ type: string; code: string; label: string | null; start: string | null; end: string | null; location: string | null }> }> };
type RuleSummary = { pass: number; fail: number; unknown: number; notApplicable: number };
type Props = { label: string; planned: FlightScheduleImport | null; current: FlightScheduleImport | null; activity: ActivityData | undefined; legs: CalendarLeg[]; audit: RuleSummary; closure: { gross: number | null; net: number | null; deductions: number | null } | null; cycles: Array<{ paymentDate: string; currency: string | null; amount: number; status: string }> };

const money = (value: number | null, currency = "BRL") => value === null ? "—" : new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value / 100);
const duration = (minutes: number | null | undefined) => minutes === null || minutes === undefined ? "—" : `${Math.floor(minutes / 60)}:${String(minutes % 60).padStart(2, "0")}`;
const delta = (current: number | null | undefined, planned: number | null | undefined) => current === null || current === undefined || planned === null || planned === undefined ? "—" : `${current - planned >= 0 ? "+" : ""}${duration(current - planned)}`;

function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) { return <div className="min-w-0 border-l border-[var(--atlas-border)] pl-4 first:border-l-0 first:pl-0"><p className="text-sm font-medium uppercase tracking-wide text-[var(--atlas-muted)]">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">{value}</p>{note ? <p className="mt-1 text-sm text-[var(--atlas-muted)]">{note}</p> : null}</div>; }
function Card({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-[var(--atlas-border)] bg-[var(--atlas-surface)] p-4 shadow-sm backdrop-blur-sm sm:p-5 ${className}`}><h2 className="text-sm font-semibold">{title}</h2>{children}</section>; }

export function FlightMonthOverview({ label, planned, current, activity, legs, audit, closure, cycles }: Props) {
  const days = activity?.days ?? []; const off = activity?.counts.OFF ?? current?.official_off_days ?? 0; const standby = activity?.counts.STANDBY ?? 0;
  return <div className="grid gap-4 sm:gap-5">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="atlas-label">Atlas Flight</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Resumo</h1><p className="mt-1 capitalize text-sm text-[var(--atlas-muted)]">{label}</p></div><nav aria-label="Navegação Flight" className="flex flex-wrap gap-x-4 gap-y-2 text-sm"><span className="border-b-2 border-[var(--atlas-blue)] pb-1 font-semibold">Resumo</span><Link href="#agenda" className="text-[var(--atlas-muted)] hover:text-[var(--atlas-text)]">Escala</Link><Link href="/escala/regras" className="text-[var(--atlas-muted)] hover:text-[var(--atlas-text)]">Auditoria</Link><Link href="#financeiro" className="text-[var(--atlas-muted)] hover:text-[var(--atlas-text)]">Financeiro</Link><Link href="/escala/diarias" className="text-[var(--atlas-muted)] hover:text-[var(--atlas-text)]">Diárias</Link><Link href="/escala/regras" className="text-[var(--atlas-muted)] hover:text-[var(--atlas-text)]">Regras</Link></nav></header>
    <div className="grid gap-4 xl:grid-cols-[1.8fr_1fr]"><Card title="Resumo do mês"><div className="mt-4 grid grid-cols-2 gap-5 sm:grid-cols-5"><Metric label="FT" value={duration(current?.official_month_flight_time_minutes)} note="h:mm" /><Metric label="DT" value={duration(current?.official_month_duty_time_minutes)} note="h:mm" /><Metric label="Folgas" value={off} note="dias" /><Metric label="Sobreaviso" value={standby} note="ocorrências" /><Metric label="Snapshot" value={current?.snapshot_number ?? "—"} note="execução atual" /></div></Card><Card title="Auditoria 3B"><p className="mt-3 text-sm font-medium text-[var(--atlas-positive)]">Auditoria concluída com pendências conhecidas</p><div className="mt-4 grid grid-cols-4 gap-2 text-center text-sm"><Metric label="Atendidas" value={audit.pass} /><Metric label="Violações" value={audit.fail} /><Metric label="Não avaliáveis" value={audit.unknown} /><Metric label="Não aplicáveis" value={audit.notApplicable} /></div></Card></div>
    <div className="grid gap-4 xl:grid-cols-[1.35fr_1.2fr_.8fr]"><Card title="Planejada × Executada"><div className="mt-3 grid grid-cols-[1fr_1fr_auto] gap-y-2 text-sm"><span className="text-[var(--atlas-muted)]">Métrica</span><span className="text-[var(--atlas-muted)]">Planejada / Executada</span><span className="text-[var(--atlas-muted)]">Delta</span>{[["FT", planned?.official_month_flight_time_minutes, current?.official_month_flight_time_minutes],["DT",planned?.official_month_duty_time_minutes,current?.official_month_duty_time_minutes],["Folgas",planned?.official_off_days,current?.official_off_days]].map(([name,a,b])=><div key={String(name)} className="contents"><b>{String(name)}</b><span>{name === "Folgas" ? `${a ?? "—"} / ${b ?? "—"}` : `${duration(a as number | null)} / ${duration(b as number | null)}`}</span><span className="text-[var(--atlas-positive)]">{name === "Folgas" && typeof a === "number" && typeof b === "number" ? `${b-a>=0?"+":""}${b-a}` : delta(b as number | null,a as number | null)}</span></div>)}</div><p className="mt-4 text-sm text-[var(--atlas-muted)]">Planejada: baseline imutável · Executada: Snapshot {current?.snapshot_number ?? "—"}</p></Card><Card title={`Demonstrativo de folha — ${label}`} className="" ><div id="financeiro" className="mt-3 grid gap-2 text-sm"><div className="flex justify-between"><span>Bruto previsto</span><strong className="text-[var(--atlas-positive)]">{money(closure?.gross ?? null)}</strong></div><div className="flex justify-between"><span>Descontos</span><strong className="text-[var(--atlas-negative)]">{money(closure?.deductions ?? null)}</strong></div><div className="flex justify-between border-t border-[var(--atlas-border)] pt-3 text-base"><span>Líquido previsto</span><strong className="text-[var(--atlas-blue)]">{money(closure?.net ?? null)}</strong></div><Link href="/escala/configuracoes/remuneracao" className="mt-2 text-sm font-semibold text-[var(--atlas-blue)]">Configurar remuneração</Link></div></Card><div className="grid gap-4"><Card title="Diárias"><div className="mt-3 grid gap-2 text-sm">{cycles.slice(0,3).map(cycle=><div key={`${cycle.paymentDate}:${cycle.currency}`} className="flex justify-between rounded-lg bg-[var(--atlas-surface-solid)] px-3 py-2"><span>{cycle.paymentDate}</span><b>{money(cycle.amount,cycle.currency ?? "BRL")}</b></div>)}<Link href="/escala/diarias" className="mt-1 font-semibold text-[var(--atlas-blue)]">Ver diárias</Link></div></Card><Card title="Escala atual"><p className="mt-2 text-sm text-[var(--atlas-muted)]">Snapshot {current?.snapshot_number ?? "—"} · {current?.original_filename ?? "Sem execução"}</p><details className="mt-3 text-sm"><summary className="cursor-pointer font-medium">Histórico e ações</summary><div className="mt-3 flex gap-3"><Link href="/escala/diarias" className="text-[var(--atlas-blue)]">Ver executada</Link><Link href="/escala/regras" className="text-[var(--atlas-blue)]">Regras</Link></div></details></Card></div></div>
    <div id="agenda"><FlightMonthCalendar label={label} year={current?.document_period_start ? Number(current.document_period_start.slice(0,4)) : new Date().getFullYear()} month={current?.document_period_start ? Number(current.document_period_start.slice(5,7)) : new Date().getMonth()+1} days={days} legs={legs} /></div>
  </div>;
}
