import { AtlasText } from "@/components/ui/atlas-text";

export type LegalInstrumentOverview = { id: string; instrument_type: string; instrument_code: string; title: string; effective_from: string | null; effective_to: string | null; status: string; version: number; storage_path: string | null };
export type LegalRulesetOverview = { id: string; ruleset_code: string; name: string; effective_from: string; effective_to: string | null; status: string; version: number };
export type LegalRuleAuditOverview = { ruleKey: string; ruleVersion: number; lifecycle: string; effectiveFrom: string | null; effectiveTo: string | null; sourceCount: number };
export type FinancialProfileOverview = { id: string; effective_from: string; effective_to: string | null; role: string; seniority_percentage: string | number; source_type: string };
export type EconomicParameterOverview = { id: string; parameter_key: string; role: string | null; value_cents: number | null; value_numeric: string | number | null; value_unit: string; effective_from: string | null; lifecycle: string; derived: boolean; seniority_applicable: boolean };

function period(from: string | null, to: string | null) {
  if (!from) return "Ainda não informada";
  const format = new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" });
  return `${format.format(new Date(`${from}T00:00:00`))} — ${to ? format.format(new Date(`${to}T00:00:00`)) : "vigente"}`;
}

function parameterValue(parameter: EconomicParameterOverview) {
  if (parameter.value_cents !== null) return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(parameter.value_cents / 100);
  return parameter.value_numeric === null ? "Aguardando fonte" : `${parameter.value_numeric} ${parameter.value_unit}`;
}

export function LegalRulesOverview({ instruments, ruleSets, rules, financialProfiles, economicParameters }: { instruments: LegalInstrumentOverview[]; ruleSets: LegalRulesetOverview[]; rules: LegalRuleAuditOverview[]; financialProfiles: FinancialProfileOverview[]; economicParameters: EconomicParameterOverview[] }) {
  return <div className="grid gap-6">
    <section className="rounded-2xl border border-slate-700/80 bg-slate-900/80 p-6"><div className="mb-5 grid gap-1"><AtlasText variant="sectionTitle">Instrumentos jurídicos</AtlasText><AtlasText variant="secondary">Base versionada para consulta técnica. Alterações são feitas somente pelo backend autorizado.</AtlasText></div>{instruments.length === 0 ? <AtlasText variant="secondary">Nenhum instrumento jurídico cadastrado.</AtlasText> : <div className="grid gap-3">{instruments.map((instrument) => <article key={instrument.id} className="grid gap-2 border-t border-slate-700/80 pt-4 first:border-t-0 first:pt-0 sm:grid-cols-[1fr_auto]"><div><AtlasText variant="itemTitle">{instrument.title}</AtlasText><AtlasText variant="secondary">{instrument.instrument_type} · {instrument.instrument_code} · v{instrument.version}</AtlasText><AtlasText variant="caption">Vigência: {period(instrument.effective_from, instrument.effective_to)}</AtlasText>{instrument.storage_path ? <a className="atlas-link mt-2 inline-block" href={`/api/flight-legal-instruments/${instrument.id}/pdf`} target="_blank" rel="noreferrer">Visualizar documento</a> : null}</div><AtlasText variant="badge">{instrument.status}</AtlasText></article>)}</div>}</section>
    <section className="rounded-2xl border border-slate-700/80 bg-slate-900/80 p-6"><div className="mb-5 grid gap-1"><AtlasText variant="sectionTitle">Conjuntos de regras</AtlasText><AtlasText variant="secondary">Rulesets fixam versões para reprodutibilidade futura.</AtlasText></div>{ruleSets.length === 0 ? <AtlasText variant="secondary">Nenhum conjunto de regras cadastrado.</AtlasText> : <div className="grid gap-3">{ruleSets.map((ruleSet) => <article key={ruleSet.id} className="grid gap-2 border-t border-slate-700/80 pt-4 first:border-t-0 first:pt-0 sm:grid-cols-[1fr_auto]"><div><AtlasText variant="itemTitle">{ruleSet.name}</AtlasText><AtlasText variant="secondary">{ruleSet.ruleset_code} · v{ruleSet.version}</AtlasText><AtlasText variant="caption">Vigência: {period(ruleSet.effective_from, ruleSet.effective_to)}</AtlasText></div><AtlasText variant="badge">{ruleSet.status}</AtlasText></article>)}</div>}</section>
    <details className="rounded-2xl border border-slate-700/80 bg-slate-900/80 p-6"><summary className="cursor-pointer font-semibold">Catálogo técnico de regras ({rules.length})</summary><div className="mt-4 grid gap-2 text-sm text-[var(--atlas-text-muted)]">{rules.map((rule) => <div key={`${rule.ruleKey}-${rule.ruleVersion}`}><b className="text-[var(--atlas-text)]">{rule.ruleKey}</b> · v{rule.ruleVersion} · {rule.lifecycle} · fontes: {rule.sourceCount} · vigência: {period(rule.effectiveFrom, rule.effectiveTo)}</div>)}</div></details>
    <details className="rounded-2xl border border-slate-700/80 bg-slate-900/80 p-6"><summary className="cursor-pointer font-semibold">Catálogo financeiro ({economicParameters.length})</summary><div className="mt-4 grid gap-4 text-sm text-[var(--atlas-text-muted)]"><div>{financialProfiles.map((profile) => <div key={profile.id}><b className="text-[var(--atlas-text)]">Perfil {profile.role}</b> · antiguidade {profile.seniority_percentage}% · {period(profile.effective_from, profile.effective_to)} · {profile.source_type}</div>)}</div><div className="grid gap-2">{economicParameters.map((parameter) => <div key={parameter.id}><b className="text-[var(--atlas-text)]">{parameter.parameter_key}</b>{parameter.role ? ` (${parameter.role})` : ""} · {parameterValue(parameter)} · {parameter.lifecycle}{parameter.derived ? " · derivado" : ""}{parameter.seniority_applicable ? " · antiguidade aplicável" : ""} · {period(parameter.effective_from, null)}</div>)}</div><AtlasText variant="caption">Referência técnica versionada. Nenhum cálculo mensal foi executado.</AtlasText></div></details>
  </div>;
}
