import { AtlasText } from "@/components/ui/atlas-text";
import { requireFlightAccess } from "@/modules/flight/access";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const hours = (seconds: number | null) => seconds === null ? "—" : `${(seconds / 3600).toFixed(2).replace(".", ",")}h`;
const labels: Record<string, string> = { PAYROLL_NORMAL: "Horas de voo", PAYROLL_NIGHT_NORMAL: "Noturna normal", PAYROLL_SUNDAY_HOLIDAY_DAY: "Dom/fer diurno", PAYROLL_SUNDAY_HOLIDAY_NIGHT: "Dom/fer noturno", DSR_AERONAUTAS: "DSR aeronautas", VARIABLE_HAZARD: "Adic. periculosidade aeronautas", SALARY: "Salário", ORGANIC_COMPENSATION: "Compensação orgânica", FIXED_HAZARD_SALARY: "Adic. periculosidade", FIXED_HAZARD_ORGANIC: "Adic. per. s/ comp. org.", SENIORITY: "Gratificação senioridade", FAM_REIMBURSEMENT: "Reembolso FAM" };

export async function PayrollStatement() {
  const access = await requireFlightAccess(); const now = new Date();
  const schedule = await access.supabase.from("flight_schedule_months").select("current_execution_import_id").eq("user_id", access.user.id).eq("year", now.getFullYear()).eq("month", now.getMonth() + 1).maybeSingle(); const importId = schedule.data?.current_execution_import_id;
  if (!importId) return null;
  const [estimate, lines, buckets, cycles, tax] = await Promise.all([
    access.supabase.from("flight_payroll_final_estimates").select("id,guarantee_target_seconds,guarantee_eligible_operating_seconds,guarantee_eligible_deadhead_seconds,guarantee_eligible_standby_equivalent_seconds,guarantee_eligible_reserve_seconds,guarantee_eligible_total_seconds,guarantee_consumed_seconds,normal_within_guarantee_seconds,normal_above_guarantee_seconds,total_payroll_reference_seconds,gross_amount_minor_units,estimate_status,reconciliation_status").eq("import_id", importId).maybeSingle(),
    access.supabase.from("flight_payroll_final_lines").select("estimate_id,line_key,payroll_reference,exact_seconds,amount_minor_units,metadata").eq("user_id", access.user.id),
    access.supabase.from("flight_payroll_bucket_runs").select("bucket,source_activity,actual_seconds,payroll_reference").eq("import_id", importId),
    access.supabase.from("flight_diem_payment_cycles").select("payment_date,half_month,currency,known_minor_units,status").eq("import_id", importId).order("payment_date"),
    access.supabase.from("flight_payroll_tax_estimates").select("gross_amount_minor_units,inss_amount_minor_units,irrf_amount_minor_units,personal_deductions_minor_units,net_amount_minor_units,tax_status,provenance").eq("import_id", importId).maybeSingle(),
  ]);
  if (estimate.error || lines.error || buckets.error || cycles.error || tax.error || !estimate.data) return null;
  const payrollEstimate = estimate.data;
  const finalLines = (lines.data ?? []).filter(line => line.estimate_id === payrollEstimate.id); const variable = finalLines.filter(line => line.line_key.startsWith("PAYROLL_") || line.line_key === "DSR_AERONAUTAS" || line.line_key === "VARIABLE_HAZARD"); const fixed = finalLines.filter(line => !variable.includes(line));
  const sources = new Map<string, string[]>(); for (const row of buckets.data ?? []) { const list = sources.get(row.bucket) ?? []; list.push(`${row.source_activity === "STANDBY" ? "Sobreaviso eq." : row.source_activity} ${Number(row.payroll_reference).toFixed(2).replace(".", ",")}h`); sources.set(row.bucket, list); }
  const taxDetail = tax.data?.provenance as { irrf?: { legalDeductionsCents?: number; simplifiedCents?: number; method?: string; baseCents?: number; rateBasisPoints?: number; deductionCents?: number; monthlyReductionCents?: number }; personal?: Array<{ name: string; amountCents: number }> } | null;
  return <section className="grid gap-4 rounded-2xl border border-[var(--atlas-border)] bg-[var(--atlas-surface)] p-5"><div><AtlasText variant="sectionTitle">Demonstrativo · {String(now.getMonth() + 1).padStart(2, "0")}/{now.getFullYear()}</AtlasText><p className="mt-1 text-sm text-[var(--atlas-muted)]">Previsão salarial auditável.</p></div><div className="grid gap-2"><b className="text-sm">PROVENTOS</b>{[...fixed, ...variable].map(line => <details key={line.line_key} className="rounded-xl border border-[var(--atlas-border)] p-3"><summary className="cursor-pointer font-medium">{labels[line.line_key] ?? line.line_key} · {money(line.amount_minor_units)}</summary>{line.exact_seconds !== null ? <p className="mt-2 text-sm text-[var(--atlas-muted)]">Referência folha: {Number(line.payroll_reference).toFixed(2).replace(".", ",")}h · tempo exato: {hours(line.exact_seconds)}{sources.get(line.line_key.replace("PAYROLL_", "")) ? ` · ${sources.get(line.line_key.replace("PAYROLL_", ""))?.join(" · ")}` : ""}</p> : <p className="mt-2 text-sm text-[var(--atlas-muted)]">Componente confirmado de folha.</p>}</details>)}<b>Total de proventos: {money(payrollEstimate.gross_amount_minor_units)}</b></div>{tax.data ? <div className="grid gap-2"><b className="text-sm">DESCONTOS</b><p className="text-sm">INSS · base contributiva {money(tax.data.gross_amount_minor_units)} · -{money(tax.data.inss_amount_minor_units)}</p><p className="text-sm">IRRF · deduções legais {money(taxDetail?.irrf?.legalDeductionsCents ?? 0)} · simplificado {money(taxDetail?.irrf?.simplifiedCents ?? 0)} · {taxDetail?.irrf?.method} · base {money(taxDetail?.irrf?.baseCents ?? 0)} · -{money(tax.data.irrf_amount_minor_units)}</p>{(taxDetail?.personal ?? []).map(item => <p key={item.name} className="text-sm">{item.name} · -{money(item.amountCents)}</p>)}<b>Líquido salarial previsto: {money(tax.data.net_amount_minor_units)}</b></div> : null}<div className="grid gap-2"><b className="text-sm">DIÁRIAS E ADICIONAIS</b>{(cycles.data ?? []).map(cycle => <div key={`${cycle.payment_date}:${cycle.currency ?? "UNKNOWN"}`} className="text-sm"><b>{cycle.payment_date} · {cycle.half_month === "FIRST_HALF" ? "1ª quinzena" : "2ª quinzena"}</b><span className="ml-2">{cycle.currency === "BRL" ? money(cycle.known_minor_units) : "Moeda internacional pendente"} · {cycle.status}</span></div>)}</div></section>;
}
