export type TransactionType = "income" | "expense" | "transfer" | "reversal" | "refund" | "adjustment";
export type TransactionStatus = "forecast" | "pending" | "partial" | "realized" | "overdue" | "cancelled";
export interface FinancialAccount { id:string; name:string; institution_name:string|null; account_type:string; current_balance:number; opening_balance:number; source:string; status:string; visibility:string; last_sync_at:string|null }
export interface FinancialTransaction { id:string; description:string; amount:number; transaction_type:TransactionType; status:TransactionStatus; competence_date:string; due_date:string|null; realized_at:string|null; source:string; visibility:string; account_id:string|null; credit_card_id?:string|null; destination_account_id:string|null; category_id:string|null; workspace_id:string|null; review_status?:string; suspected_transfer?:boolean; financial_accounts?:{name:string}|null; credit_cards?:{name:string}|null; financial_categories?:{name:string}|null }
export interface CreditCard { id:string; name:string; institution_name:string|null; last_four_digits:string|null; brand:string|null; credit_limit:number; used_limit:number; current_balance:number; closing_day:number; due_day:number; status:string; visibility:string; linked_account_id:string|null; last_sync_at:string|null }
export interface FinancialInvestment { id:string;name:string;investment_type:string;institution_name:string|null;balance:number;currency:string;last_sync_at:string|null }
export interface FinancialLoan { id:string;name:string;institution_name:string|null;loan_type:string;subtype:string|null;contracted_amount:number|null;outstanding_balance:number|null;installment_amount:number|null;installment_count:number|null;installments_paid:number|null;installments_remaining:number|null;interest_rate:number|null;effective_cost_rate:number|null;contract_date:string|null;first_installment_date:string|null;next_installment_date:string|null;final_due_date:string|null;payroll_deducted:boolean|null;payment_source:string|null;currency:string;status:string|null;source:string;last_sync_at:string|null;provider_updated_at:string|null;notes:string|null }
export interface BankConnectionSummary { id:string;connector_name:string|null;sync_status:string;last_successful_sync_at:string|null;loans_sync_status:string;loans_sync_message:string|null;last_loans_sync_at:string|null }
export interface FinanceSummary { available:number; income:number; expenses:number; projected:number; receivable:number; payable:number; overdue:number; monthlyResult:number }
