export type TransactionType = "income" | "expense" | "transfer" | "reversal" | "refund" | "adjustment";
export type TransactionStatus = "forecast" | "pending" | "partial" | "realized" | "overdue" | "cancelled";
export interface FinancialAccount { id:string; bank_connection_id?:string|null; name:string; institution_name:string|null; account_type:string; current_balance:number; opening_balance:number; source:string; status:string; visibility:string; workspace_id?:string|null; last_sync_at:string|null }
export type TransactionRole="consumption"|"cash_flow"|"invoice_payment"|"transfer"|"refund"|"adjustment";
export interface FinancialTransaction { id:string; description:string; amount:number; original_amount?:number|null; transaction_type:TransactionType; transaction_role:TransactionRole; source_type:"bank"|"card"|"manual"|"automation"|"payroll"; financial_origin:"bank_account"|"credit_card"|"invoice"|"transfer"|"adjustment"; status:TransactionStatus|string; competence_date:string; due_date:string|null; realized_at:string|null; transaction_date?:string|null; posted_at?:string|null; provider_posted_at?:string|null; bank_posted_at?:string|null; effective_at?:string|null; user_effective_at?:string|null; date_source?:string|null; date_confidence?:string|null; date_override_reason?:string|null; created_at?:string|null; source:string; external_id?:string|null; visibility:string; account_id:string|null; credit_card_id?:string|null; invoice_id?:string|null; loan_id?:string|null; recurring_rule_id?:string|null; payment_source?:string|null; cash_flow_kind?:string|null; bank_direction?:"inflow"|"outflow"|"neutral"|"review"|null; financial_nature?:string|null; financial_role?:string|null; provider_type?:string|null; operation_type?:string|null; operation_type_additional_info?:string|null; classification_source?:string|null; classification_confidence?:string|null; classification_rule?:string|null; classification_version?:string|null; manually_confirmed?:boolean; manual_override_at?:string|null; manual_override_by?:string|null; transfer_group_id?:string|null; destination_account_id:string|null; category_id:string|null; workspace_id:string|null; review_status?:string; suspected_transfer?:boolean; financial_accounts?:{name:string;institution_name:string|null}|null; credit_cards?:{name:string;last_four_digits:string|null}|null; financial_categories?:{name:string}|null }
export interface CreditCardInstrument {id:string;credit_card_id:string;external_id:string;last_four_digits:string|null;card_kind:"physical"|"virtual"|"online"|"additional"|"unknown";display_name:string;provider_status:string;user_archived_at:string|null;source:string}
export interface CardInvoiceConfirmation {id:string;card_id:string;reference_month:string;official_amount:number;source:"manual_bank_confirmation";informed_at:string;note:string|null}
export interface StoredCardInvoice {id:string;card_id:string;reference_month:string;cycle_start_date:string|null;cycle_end_date:string|null;closing_date:string;due_date:string;total_amount:number;paid_amount:number;paid_at:string|null;outstanding_amount:number;purchase_count:number;status:"open"|"closed"|"due"|"partially_paid"|"paid"|"overdue"|"cancelled"|"estimated";external_id:string|null;provider_invoice_total:number|null;calculated_invoice_total:number|null;manual_invoice_total:number|null;confirmed_invoice_total?:number|null;minimum_payment_amount?:number|null;provider_bill_status?:string|null;total_source:string|null;reconciliation_difference?:number|null;reconciliation_status:string|null;provider_updated_at:string|null;invoice_breakdown?:Record<string,number>|null}
export interface CreditCard { id:string;bank_connection_id?:string|null;workspace_id?:string|null;name:string;institution_name:string|null;last_four_digits:string|null;brand:string|null;credit_limit:number;used_limit:number;current_balance:number;provider_status?:string|null;provider_invoice_total?:number|null;account_credit_balance?:number|null;provider_bill_id?:string|null;provider_bill_closing_date?:string|null;provider_bill_due_date?:string|null;provider_cycle_start_date?:string|null;dates_source?:string|null;closing_day:number|null;due_day:number|null;status:string;user_archived_at?:string|null;visibility:string;linked_account_id:string|null;last_sync_at:string|null;source?:string;bank_connections?:{last_complete_sync_at:string|null;data_completeness:string;provider_status:string}|null;credit_card_instruments?:CreditCardInstrument[];card_invoice_confirmations?:CardInvoiceConfirmation[] }
export interface CardPurchase { id:string;card_id:string;external_id?:string|null;workspace_id?:string|null;instrument_id?:string|null;instrument_review_status?:string;invoice_id:string|null;provider_bill_id?:string|null;description:string;total_amount:number;total_purchase_amount?:number|null;installment_amount:number;purchase_date:string;competence_date?:string|null;realized_at?:string|null;created_at?:string|null;is_installment?:boolean;installment_number:number|null;installment_count:number|null;installment_source?:"provider_structured"|"provider_description"|"manual"|"unknown";installment_confidence?:"confirmed"|"inferred"|"manual"|"unknown";installment_plan_id?:string|null;installment_manually_confirmed?:boolean;source:string;source_type:string;financial_origin:string;transaction_role:TransactionRole;status:string;review_status:string;invoice_reference:string|null;bill_forecast_date:string|null;due_date?:string|null;provider_category:string|null;merchant:string|null;visibility:string;category_id:string|null;original_amount?:number|null;credit_cards?:{name:string;institution_name:string|null;last_four_digits:string|null}|null;credit_card_instruments?:{last_four_digits:string|null;card_kind:string;display_name:string}|null;financial_categories?:{name:string}|null }
export interface FinancialInvestment { id:string;name:string;investment_type:string;institution_name:string|null;balance:number;currency:string;last_sync_at:string|null }
export interface FinancialLoan { id:string;name:string;institution_name:string|null;loan_type:string;subtype:string|null;contracted_amount:number|null;outstanding_balance:number|null;installment_amount:number|null;installment_count:number|null;installments_paid:number|null;installments_remaining:number|null;interest_rate:number|null;effective_cost_rate:number|null;contract_date:string|null;first_installment_date:string|null;next_installment_date:string|null;final_due_date:string|null;payroll_deducted:boolean|null;payment_source:string|null;currency:string;status:string|null;source:string;last_sync_at:string|null;provider_updated_at:string|null;notes:string|null }
export interface BankConnectionSummary { id:string;connector_name:string|null;sync_status:string;last_successful_sync_at:string|null;last_complete_sync_at?:string|null;last_sync_at?:string|null;provider_status?:string;data_completeness?:string;incident_message?:string|null;stale_since?:string|null;partial_data_count?:number;loans_sync_status:string;loans_sync_message:string|null;last_loans_sync_at:string|null }
export interface FinanceSummary { monthStart:string; monthEndExclusive:string; available:number; income:number; expenses:number; projected:number; receivable:number; payable:number; overdue:number; monthlyResult:number }
