export type TransactionType = "income" | "expense" | "transfer" | "reversal" | "refund" | "adjustment";
export type TransactionStatus = "forecast" | "pending" | "partial" | "realized" | "overdue" | "cancelled";
export interface FinancialAccount { id:string; name:string; institution_name:string|null; account_type:string; current_balance:number; opening_balance:number; source:string; status:string; visibility:string; last_sync_at:string|null }
export interface FinancialTransaction { id:string; description:string; amount:number; transaction_type:TransactionType; status:TransactionStatus; competence_date:string; due_date:string|null; realized_at:string|null; source:string; visibility:string; account_id:string|null; credit_card_id?:string|null; destination_account_id:string|null; category_id:string|null; workspace_id:string|null; review_status?:string; suspected_transfer?:boolean; financial_accounts?:{name:string}|null; credit_cards?:{name:string}|null; financial_categories?:{name:string}|null }
export interface CreditCard { id:string; name:string; institution_name:string|null; last_four_digits:string|null; brand:string|null; credit_limit:number; used_limit:number; current_balance:number; closing_day:number; due_day:number; status:string; visibility:string; linked_account_id:string|null; last_sync_at:string|null }
export interface FinancialInvestment { id:string;name:string;investment_type:string;institution_name:string|null;balance:number;currency:string;last_sync_at:string|null }
export interface FinancialLoan { id:string;name:string;loan_type:string;balance_due:number;original_amount:number;currency:string;end_date:string|null;last_sync_at:string|null }
export interface BankConnectionSummary { id:string;connector_name:string|null;sync_status:string;last_successful_sync_at:string|null }
export interface FinanceSummary { available:number; income:number; expenses:number; projected:number; receivable:number; payable:number; overdue:number; monthlyResult:number }
