"use client";

import { useActionState } from "react";
import { fullSyncItemAction, linkItemAction, syncItemAction, testCredentialsAction, unlinkItemAction, type IntegrationActionState } from "@/app/financeiro/integracoes/actions";

type Connection={id:string;connector_name:string|null;status:string;sync_status:string;last_provider_update_at:string|null;last_successful_sync_at:string|null;connection_error_message:string|null;maskedItem:string};
type SyncRun={id:string;bank_connection_id:string;status:string;started_at:string;accounts_count:number;cards_count:number;transactions_count:number;investments_count:number;loans_count:number};
const initial:IntegrationActionState={status:"idle",message:""};
function Feedback({state}:{state:IntegrationActionState}){return state.message?<p className={`integration-feedback ${state.status}`} role="status">{state.message}</p>:null}
function ActionForm({action,id,label,danger=false,confirmMessage}:{action:typeof syncItemAction;id:string;label:string;danger?:boolean;confirmMessage?:string}){const [state,formAction,pending]=useActionState(action,initial);return <form action={formAction} onSubmit={event=>{if(confirmMessage&&!window.confirm(confirmMessage))event.preventDefault()}}><input type="hidden" name="connection_id" value={id}/><button className={danger?"integration-action danger":"integration-action"} disabled={pending}>{pending?"Processando…":label}</button><Feedback state={state}/></form>}

export function PluggyIntegrationPanel({configured,connections,runs}:{configured:boolean;connections:Connection[];runs:SyncRun[]}){
 const [testState,testAction,testPending]=useActionState(testCredentialsAction,initial);const [linkState,linkAction,linkPending]=useActionState(linkItemAction,initial);
 return <div className="integration-grid">
  <section className="finance-panel integration-overview"><header><div><p className="eyebrow">Open Finance</p><h2>Pluggy</h2></div><span className={`status ${configured?"success":"danger"}`}>{configured?"Configurada":"Não configurada"}</span></header><p>Importe contas, cartões, movimentações, investimentos e empréstimos sem armazenar senhas bancárias no Atlas.</p><form action={testAction}><button className="finance-button" disabled={!configured||testPending}>{testPending?"Testando…":"Testar credenciais"}</button><Feedback state={testState}/></form></section>
  <section className="finance-panel"><header><div><p className="eyebrow">Vincular conexão</p><h2>Item da Pluggy</h2></div></header><p>A Pluggy não oferece uma API para listar Items existentes. Copie o Item ID do painel da Pluggy; o Atlas o valida antes de vincular.</p><form action={linkAction} className="integration-link-form"><label>Item ID<input name="item_id" autoComplete="off" required maxLength={180} placeholder="ID exibido no painel Pluggy"/></label><button className="finance-button" disabled={!configured||linkPending}>{linkPending?"Validando e sincronizando…":"Validar e vincular"}</button><Feedback state={linkState}/></form></section>
  <section className="finance-panel integration-connections"><header><h2>Conexões</h2><span>{connections.length}</span></header>{connections.length?<div className="integration-list">{connections.map(connection=>{const last=runs.find(run=>run.bank_connection_id===connection.id);return <article key={connection.id}><div><b>{connection.connector_name||"Instituição conectada"}</b><small>Item {connection.maskedItem} · {connection.sync_status}</small>{connection.last_provider_update_at?<small>Provedor atualizado: {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(connection.last_provider_update_at))}</small>:null}{connection.last_successful_sync_at?<small>Último sucesso no Atlas: {new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(connection.last_successful_sync_at))}</small>:null}{last?<small>{last.accounts_count} contas · {last.cards_count} cartões · {last.transactions_count} movimentações · {last.investments_count} investimentos · {last.loans_count} empréstimos</small>:null}{connection.connection_error_message?<p className="integration-error">{connection.connection_error_message}</p>:null}</div><div className="integration-actions"><ActionForm action={syncItemAction} id={connection.id} label="Sincronizar agora"/><ActionForm action={fullSyncItemAction} id={connection.id} label="Ressincronizar tudo" confirmMessage="Refazer a sincronização completa? O processo é idempotente e não apaga personalizações."/><ActionForm action={unlinkItemAction} id={connection.id} label="Desvincular" danger confirmMessage="Desvincular este Item? Novas sincronizações serão bloqueadas, mas os dados já importados serão preservados."/></div></article>})}</div>:<p className="integration-empty">Nenhuma conexão ativa.</p>}</section>
  {runs.length?<section className="finance-panel integration-connections"><header><h2>Histórico de sincronização</h2><span>{runs.length}</span></header><div className="finance-list">{runs.slice(0,10).map(run=><div key={run.id}><span><b>{run.status}</b><small>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(run.started_at))}</small></span><strong>{run.transactions_count} movimentações</strong></div>)}</div></section>:null}
 </div>
}
