import { createClient } from "@supabase/supabase-js";
import { resolveEconomicParameter, type EconomicParameterForResolution } from "./financial-economic-resolution";
import { closureId, materializeClosureLines, summarizeClosure, FLIGHT_FINANCIAL_CLOSURE_VERSION, type ClosureLineInput, type ClosureLineType } from "./financial-closure";

type DecisionRow = { id: string; financial_component: string; planned_quantity: number; executed_quantity: number; decision: string; reason: string | null; confidence: "HIGH" | "MEDIUM" | "LOW" };
type EntitlementRow = { entitlement_type: string; eligibility_status: string; amount_minor_units: number | null; currency: string | null; source_instrument_id: string | null; source_clause: string | null };
type ProfileRow = { role: string; seniority_percentage: number | string; contractual_base: string | null; effective_from: string; effective_to: string | null };

const mapComponent: Record<string, ClosureLineType> = { NORMAL_OPERATING: "NORMAL_VARIABLE", DEADHEAD: "DEADHEAD", STANDBY_EQUIVALENT: "STANDBY", RESERVE: "RESERVE", NIGHT: "NIGHT", SUNDAY: "SUNDAY", HOLIDAY: "HOLIDAY" };
const sourceImport = (decision: string): ClosureLineInput["sourceImport"] => decision === "PLANNED" ? "PLANNED" : decision === "EXECUTED" ? "EXECUTED" : decision === "ADDITIVE" ? "ADDITIVE" : decision === "NO_DIFFERENCE" ? "NONE" : "MIXED";
const blockerForDecision = (reason: string | null) => reason === "VOLUNTARY_STATUS_UNKNOWN" ? "WAITING_VOLUNTARY_FACT" : reason === "GUARANTEE_SCOPE_NOT_DOCUMENTED" ? "WAITING_GUARANTEE_SCOPE" : reason ?? "OTHER";

export async function buildFlightFinancialMonthlyClosure(executedImportId: string, ownerUserId?: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("As credenciais de servidor do Supabase não foram configuradas.");
  const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  const executedResult = await supabase.from("flight_schedule_imports").select("id,user_id,document_period_start,schedule_month_id,schedule_role").eq("id", executedImportId).maybeSingle();
  if (executedResult.error || !executedResult.data || (ownerUserId && executedResult.data.user_id !== ownerUserId)) throw new Error("Importação executada não encontrada.");
  const executed = executedResult.data; const period = executed.document_period_start ?? ""; const [year, month] = period.split("-").map(Number); if (!year || !month) throw new Error("Período documental da escala indisponível.");
  const [plannedResult, decisionsResult, entitlementsResult, profilesResult, parametersResult] = await Promise.all([
    supabase.from("flight_schedule_imports").select("id").eq("schedule_month_id", executed.schedule_month_id).eq("schedule_role", "PLANNED").maybeSingle(),
    supabase.from("flight_financial_guarantee_decisions").select("id,financial_component,planned_quantity,executed_quantity,decision,reason,confidence").eq("executed_import_id", executed.id),
    supabase.from("flight_financial_entitlements").select("entitlement_type,eligibility_status,amount_minor_units,currency,source_instrument_id,source_clause").eq("import_id", executed.id),
    supabase.from("flight_compensation_profiles").select("role,seniority_percentage,contractual_base,effective_from,effective_to").eq("user_id", executed.user_id).order("effective_from", { ascending: false }),
    supabase.from("flight_economic_parameters").select("id,parameter_key,role,value_cents,effective_from,effective_to,lifecycle,seniority_applicable,source_instrument_id,source_clause_reference").in("parameter_key", ["SALARY_FLOOR", "FLIGHT_HOUR_TOTAL"]),
  ]);
  if (plannedResult.error || !plannedResult.data || decisionsResult.error || entitlementsResult.error || profilesResult.error || parametersResult.error) throw new Error(plannedResult.error?.message ?? decisionsResult.error?.message ?? entitlementsResult.error?.message ?? profilesResult.error?.message ?? parametersResult.error?.message ?? "Não foi possível carregar o fechamento financeiro.");
  const profile = ((profilesResult.data ?? []) as ProfileRow[]).find(item => item.effective_from <= period && (item.effective_to === null || item.effective_to >= period)) ?? null;
  const parameters = (parametersResult.data ?? []) as EconomicParameterForResolution[];
  const floor = resolveEconomicParameter(parameters, "SALARY_FLOOR", profile?.role ?? null, period);
  const hourly = resolveEconomicParameter(parameters, "FLIGHT_HOUR_TOTAL", profile?.role ?? null, period);
  const decisions = decisionsResult.data as DecisionRow[]; const entitlements = entitlementsResult.data as EntitlementRow[];
  const inputs: ClosureLineInput[] = [
    { componentType: "SALARY_FLOOR", sourceImport: "NONE", quantity: 1, quantityUnit: "MONTH", rateMinorUnits: floor.applicable ? floor.parameter?.value_cents ?? null : null, calculationStatus: floor.applicable ? "CALCULATED" : "UNKNOWN", reason: floor.applicable ? null : floor.blocker, currency: "BRL", parameterId: floor.parameter?.id ?? null, sourceInstrumentId: floor.parameter?.source_instrument_id ?? null, sourceClause: floor.parameter?.source_clause_reference ?? null, confidence: floor.applicable ? "HIGH" : "LOW" },
    { componentType: "SENIORITY", sourceImport: "NONE", quantity: floor.applicable && floor.parameter?.seniority_applicable ? floor.parameter.value_cents ?? 0 : 0, quantityUnit: "CENT", rateMinorUnits: floor.applicable && profile && floor.parameter?.seniority_applicable ? 1 : null, multiplierNumerator: profile ? Math.round(Number(profile.seniority_percentage) * 100) : 0, multiplierDenominator: 10000, calculationStatus: floor.applicable && profile && floor.parameter?.seniority_applicable ? "CALCULATED" : "UNKNOWN", reason: floor.applicable && profile && floor.parameter?.seniority_applicable ? null : floor.applicable ? "SENIORITY_NOT_APPLICABLE_TO_FLOOR" : floor.blocker, currency: "BRL", parameterId: floor.parameter?.id ?? null, sourceInstrumentId: floor.parameter?.source_instrument_id ?? null, sourceClause: floor.parameter?.source_clause_reference ?? null, confidence: floor.applicable && profile ? "HIGH" : "LOW" },
  ];
  for (const decision of decisions.filter(item => item.financial_component in mapComponent)) {
    const type = mapComponent[decision.financial_component]; const selected = decision.decision === "PLANNED" ? decision.planned_quantity : decision.executed_quantity; const noDifferenceZero = decision.decision === "NO_DIFFERENCE" && selected === 0; const denominator = type === "STANDBY" ? 10800 : type === "NIGHT" ? 25200 : 3600; const supported = ["EXECUTED", "PLANNED", "ADDITIVE", "NO_DIFFERENCE"].includes(decision.decision);
    inputs.push({ componentType: type, sourceImport: sourceImport(decision.decision), quantity: selected, quantityUnit: type === "STANDBY" ? "SECONDS_NUMERATOR_OVER_3" : type === "NIGHT" ? "SECONDS_NUMERATOR_OVER_7" : "SECONDS", rateMinorUnits: noDifferenceZero ? 0 : hourly.applicable ? hourly.parameter?.value_cents ?? null : null, multiplierDenominator: denominator, calculationStatus: noDifferenceZero ? "CALCULATED" : supported && hourly.applicable ? "CALCULATED" : "UNKNOWN", reason: noDifferenceZero ? null : !supported ? blockerForDecision(decision.reason) : hourly.blocker, currency: "BRL", parameterId: hourly.parameter?.id ?? null, sourceInstrumentId: hourly.parameter?.source_instrument_id ?? null, sourceClause: hourly.parameter?.source_clause_reference ?? null, decisionStatus: decision.decision, confidence: noDifferenceZero ? "HIGH" : supported && hourly.applicable ? decision.confidence : "LOW" });
  }
  const entitlementGroups: Array<[ClosureLineType, string]> = [["DOMESTIC_BREAKFAST", "DOMESTIC_BREAKFAST"], ["DOMESTIC_LUNCH", "DOMESTIC_LUNCH"], ["DOMESTIC_DINNER", "DOMESTIC_DINNER"], ["DOMESTIC_SUPPER", "DOMESTIC_SUPPER"], ["MADRUGADA_TRANSPORT", "MADRUGADA_TRANSPORT_REIMBURSEMENT"]];
  for (const [componentType, entitlementType] of entitlementGroups) {
    const rows = entitlements.filter(item => item.entitlement_type === entitlementType && item.eligibility_status === "ELIGIBLE" && item.currency === "BRL" && item.amount_minor_units !== null); const amount = rows.reduce((sum, row) => sum + row.amount_minor_units!, 0); const rate = rows.length === 0 ? 0 : amount % rows.length === 0 ? amount / rows.length : null; const source = rows[0] ?? null;
    inputs.push({ componentType, sourceImport: "EXECUTED", quantity: rows.length, quantityUnit: "ENTITLEMENT", rateMinorUnits: rate, calculationStatus: rate === null ? "UNKNOWN" : "CALCULATED", reason: rate === null ? "OTHER" : null, currency: "BRL", parameterId: null, sourceInstrumentId: source?.source_instrument_id ?? null, sourceClause: source?.source_clause ?? null, confidence: rate === null ? "LOW" : "HIGH" });
  }
  const foreign = entitlements.filter(item => item.entitlement_type.startsWith("INTERNATIONAL_") && item.eligibility_status === "ELIGIBLE");
  inputs.push({ componentType: "INTERNATIONAL_DIEMS", sourceImport: "EXECUTED", quantity: foreign.length, quantityUnit: "ENTITLEMENT", rateMinorUnits: null, calculationStatus: foreign.length ? "UNKNOWN" : "NOT_APPLICABLE", reason: foreign.length ? "WAITING_INTERNATIONAL_RATE" : null, currency: null, parameterId: null, sourceInstrumentId: foreign[0]?.source_instrument_id ?? null, sourceClause: foreign[0]?.source_clause ?? null, confidence: foreign.length ? "LOW" : "HIGH" });
  const closure = closureId(executed.user_id, year, month, executed.id); const lines = materializeClosureLines(closure, inputs); const summary = summarizeClosure(lines);
  const removedLines = await supabase.from("flight_financial_monthly_lines").delete().eq("closure_id", closure); if (removedLines.error) throw new Error(removedLines.error.message);
  const persisted = await supabase.from("flight_financial_monthly_closures").upsert({ id: closure, user_id: executed.user_id, year, month, planned_import_id: plannedResult.data.id, executed_import_id: executed.id, known_total_brl: summary.knownTotalBrl, final_total_brl: summary.finalTotalBrl, final_total_status: summary.finalTotalStatus, engine_version: FLIGHT_FINANCIAL_CLOSURE_VERSION, provenance: { role: profile?.role ?? "UNKNOWN", seniorityPercentage: profile?.seniority_percentage ?? null, contractualBase: profile?.contractual_base ?? null } }); if (persisted.error) throw new Error(persisted.error.message);
  const inserted = await supabase.from("flight_financial_monthly_lines").insert(lines.map(line => { const decision = decisions.find(item => mapComponent[item.financial_component] === line.componentType); return { id: line.id, closure_id: closure, user_id: executed.user_id, component_type: line.componentType, source_import: line.sourceImport, quantity: line.quantity, quantity_unit: line.quantityUnit, rate_minor_units: line.rateMinorUnits, currency: line.currency, multiplier_numerator: line.multiplierNumerator, multiplier_denominator: line.multiplierDenominator, amount_minor_units: line.amountMinorUnits, calculation_status: line.calculationStatus, decision_id: decision?.id ?? null, economic_parameter_id: line.parameterId, source_instrument_id: line.sourceInstrumentId ?? null, source_clause: line.sourceClause ?? null, reason: line.reason, confidence: line.confidence, provenance: line.provenance }; })); if (inserted.error) throw new Error(inserted.error.message);
  return { closureId: closure, plannedImportId: plannedResult.data.id, executedImportId: executed.id, profile, summary, lines };
}
