import { createHash } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { buildFinalPayrollReferences, buildPayrollBuckets, calculateGrossPayrollEstimate, payrollDecimalReference, type SourceActivity } from "./financial-payroll";

const stableId = (value: string) => { const hash = createHash("sha256").update(`flight-payroll-final/1.0.0:${value}`).digest("hex"); return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-5${hash.slice(13, 16)}-${(Number.parseInt(hash.slice(16, 18), 16) & 0x3f | 0x80).toString(16)}${hash.slice(18, 20)}-${hash.slice(20, 32)}`; };
const keys = ["PAYROLL_NORMAL", "PAYROLL_NIGHT_NORMAL", "PAYROLL_SUNDAY_HOLIDAY_DAY", "PAYROLL_SUNDAY_HOLIDAY_NIGHT"] as const;

export async function buildFlightFinalPayrollEstimate(importId: string, ownerUserId?: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("Credenciais de servidor indisponíveis.");
  const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  const source = await supabase.from("flight_schedule_imports").select("id,user_id").eq("id", importId).maybeSingle();
  if (source.error || !source.data || (ownerUserId && source.data.user_id !== ownerUserId)) throw new Error("Importação não encontrada.");
  const imported = source.data;
  const result = await supabase.from("flight_financial_segments").select("activity_type,duration_seconds,is_night,is_sunday,holiday_status,night_equivalent_numerator_seconds,night_equivalent_denominator").eq("import_id", importId);
  if (result.error) throw new Error(result.error.message);
  const segments = (result.data ?? []).map(row => ({ sourceActivity: row.activity_type as SourceActivity, durationSeconds: row.duration_seconds, isNight: row.is_night, isSunday: row.is_sunday, isHoliday: row.holiday_status === "TRUE", nightEquivalentNumeratorSeconds: row.night_equivalent_numerator_seconds, nightEquivalentDenominator: row.night_equivalent_denominator, equivalenceNumeratorSeconds: row.activity_type === "STANDBY" ? row.duration_seconds : undefined, equivalenceDenominator: row.activity_type === "STANDBY" ? 3 : undefined }));
  const buckets = buildPayrollBuckets(segments); const references = buildFinalPayrollReferences(buckets); const amounts = calculateGrossPayrollEstimate(references); const estimateId = stableId(importId);
  const refs = [references.payrollNormalSeconds, references.payrollNightNormalSeconds, references.payrollSundayHolidayDaySeconds, references.payrollSundayHolidayNightSeconds];
  const lines = [...keys.map((lineKey, index) => ({ lineKey, exactSeconds: refs[index], reference: payrollDecimalReference(refs[index]), amount: amounts.variableAmounts[index], metadata: { rateCents: 8947 } })), { lineKey: "DSR_AERONAUTAS", exactSeconds: references.totalPayrollReferenceSeconds, reference: payrollDecimalReference(references.totalPayrollReferenceSeconds), amount: amounts.dsrAmountCents, metadata: { rateCents: 3253 } }, { lineKey: "VARIABLE_HAZARD", exactSeconds: references.totalPayrollReferenceSeconds, reference: payrollDecimalReference(references.totalPayrollReferenceSeconds), amount: amounts.variableHazardAmountCents, metadata: { rateCents: 3660 } }, { lineKey: "SALARY", exactSeconds: null, reference: null, amount: 752160, metadata: {} }, { lineKey: "ORGANIC_COMPENSATION", exactSeconds: null, reference: null, amount: 150432, metadata: {} }, { lineKey: "FIXED_HAZARD_SALARY", exactSeconds: null, reference: null, amount: 225648, metadata: {} }, { lineKey: "FIXED_HAZARD_ORGANIC", exactSeconds: null, reference: null, amount: 45130, metadata: {} }, { lineKey: "SENIORITY", exactSeconds: null, reference: null, amount: 63181, metadata: { percentage: 7 } }, { lineKey: "FAM_REIMBURSEMENT", exactSeconds: null, reference: null, amount: 10000, metadata: { nature: "INDEMNITY" } }];
  const upsert = await supabase.from("flight_payroll_final_estimates").upsert({ id: estimateId, user_id: imported.user_id, import_id: importId, guarantee_target_seconds: references.guaranteeTargetSeconds, guarantee_eligible_total_seconds: references.guaranteeEligibleTotalSeconds, guarantee_eligible_operating_seconds: references.guaranteeEligibleOperatingSeconds, guarantee_eligible_deadhead_seconds: references.guaranteeEligibleDeadheadSeconds, guarantee_eligible_standby_equivalent_seconds: references.guaranteeEligibleStandbyEquivalentSeconds, guarantee_eligible_reserve_seconds: references.guaranteeEligibleReserveSeconds, guarantee_consumed_seconds: references.guaranteeConsumedSeconds, normal_within_guarantee_seconds: references.normalWithinGuaranteeSeconds, normal_above_guarantee_seconds: references.normalAboveGuaranteeSeconds, total_payroll_reference_seconds: references.totalPayrollReferenceSeconds, gross_amount_minor_units: amounts.grossAmountCents, estimate_status: "NEAR_MATCH_ESTIMATE", reconciliation_status: "REVIEW_REQUIRED", provenance: { engine: "flight-payroll-final/1.0.0", guaranteeCompositionStatus: "PAYROLL_OBSERVED_EFFECTIVE", payrollObservedEffective: true, observedPayrollDate: "2026-08-06", legalEffectiveDate: "UNKNOWN", juneReconciliationStatus: "WAITING_IMPORTS", externalReference: { normal: 26.2, night: 39.8, sundayDay: 3.7, sundayNight: 2.2, total: 71.9, grossCents: 2387590 } } });
  if (upsert.error) throw new Error(upsert.error.message);
  const deleted = await supabase.from("flight_payroll_final_lines").delete().eq("estimate_id", estimateId); if (deleted.error) throw new Error(deleted.error.message);
  const inserted = await supabase.from("flight_payroll_final_lines").insert(lines.map(line => ({ id: stableId(`${importId}:${line.lineKey}`), estimate_id: estimateId, user_id: imported.user_id, line_key: line.lineKey, payroll_reference: line.reference, exact_seconds: line.exactSeconds, amount_minor_units: line.amount, metadata: line.metadata })));
  if (inserted.error) throw new Error(inserted.error.message);
  return { estimateId, references, amounts, lines };
}
