import { createClient } from "@supabase/supabase-js";
import { flightAirports, localAtUtc } from "@/modules/flight/time-metrics";
import { deriveFinancialEntitlements, FLIGHT_FINANCIAL_ENTITLEMENTS_VERSION, summarizeFinancialEntitlements, type DiemTimelineActivity, type HotelInterval, type TimelineActivityKind, type TransportDuty } from "./financial-entitlements";
import { persistFlightDiemReconciliation } from "./financial-diem-reconciliation-service";
import { deriveFlightTripFacts } from "./flight-trip-facts";
import { deriveFlightDiemPaymentCycles } from "./financial-payroll-service";

const airports = new Map(flightAirports.map(airport => [airport.iata, airport]));
const at = (date: string, time: string | null, airport: string | null) => { const timezone = airport ? airports.get(airport)?.timezone : null; return time && timezone ? localAtUtc(date, time, timezone) : null; };
const eventKind: Record<string, TimelineActivityKind | null> = { STANDBY: "STANDBY", COURSE: "COURSE", TRAINING: "TRAINING", EVALUATION: "EVALUATION", DEADHEAD: "DEADHEAD", GROUND_ACTIVITY: "GROUND_ACTIVITY", OFF: null, CHECK_IN: null, CHECK_OUT: null, UNKNOWN: null };
const documentedAirport = (rawText: string, parsed: string | null) => parsed && airports.has(parsed) ? parsed : rawText.split(/\s+/).map(token => token.replace(/[^A-Z]/g, "")).find(token => airports.has(token)) ?? null;

export async function buildFlightFinancialEntitlements(importId: string, ownerUserId?: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("As credenciais de servidor do Supabase não foram configuradas.");
  const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  const sourceResult = await supabase.from("flight_schedule_imports").select("id,user_id,document_period_start,document_period_end").eq("id", importId).maybeSingle();
  if (sourceResult.error || !sourceResult.data || (ownerUserId && sourceResult.data.user_id !== ownerUserId)) throw new Error("Importação de escala não encontrada.");
  const source = sourceResult.data; const period = source.document_period_start ?? "";
  const [dutiesResult, legsResult, eventsResult, daysResult, profilesResult, parametersResult] = await Promise.all([
    supabase.from("flight_duties").select("id,sequence,start_date,end_date,check_in_airport,check_out_airport,check_in_time_local,check_out_time_local").eq("import_id", importId).order("sequence"),
    supabase.from("flight_legs").select("id,duty_id,sequence,leg_type,origin,destination,departure_at_utc,arrival_at_utc,raw_text").eq("import_id", importId).order("sequence"),
    supabase.from("flight_schedule_events").select("id,schedule_day_id,event_type,event_code,start_time_local,end_time_local,location_airport,raw_text").eq("import_id", importId).order("sequence"),
    supabase.from("flight_schedule_days").select("id,schedule_date").eq("import_id", importId).order("schedule_date"),
    supabase.from("flight_compensation_profiles").select("id,contractual_base,effective_from,effective_to,source_reference").eq("user_id", source.user_id).order("effective_from", { ascending: false }),
    supabase.from("flight_economic_parameters").select("id,parameter_key,value_cents,value_numeric,currency,effective_from,effective_to,lifecycle,source_instrument_id,source_clause_reference").in("parameter_key", ["MEAL_MAIN_DIEM", "BREAKFAST_DIEM_PERCENT", "MADRUGADA_TRANSPORT"]),
  ]);
  if (dutiesResult.error || legsResult.error || eventsResult.error || daysResult.error || profilesResult.error || parametersResult.error) throw new Error(dutiesResult.error?.message ?? legsResult.error?.message ?? eventsResult.error?.message ?? daysResult.error?.message ?? profilesResult.error?.message ?? parametersResult.error?.message ?? "Não foi possível carregar dados para as diárias.");
  const profile = (profilesResult.data ?? []).find(item => item.effective_from <= period && (item.effective_to === null || item.effective_to >= period)) ?? null;
  const policiesResult = profile ? await supabase.from("flight_compensation_profile_policies").select("policy_key,metadata").eq("profile_id", profile.id).in("policy_key", ["HOTEL_USAGE_POLICY", "BREAKFAST_POLICY"]) : { data: [], error: null };
  if (policiesResult.error) throw new Error(policiesResult.error.message);
  const parameter = (parameterKey: string) => (parametersResult.data ?? []).filter(item => item.parameter_key === parameterKey && (item.effective_from === null || item.effective_from <= period) && (item.effective_to === null || item.effective_to >= period)).sort((left, right) => String(right.effective_from).localeCompare(String(left.effective_from)))[0] ?? null;
  const meal = parameter("MEAL_MAIN_DIEM"); const breakfast = parameter("BREAKFAST_DIEM_PERCENT"); const transport = parameter("MADRUGADA_TRANSPORT");
  const policy = (policyKey: string) => (policiesResult.data ?? []).find(item => item.policy_key === policyKey) ?? null;
  const hotelMetadata = policy("HOTEL_USAGE_POLICY")?.metadata as { waivedLocations?: unknown; defaultHotelUsed?: unknown } | null; const breakfastMetadata = policy("BREAKFAST_POLICY")?.metadata as { stillDueLocations?: unknown } | null;
  const hotelWaivedLocations = new Set(Array.isArray(hotelMetadata?.waivedLocations) ? hotelMetadata.waivedLocations.filter((value): value is string => typeof value === "string") : []); const breakfastStillDueLocations = new Set(Array.isArray(breakfastMetadata?.stillDueLocations) ? breakfastMetadata.stillDueLocations.filter((value): value is string => typeof value === "string") : []);
  const duties = dutiesResult.data ?? []; const legs = legsResult.data ?? []; const days = daysResult.data ?? []; const daysById = new Map(days.map(day => [day.id, day.schedule_date]));
  const boundaries = new Map(duties.map(duty => [duty.id, { presentationAt: at(duty.start_date, duty.check_in_time_local, duty.check_in_airport), releaseAt: duty.end_date ? at(duty.end_date, duty.check_out_time_local, duty.check_out_airport) : null }]));
  const timeline: DiemTimelineActivity[] = []; const fallbackTimezone = profile?.contractual_base ? airports.get(profile.contractual_base)?.timezone ?? null : null;
  const add = (activity: Omit<DiemTimelineActivity, "country" | "timezone" | "internationalDiemRateGroup">) => { const airport = activity.location ? airports.get(activity.location) : null; if (Date.parse(activity.endAt) > Date.parse(activity.startAt)) timeline.push({ ...activity, country: airport?.country ?? null, timezone: airport?.timezone ?? fallbackTimezone, internationalDiemRateGroup: airport?.internationalDiemRateGroup }); };
  for (const leg of legs) if (leg.departure_at_utc && leg.arrival_at_utc) { const origin = leg.origin ? airports.get(leg.origin) : null; const destination = leg.destination ? airports.get(leg.destination) : null; const internationalAirport = origin?.country !== "BR" ? origin : destination?.country !== "BR" ? destination : origin; add({ id: leg.id, contextId: leg.duty_id ?? `leg:${leg.id}`, startAt: leg.departure_at_utc, endAt: leg.arrival_at_utc, location: internationalAirport?.iata ?? leg.origin, kind: leg.leg_type === "DEADHEAD" ? "DEADHEAD" : "OPERATING", rawReference: leg.raw_text }); }
  for (const event of eventsResult.data ?? []) { const kind = eventKind[event.event_type] ?? null; const date = daysById.get(event.schedule_day_id); const location = documentedAirport(event.raw_text, event.location_airport); const timezone = location ? airports.get(location)?.timezone ?? null : fallbackTimezone; if (!kind || !date || !timezone) continue; const startAt = event.start_time_local ? localAtUtc(date, event.start_time_local, timezone) : null; const endAt = event.end_time_local ? localAtUtc(date, event.end_time_local, timezone) : null; if (startAt && endAt) add({ id: event.id, contextId: `event:${event.id}`, startAt, endAt, location, kind, rawReference: event.raw_text }); }
  for (const duty of duties) {
    const bound = boundaries.get(duty.id); const dutyLegs = legs.filter(leg => leg.duty_id === duty.id && leg.departure_at_utc && leg.arrival_at_utc).sort((left, right) => left.sequence - right.sequence);
    if (!bound || !dutyLegs.length) continue;
    if (bound.presentationAt && duty.check_in_airport) add({ id: `${duty.id}:before`, contextId: duty.id, startAt: bound.presentationAt, endAt: dutyLegs[0].departure_at_utc!, location: duty.check_in_airport, kind: "DUTY_CONTINUITY", rawReference: "CHECK_IN_TO_FIRST_LEG" });
    for (let index = 1; index < dutyLegs.length; index += 1) if (dutyLegs[index - 1].destination && dutyLegs[index - 1].destination === dutyLegs[index].origin) add({ id: `${duty.id}:ground:${index}`, contextId: duty.id, startAt: dutyLegs[index - 1].arrival_at_utc!, endAt: dutyLegs[index].departure_at_utc!, location: dutyLegs[index - 1].destination, kind: "DUTY_CONTINUITY", rawReference: "BETWEEN_LEGS" });
    if (bound.releaseAt && duty.check_out_airport) add({ id: `${duty.id}:after`, contextId: duty.id, startAt: dutyLegs.at(-1)!.arrival_at_utc!, endAt: bound.releaseAt, location: duty.check_out_airport, kind: "DUTY_CONTINUITY", rawReference: "LAST_LEG_TO_CHECK_OUT" });
  }
  const tripFacts = deriveFlightTripFacts(importId, profile?.contractual_base ?? null, duties.map(duty => ({ id: duty.id, sequence: duty.sequence, presentationAt: boundaries.get(duty.id)?.presentationAt ?? null, releaseAt: boundaries.get(duty.id)?.releaseAt ?? null, startAirport: duty.check_in_airport, endAirport: duty.check_out_airport })), hotelWaivedLocations, hotelMetadata?.defaultHotelUsed === true, legs.map(leg => ({ id: leg.id, sequence: leg.sequence, dutyId: leg.duty_id, origin: leg.origin, destination: leg.destination, departureAt: leg.departure_at_utc, arrivalAt: leg.arrival_at_utc })));
  const hotelIntervals: HotelInterval[] = tripFacts.overnights.map(overnight => ({ id: overnight.id, startAt: overnight.startAt, endAt: overnight.endAt, location: overnight.location, hotelUsed: overnight.hotelStatus === "USED" ? "TRUE" : overnight.hotelStatus === "WAIVED" ? "FALSE" : "UNKNOWN", hotelWaived: overnight.hotelStatus === "WAIVED" ? "TRUE" : "FALSE" }));
  for (const continuity of tripFacts.continuities) add({ id: continuity.id, contextId: continuity.tripId, startAt: continuity.startAt, endAt: continuity.endAt, location: continuity.location, kind: "TRIP_CONTINUITY_AWAY_FROM_BASE", rawReference: "TRIP_CONTINUITY_AWAY_FROM_BASE" });
  const transportDuties: TransportDuty[] = duties.map(duty => ({ id: duty.id, presentationAt: boundaries.get(duty.id)?.presentationAt ?? null, releaseAt: boundaries.get(duty.id)?.releaseAt ?? null, startAirport: duty.check_in_airport, endAirport: duty.check_out_airport, startTimezone: duty.check_in_airport ? airports.get(duty.check_in_airport)?.timezone ?? null : null, endTimezone: duty.check_out_airport ? airports.get(duty.check_out_airport)?.timezone ?? null : null }));
  const entitlements = deriveFinancialEntitlements({ importId, contractualBase: profile?.contractual_base ?? null, periodStart: source.document_period_start, periodEnd: source.document_period_end, activities: timeline, duties: transportDuties, mealMainDiemCents: meal?.value_cents ?? null, breakfastPercent: breakfast?.value_numeric === null || breakfast?.value_numeric === undefined ? null : Number(breakfast.value_numeric), madrugadaTransportCents: transport?.value_cents ?? null, hotelWaivedLocations, breakfastStillDueLocations, hotelUsedByDefault: hotelMetadata?.defaultHotelUsed === true, hotelIntervals });
  const removed = await supabase.from("flight_financial_entitlements").delete().eq("import_id", importId); if (removed.error) throw new Error(removed.error.message);
  const inserted = entitlements.length ? await supabase.from("flight_financial_entitlements").insert(entitlements.map(item => ({ id: item.id, user_id: source.user_id, import_id: importId, subject_type: item.subjectType, subject_id: item.subjectId, entitlement_type: item.entitlementType, entitlement_date: item.entitlementDate, location: item.location, country: item.country, domesticity: item.domesticity, currency: item.currency, amount_minor_units: item.amountMinorUnits, quantity: item.quantity, start_at: item.startAt, end_at: item.endAt, eligibility_status: item.eligibilityStatus, reason: item.reason, source_instrument_id: item.entitlementType === "MADRUGADA_TRANSPORT_REIMBURSEMENT" ? transport?.source_instrument_id ?? null : meal?.source_instrument_id ?? null, source_clause: item.entitlementType === "MADRUGADA_TRANSPORT_REIMBURSEMENT" ? transport?.source_clause_reference ?? "5.9" : "2.4", profile_fact_source: profile?.source_reference ?? null, confidence: item.confidence, lifecycle: item.eligibilityStatus === "UNKNOWN" ? "REVIEW_REQUIRED" : "REVIEWED", engine_version: FLIGHT_FINANCIAL_ENTITLEMENTS_VERSION, provenance: item.provenance }))) : { error: null };
  if (inserted.error) throw new Error(inserted.error.message);
  const deletedOvernights = await supabase.from("flight_trip_overnights").delete().eq("import_id", importId); if (deletedOvernights.error) throw new Error(deletedOvernights.error.message);
  const deletedTrips = await supabase.from("flight_trips").delete().eq("import_id", importId); if (deletedTrips.error) throw new Error(deletedTrips.error.message);
  if (tripFacts.trips.length) { const insertedTrips = await supabase.from("flight_trips").insert(tripFacts.trips.map(trip => ({ id: trip.id, user_id: source.user_id, import_id: importId, start_duty_id: trip.startDutyId, end_duty_id: trip.endDutyId, trip_start_at: trip.tripStartAt, trip_end_at: trip.tripEndAt, contractual_base: trip.contractualBase, starts_at_base: trip.startsAtBase, ends_at_base: trip.endsAtBase, away_from_base: trip.awayFromBase, locations: trip.locations, confidence: trip.confidence, provenance: trip.provenance }))); if (insertedTrips.error) throw new Error(insertedTrips.error.message); }
  if (tripFacts.overnights.length) { const insertedOvernights = await supabase.from("flight_trip_overnights").insert(tripFacts.overnights.map(overnight => ({ id: overnight.id, user_id: source.user_id, import_id: importId, trip_id: overnight.tripId, previous_duty_id: overnight.previousDutyId, next_duty_id: overnight.nextDutyId, location: overnight.location, start_at: overnight.startAt, end_at: overnight.endAt, hotel_status: overnight.hotelStatus, source: overnight.source, confidence: overnight.confidence, provenance: { algorithm: "deriveFlightTripFacts", tripId: overnight.tripId } }))); if (insertedOvernights.error) throw new Error(insertedOvernights.error.message); }
  const diemCycles = deriveFlightDiemPaymentCycles(importId, source.user_id, entitlements.map(item => ({ entitlement_date: item.entitlementDate, eligibility_status: item.eligibilityStatus, amount_minor_units: item.amountMinorUnits, currency: item.currency })));
  const deletedCycles = await supabase.from("flight_diem_payment_cycles").delete().eq("import_id", importId); if (deletedCycles.error) throw new Error(deletedCycles.error.message);
  if (diemCycles.length) { const insertedCycles = await supabase.from("flight_diem_payment_cycles").insert(diemCycles); if (insertedCycles.error) throw new Error(insertedCycles.error.message); }
  const reconciliation = await persistFlightDiemReconciliation(supabase, source.user_id, importId, entitlements);
  return { importId, engineVersion: FLIGHT_FINANCIAL_ENTITLEMENTS_VERSION, contractualBase: profile?.contractual_base ?? null, entitlementCount: entitlements.length, timelineCount: timeline.length, tripCount: tripFacts.trips.length, overnightCount: tripFacts.overnights.length, hotelIntervalCount: hotelIntervals.length, diemCycles, reconciliation, totals: summarizeFinancialEntitlements(entitlements), entitlements };
}
