import { createClient } from "@supabase/supabase-js";
import { flightAirports, localAtUtc } from "@/modules/flight/time-metrics";
import { FLIGHT_FINANCIAL_SPECIAL_TIME_VERSION, holidayAppliesToBase, segmentFinancialInterval, segmentGroundFinancialInterval, summarizeSpecialTime } from "./financial-special-time";

export async function buildFlightFinancialSpecialTime(importId: string, ownerUserId?: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error("As credenciais de servidor não foram configuradas.");
  const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); const imported = await supabase.from("flight_schedule_imports").select("id,user_id,document_period_start").eq("id", importId).maybeSingle();
  if (imported.error || !imported.data || (ownerUserId && imported.data.user_id !== ownerUserId)) throw new Error("Importação de escala não encontrada.");
  const source = imported.data; const year = Number((source.document_period_start ?? "").slice(0, 4));
  const [legs, events, holidays, calendar, profiles] = await Promise.all([
    supabase.from("flight_legs").select("id,leg_type,departure_at_utc,arrival_at_utc").eq("import_id", importId).in("leg_type", ["OPERATING", "DEADHEAD"]),
    supabase.from("flight_schedule_events").select("id,event_type,start_time_local,end_time_local,location_airport,schedule_day_id,flight_schedule_days!inner(schedule_date)").eq("import_id", importId).in("event_type", ["STANDBY", "RESERVE"]),
    supabase.from("flight_holidays").select("holiday_date,name,scope,base_code").eq("year", year).eq("verified", true),
    supabase.from("flight_holiday_calendar_years").select("base_code,status").eq("year", year).eq("country", "BR"),
    supabase.from("flight_compensation_profiles").select("contractual_base,effective_from,effective_to").eq("user_id", source.user_id).order("effective_from", { ascending: false }),
  ]);
  if (legs.error || events.error || holidays.error || calendar.error || profiles.error) throw new Error(legs.error?.message ?? events.error?.message ?? holidays.error?.message ?? calendar.error?.message ?? profiles.error?.message ?? "Não foi possível carregar a segmentação financeira.");
  const profile = (profiles.data ?? []).find(item => item.effective_from <= (source.document_period_start ?? "") && (item.effective_to === null || item.effective_to >= (source.document_period_start ?? ""))) ?? null; const contractualBase = profile?.contractual_base ?? null; const calendarStatus = (calendar.data ?? []).find(item => item.base_code === contractualBase)?.status ?? (calendar.data ?? []).find(item => item.base_code === null)?.status ?? "UNKNOWN";
  const applicableHolidays = (holidays.data ?? []).filter(holiday => holidayAppliesToBase({ scope: holiday.scope, baseCode: holiday.base_code }, contractualBase)).map(holiday => ({ date: holiday.holiday_date, name: holiday.name, scope: holiday.scope }));
  const flightSegments = (legs.data ?? []).flatMap(leg => leg.departure_at_utc && leg.arrival_at_utc ? segmentFinancialInterval({ importId, subjectId: leg.id, activityType: leg.leg_type as "OPERATING" | "DEADHEAD", startAt: leg.departure_at_utc, endAt: leg.arrival_at_utc, holidays: applicableHolidays, calendarComplete: calendarStatus === "VERIFIED" }) : []);
  const eventSegments = (events.data ?? []).flatMap(event => { const day = event.flight_schedule_days as unknown as { schedule_date: string } | null; const airport = flightAirports.find(item => item.iata === event.location_airport); if (!day || !airport || !event.start_time_local || !event.end_time_local) return []; const startAt = localAtUtc(day.schedule_date, event.start_time_local, airport.timezone); const next = event.end_time_local < event.start_time_local ? new Date(Date.parse(`${day.schedule_date}T12:00:00Z`) + 86400000).toISOString().slice(0, 10) : day.schedule_date; const endAt = localAtUtc(next, event.end_time_local, airport.timezone); return segmentGroundFinancialInterval({ importId, subjectId: event.id, activityType: event.event_type as "STANDBY" | "RESERVE", startAt, endAt, holidays: applicableHolidays, calendarComplete: calendarStatus === "VERIFIED", timezone: airport.timezone, equivalenceDenominator: event.event_type === "STANDBY" ? 3 : 1 }); });
  const segments = [...flightSegments, ...eventSegments]; const removed = await supabase.from("flight_financial_segments").delete().eq("import_id", importId); if (removed.error) throw new Error(removed.error.message);
  if (segments.length) { const inserted = await supabase.from("flight_financial_segments").insert(segments.map(segment => ({ id: segment.id, import_id: importId, subject_type: segment.activityType === "STANDBY" || segment.activityType === "RESERVE" ? "EVENT" : "LEG", subject_id: segment.subjectId, activity_type: segment.activityType, start_at: segment.startAt, end_at: segment.endAt, duration_seconds: segment.durationSeconds, is_night: segment.isNight, is_sunday: segment.isSunday, holiday_status: segment.holidayStatus, holiday_name: segment.holidayName, holiday_scope: segment.holidayScope, reference_timezone: segment.activityType === "RESERVE" ? "LOCAL" : segment.referenceTimezone, normal_equivalent_seconds: segment.normalEquivalentSeconds, night_equivalent_numerator_seconds: segment.nightEquivalentNumeratorSeconds, night_equivalent_denominator: segment.nightEquivalentDenominator, provenance: segment.provenance }))); if (inserted.error) throw new Error(inserted.error.message); }
  const byActivity = (activityType: "OPERATING" | "DEADHEAD" | "STANDBY" | "RESERVE") => summarizeSpecialTime(segments.filter(segment => segment.activityType === activityType));
  return { importId, engineVersion: FLIGHT_FINANCIAL_SPECIAL_TIME_VERSION, calendarStatus, contractualBase, segmentCount: segments.length, operating: byActivity("OPERATING"), deadhead: byActivity("DEADHEAD"), standby: byActivity("STANDBY"), reserve: byActivity("RESERVE") };
}
