import { createHash } from "node:crypto";

export const FLIGHT_FINANCIAL_CLOSURE_VERSION = "flight-financial-closure/1.0.0";
export type ClosureLineType = "SALARY_FLOOR" | "SENIORITY" | "NORMAL_VARIABLE" | "DEADHEAD" | "STANDBY" | "RESERVE" | "NIGHT" | "SUNDAY" | "HOLIDAY" | "DOMESTIC_BREAKFAST" | "DOMESTIC_LUNCH" | "DOMESTIC_DINNER" | "DOMESTIC_SUPPER" | "MADRUGADA_TRANSPORT" | "INTERNATIONAL_DIEMS";
export type CalculationStatus = "CALCULATED" | "UNKNOWN" | "NOT_APPLICABLE" | "PROVISIONAL";
export type ClosureLineInput = { componentType: ClosureLineType; sourceImport: "PLANNED" | "EXECUTED" | "ADDITIVE" | "MIXED" | "NONE"; quantity: number; quantityUnit: string; rateMinorUnits: number | null; multiplierNumerator?: number; multiplierDenominator?: number; decisionStatus?: string | null; calculationStatus: CalculationStatus; reason: string | null; currency: string | null; parameterId: string | null; sourceInstrumentId?: string | null; sourceClause?: string | null; confidence: "HIGH" | "MEDIUM" | "LOW" };
export type ClosureLine = ClosureLineInput & { id: string; amountMinorUnits: number | null; multiplierNumerator: number; multiplierDenominator: number; provenance: Record<string, unknown> };
function id(closureId: string, type: ClosureLineType) { const hash = createHash("sha256").update(`${FLIGHT_FINANCIAL_CLOSURE_VERSION}:${closureId}:${type}`).digest("hex"); return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-5${hash.slice(13, 16)}-${(Number.parseInt(hash.slice(16, 18), 16) & 0x3f | 0x80).toString(16)}${hash.slice(18, 20)}-${hash.slice(20, 32)}`; }
export function closureId(userId: string, year: number, month: number, executedImportId: string) { const hash = createHash("sha256").update(`${FLIGHT_FINANCIAL_CLOSURE_VERSION}:${userId}:${year}:${month}:${executedImportId}`).digest("hex"); return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-5${hash.slice(13, 16)}-${(Number.parseInt(hash.slice(16, 18), 16) & 0x3f | 0x80).toString(16)}${hash.slice(18, 20)}-${hash.slice(20, 32)}`; }
export function materializeClosureLines(closure: string, inputs: ClosureLineInput[]) { return inputs.map(input => { const numerator = input.multiplierNumerator ?? 1; const denominator = input.multiplierDenominator ?? 1; const rate = input.rateMinorUnits; const calculable = input.calculationStatus === "CALCULATED" && rate !== null; const amount = calculable && rate !== null ? Math.round(input.quantity * rate * numerator / denominator) : input.calculationStatus === "NOT_APPLICABLE" ? 0 : null; return { ...input, id: id(closure, input.componentType), amountMinorUnits: amount, multiplierNumerator: numerator, multiplierDenominator: denominator, provenance: { algorithm: "materializeClosureLines", version: FLIGHT_FINANCIAL_CLOSURE_VERSION, decisionStatus: input.decisionStatus, rateValueKnown: rate !== null, rateApplicable: input.calculationStatus === "CALCULATED" } }; }); }
export function summarizeClosure(lines: readonly ClosureLine[]) { const knownTotalBrl = lines.filter(line => line.currency === "BRL" && line.amountMinorUnits !== null).reduce((sum, line) => sum + line.amountMinorUnits!, 0); const incomplete = lines.some(line => line.currency === "BRL" && line.calculationStatus === "UNKNOWN"); const provisional = lines.some(line => line.calculationStatus === "PROVISIONAL"); return { knownTotalBrl, finalTotalBrl: incomplete ? null : knownTotalBrl, finalTotalStatus: incomplete ? "INCOMPLETE" : provisional ? "PROVISIONAL" : "COMPLETE" as "INCOMPLETE" | "PROVISIONAL" | "COMPLETE" }; }
