import assert from "node:assert/strict";
import test from "node:test";
import { holidayAppliesToBase, segmentFinancialInterval, segmentGroundFinancialInterval, summarizeSpecialTime } from "./financial-special-time";

const input = (startAt: string, endAt: string) => ({ importId: "import", subjectId: "leg", activityType: "OPERATING" as const, startAt, endAt, holidays: [], calendarComplete: true });
test("segments exact UTC night boundaries without duplicating timeline", () => { const segments = segmentFinancialInterval(input("2026-08-03T20:30:00.000Z", "2026-08-03T21:30:00.000Z")); assert.deepEqual(segments.map(item => [item.durationSeconds, item.isNight]), [[1800, false], [1800, true]]); assert.equal(summarizeSpecialTime(segments).actualSeconds, 3600); });
test("uses exact 8/7 night equivalence and Sunday attribute on one timeline", () => { const segments = segmentFinancialInterval(input("2026-08-09T21:00:00.000Z", "2026-08-09T22:00:00.000Z")); const summary = summarizeSpecialTime(segments); assert.equal(summary.actualSeconds, 3600); assert.equal(summary.nightEquivalentNumeratorSeconds, 28800); assert.equal(summary.nightEquivalentDenominator, 7); assert.equal(summary.nightSundaySeconds, 3600); });
test("keeps holiday classification pending when the verified calendar is incomplete", () => { assert.equal(segmentFinancialInterval({ ...input("2026-08-03T10:00:00.000Z", "2026-08-03T11:00:00.000Z"), calendarComplete: false })[0].holidayStatus, "UNKNOWN"); });
test("applies national holidays to every base and municipal holidays only to their contractual base", () => { assert.equal(holidayAppliesToBase({ scope: "NATIONAL", baseCode: null }, null), true); assert.equal(holidayAppliesToBase({ scope: "BASE_MUNICIPAL", baseCode: "SAO" }, "SAO"), true); assert.equal(holidayAppliesToBase({ scope: "BASE_MUNICIPAL", baseCode: "SAO" }, "GRU"), false); });
test("resolves a verified BSB calendar without turning local holidays into duplicate timeline", () => { const segments = segmentFinancialInterval({ ...input("2026-08-03T10:00:00.000Z", "2026-08-03T11:00:00.000Z"), calendarComplete: true }); assert.equal(segments[0].holidayStatus, "FALSE"); assert.equal(summarizeSpecialTime(segments).normalGuaranteeEligibleSeconds, 3600); });
test("segments reserve with the local 22:00 to 05:00 ground-night window", () => { const segments = segmentGroundFinancialInterval({ ...input("2026-08-04T00:00:00.000Z", "2026-08-04T02:00:00.000Z"), activityType: "RESERVE", timezone: "America/Sao_Paulo", equivalenceDenominator: 1 }); assert.deepEqual(segments.map(item => item.isNight), [false, true]); });
test("segments standby before applying one-third equivalence", () => { const segments = segmentGroundFinancialInterval({ ...input("2026-08-04T20:00:00.000Z", "2026-08-04T22:00:00.000Z"), activityType: "STANDBY", timezone: "UTC", equivalenceDenominator: 3 }); assert.equal(segments.reduce((sum, item) => sum + item.durationSeconds, 0), 7200); assert.equal(segments.length, 2); assert.equal(segments[1]?.nightEquivalentDenominator, 3); });
