import { EmptyState } from "@/components/finance/empty-state";
import { SubmitButton } from "@/components/finance/submit-button";
import { createLoan } from "@/modules/finance/actions";
import { requireFinanceAccess } from "@/modules/finance/access";
import { formatCurrency,formatDate } from "@/modules/finance/format";
import { getFinanceData } from "@/modules/finance/queries";

export default async function LoansPage(){const {supabase,user}=await requireFinanceAccess();const data=await getFinanceData(supabase,user.id);return <>
 <section className="finance-panel"><header><div><p className="eyebrow">Dívidas e competências</p><h2>Empréstimos</h2></div></header>{data.loans.length?<div className="loan-list">{data.loans.map(loan=><details key={loan.id} className="loan-card"><summary><span><b>{loan.name}</b><small>{loan.institution_name||"Cadastro manual"} · {loan.payroll_deducted?"Desconto em folha":loan.loan_type}</small></span><strong className="negative">{loan.outstanding_balance===null?"Saldo não informado":formatCurrency(Number(loan.outstanding_balance))}</strong></summary><dl><div><dt>Tipo</dt><dd>{loan.loan_type}</dd></div>{loan.outstanding_balance!==null?<div><dt>Saldo devedor</dt><dd>{formatCurrency(Number(loan.outstanding_balance))}</dd></div>:loan.contracted_amount!==null?<div><dt>Valor contratado</dt><dd>{formatCurrency(Number(loan.contracted_amount))} · saldo devedor não informado pelo banco</dd></div>:null}{loan.installment_amount!==null?<div><dt>Parcela mensal</dt><dd>{formatCurrency(Number(loan.installment_amount))}</dd></div>:null}{loan.installments_remaining!==null?<div><dt>Parcelas restantes</dt><dd>{loan.installments_remaining}</dd></div>:null}{loan.interest_rate!==null?<div><dt>Taxa</dt><dd>{(Number(loan.interest_rate)*100).toLocaleString("pt-BR",{maximumFractionDigits:4})}%</dd></div>:null}{loan.final_due_date?<div><dt>Data final</dt><dd>{formatDate(loan.final_due_date)}</dd></div>:null}{loan.payroll_deducted?<div><dt>Origem do pagamento</dt><dd>Desconto em folha</dd></div>:null}{loan.last_sync_at?<div><dt>Última atualização</dt><dd>{formatDate(loan.last_sync_at)}</dd></div>:null}</dl></details>)}</div>:<EmptyState title="Nenhum contrato cadastrado" description="A conexão bancária pode não disponibilizar empréstimos. Cadastre o consignado manualmente sem criar uma saída na conta."/>}</section>
 <section id="novo" className="finance-panel"><header><div><p className="eyebrow">Alternativa segura</p><h2>Cadastrar consignado manualmente</h2></div></header><p className="loan-helper">As parcelas serão previsões por competência com origem desconto em folha e não afetarão uma conta bancária.</p><form action={createLoan} className="finance-form loan-form"><label>Nome do contrato<input name="name" required maxLength={160}/></label><label>Instituição<input name="institution_name" maxLength={120}/></label><label>Tipo<select name="loan_type" defaultValue="Consignado"><option>Consignado</option><option>Crédito pessoal</option><option>Financiamento</option><option>Outro</option></select></label><label>Valor contratado<input name="contracted_amount" inputMode="decimal" placeholder="Opcional"/></label><label>Saldo devedor<input name="outstanding_balance" inputMode="decimal" placeholder="Opcional"/></label><label>Valor da parcela<input name="installment_amount" inputMode="decimal" placeholder="Opcional"/></label><label>Quantidade total<input name="installment_count" inputMode="numeric"/></label><label>Parcelas pagas<input name="installments_paid" inputMode="numeric" defaultValue="0"/></label><label>Primeira parcela<input name="first_installment_date" type="date"/></label><label>Data final<input name="final_due_date" type="date"/></label><label>Taxa (% ao período)<input name="interest_rate" inputMode="decimal"/></label><label className="loan-checkbox"><input name="payroll_deducted" type="checkbox" defaultChecked/> Desconto em folha</label><label className="loan-notes">Observações<input name="notes" maxLength={1000}/></label><SubmitButton>Salvar contrato</SubmitButton></form><small className="loan-future-attachment">Documento anexo: suporte preparado para uma etapa futura.</small></section>
 </>}
