import { createClient } from "@supabase/supabase-js";
import { validateFactsForPersistence } from "./flight-facts-validation";
import { buildCanonicalFlightFacts, FLIGHT_FACTS_VERSION, type FactInput, type FactRecord, validateFlightFacts } from "./flight-facts";
import { matchOffPeriods, type OffPeriodForMatching } from "./off-period-matching";
import { deriveOffSubstitutionFacts } from "./off-substitution-facts";
import { deriveReprogrammingFact, type DutyProgramming, type ReprogrammingExternalFact } from "./reprogramming-facts";
import { deriveExtensionFacts } from "./extension-facts";

type ImportRow = { id: string; user_id: string; schedule_month_id: string; schedule_role: "PLANNED" | "EXECUTION_SNAPSHOT" | "FINAL_EXECUTED"; home_base: string | null; parser_version: string | null; uploaded_at: string; document_generated_at: string | null };
type DutyRow = FactInput["duties"][number];
type LegRow = FactInput["legs"][number];
type EventRow = Omit<FactInput["events"][number], "schedule_date"> & { schedule_day_id: string };

export async function buildFlightFacts(scheduleImportId: string, ownerUserId?: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceRoleKey) throw new Error("As credenciais de servidor do Supabase não foram configuradas.");
  const supabase = createClient(url, serviceRoleKey, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } });
  const imported = await supabase.from("flight_schedule_imports").select("id,user_id,schedule_month_id,schedule_role,home_base,parser_version,uploaded_at,document_generated_at").eq("id", scheduleImportId).maybeSingle();
  const source = imported.data as unknown as ImportRow | null;
  if (imported.error || !source || (ownerUserId && source.user_id !== ownerUserId)) throw new Error("Importação de escala não encontrada.");
  const [dutiesResult, legsResult, eventsResult, daysResult, profileResult] = await Promise.all([
    supabase.from("flight_duties").select("id,sequence,start_date,end_date,check_in_airport,check_out_airport,check_in_time_local,check_out_time_local,calculated_flight_time_minutes").eq("import_id", scheduleImportId).order("sequence"),
    supabase.from("flight_legs").select("id,duty_id,duty_link_status,sequence,leg_type,flight_number,origin,destination,aircraft_code,departure_at_utc,arrival_at_utc,calculated_duration_minutes,raw_departure,raw_arrival,raw_metadata").eq("import_id", scheduleImportId).order("sequence"),
    supabase.from("flight_schedule_events").select("id,schedule_day_id,event_type,event_code,start_time_local,end_time_local,location_airport").eq("import_id", scheduleImportId).order("sequence"),
    supabase.from("flight_schedule_days").select("id,schedule_date").eq("import_id", scheduleImportId),
    supabase.from("flight_legal_profile_facts").select("document_contractual_base,profile_contractual_base").eq("user_id", source.user_id).order("updated_at", { ascending: false }).limit(1).maybeSingle(),
  ]);
  if (dutiesResult.error || legsResult.error || eventsResult.error || daysResult.error) throw new Error("Não foi possível carregar os fatos documentais da escala.");
  if (profileResult.error) throw new Error(profileResult.error.message);
  const days = new Map((daysResult.data ?? []).map((day) => [String(day.id), String(day.schedule_date)]));
  const profile = profileResult.data as { document_contractual_base: string | null; profile_contractual_base: string | null } | null;
  const contractualBase = profile?.document_contractual_base && profile.document_contractual_base === profile.profile_contractual_base ? profile.document_contractual_base : null;
  const input: FactInput = {
    importId: source.id, scheduleState: source.schedule_role, homeBase: source.home_base, contractualBase, parserVersion: source.parser_version, importedAt: source.uploaded_at, printedAt: source.document_generated_at,
    duties: (dutiesResult.data ?? []) as unknown as DutyRow[], legs: (legsResult.data ?? []) as unknown as LegRow[],
    events: (eventsResult.data ?? []).flatMap((event) => { const row = event as unknown as EventRow; const scheduleDate = days.get(row.schedule_day_id); return scheduleDate ? [{ ...row, schedule_date: scheduleDate }] : []; }),
  };
  const result = buildCanonicalFlightFacts(input);
  const canonicalValidation = validateFlightFacts(result);
  if (!canonicalValidation.valid) throw new Error(`Facts invÃ¡lidos: ${canonicalValidation.errors.join(" ")}`);
  if (source.schedule_role === "EXECUTION_SNAPSHOT" || source.schedule_role === "FINAL_EXECUTED") {
    const planned = await supabase.from("flight_schedule_imports").select("id").eq("schedule_month_id", source.schedule_month_id).eq("schedule_role", "PLANNED").maybeSingle();
    if (planned.data) {
      const [plannedLegs, plannedEvents, plannedDays, plannedDuties] = await Promise.all([
        supabase.from("flight_legs").select("id,leg_type,flight_number,origin,destination,departure_at_utc,arrival_at_utc").eq("import_id", planned.data.id),
        supabase.from("flight_schedule_events").select("id,schedule_day_id,event_type,event_code,start_time_local,end_time_local").eq("import_id", planned.data.id),
        supabase.from("flight_schedule_days").select("id,schedule_date").eq("import_id", planned.data.id),
        supabase.from("flight_duties").select("id,start_date,end_date,check_in_airport,check_out_airport,check_in_time_local,check_out_time_local,calculated_flight_time_minutes").eq("import_id", planned.data.id),
      ]);
      if (!plannedLegs.error && !plannedEvents.error && !plannedDays.error && !plannedDuties.error) {
        const changes: FactRecord[] = []; const signature = (leg: { leg_type: string; flight_number: string; origin: string | null; destination: string | null; departure_at_utc: string | null; arrival_at_utc: string | null }) => `${leg.leg_type}:${leg.flight_number}:${leg.origin}:${leg.destination}:${leg.departure_at_utc}:${leg.arrival_at_utc}`; const plannedLegKeys = new Set((plannedLegs.data ?? []).map(signature)); const executedLegKeys = new Set(input.legs.map(signature));
        const matchedPlannedLegIds = new Set<string>(); const matchedExecutedLegIds = new Set<string>();
        for (const leg of input.legs) { const comparable = signature(leg); if (plannedLegKeys.has(comparable)) continue; const candidates = (plannedLegs.data ?? []).filter((candidate) => candidate.flight_number === leg.flight_number && candidate.origin === leg.origin && candidate.destination === leg.destination && candidate.leg_type === leg.leg_type); if (candidates.length === 1) { const candidate = candidates[0]; matchedPlannedLegIds.add(candidate.id); matchedExecutedLegIds.add(leg.id); changes.push({ factKey: "schedule_change", subjectType: "SCHEDULE_CHANGE", subjectId: leg.id, value: { plannedImportId: planned.data.id, executedImportId: source.id, changeType: "LEG_CHANGED", plannedReference: candidate.id, executedReference: leg.id, plannedValue: signature(candidate), executedValue: comparable, differences: { departureAt: [candidate.departure_at_utc, leg.departure_at_utc], arrivalAt: [candidate.arrival_at_utc, leg.arrival_at_utc] }, affectedStart: leg.departure_at_utc, affectedEnd: leg.arrival_at_utc, detected: true, origin: "UNKNOWN", voluntary: "UNKNOWN", reason: null, confirmedByUser: false }, sourceType: "CALCULATED", confidence: "HIGH", provenance: { algorithm: "matchLegByStableRouteAndFlight", algorithmVersion: FLIGHT_FACTS_VERSION } }); } else changes.push({ factKey: "schedule_change", subjectType: "SCHEDULE_CHANGE", subjectId: leg.id, value: { plannedImportId: planned.data.id, executedImportId: source.id, changeType: "LEG_ADDED", plannedReference: null, executedReference: leg.id, plannedValue: null, executedValue: comparable, affectedStart: leg.departure_at_utc, affectedEnd: leg.arrival_at_utc, detected: true, origin: "UNKNOWN", voluntary: "UNKNOWN", reason: null, confirmedByUser: false, matchingStatus: candidates.length > 1 ? "AMBIGUOUS" : "UNMATCHED" }, sourceType: "CALCULATED", confidence: "HIGH", provenance: { algorithm: "comparePlannedToExecution", algorithmVersion: FLIGHT_FACTS_VERSION } }); }
        for (const leg of plannedLegs.data ?? []) { const comparable = signature(leg); if (!executedLegKeys.has(comparable) && !matchedPlannedLegIds.has(leg.id)) changes.push({ factKey: "schedule_change", subjectType: "SCHEDULE_CHANGE", subjectId: null, value: { plannedImportId: planned.data.id, executedImportId: source.id, changeType: "LEG_REMOVED", plannedReference: leg.id, executedReference: null, plannedValue: comparable, executedValue: null, affectedStart: leg.departure_at_utc, affectedEnd: leg.arrival_at_utc, detected: true, origin: "UNKNOWN", voluntary: "UNKNOWN", reason: null, confirmedByUser: false }, sourceType: "CALCULATED", confidence: "HIGH", provenance: { algorithm: "comparePlannedToExecution", algorithmVersion: FLIGHT_FACTS_VERSION } }); }
        const dutySignature = (duty: { start_date: string; check_in_airport: string | null; check_out_airport: string | null }) => `${duty.start_date}:${duty.check_in_airport}:${duty.check_out_airport}`;
        const clockMinutes = (time: string | null) => time ? Number(time.slice(0, 2)) * 60 + Number(time.slice(3, 5)) : null;
        for (const duty of input.duties) { const candidates = (plannedDuties.data ?? []).filter((candidate) => dutySignature(candidate) === dutySignature(duty)); if (candidates.length !== 1) continue; const plannedDuty = candidates[0]; const baseChange = { plannedImportId: planned.data.id, executedImportId: source.id, plannedReference: plannedDuty.id, executedReference: duty.id, detected: true, origin: "UNKNOWN", voluntary: "UNKNOWN", reason: null, confirmedByUser: false }; const changed = plannedDuty.end_date !== duty.end_date || plannedDuty.check_in_time_local !== duty.check_in_time_local || plannedDuty.check_out_time_local !== duty.check_out_time_local || plannedDuty.calculated_flight_time_minutes !== duty.calculated_flight_time_minutes; if (changed) changes.push({ factKey: "schedule_change", subjectType: "SCHEDULE_CHANGE", subjectId: duty.id, value: { ...baseChange, changeType: "DUTY_CHANGED", plannedValue: plannedDuty, executedValue: duty }, sourceType: "CALCULATED", confidence: "HIGH", provenance: { algorithm: "matchDutyByDateAndAirports", algorithmVersion: FLIGHT_FACTS_VERSION } }); for (const [changeType, plannedValue, executedValue] of [["REPORT_TIME_CHANGED", plannedDuty.check_in_time_local, duty.check_in_time_local], ["RELEASE_TIME_CHANGED", plannedDuty.check_out_time_local, duty.check_out_time_local]] as const) if (plannedValue && executedValue && plannedValue !== executedValue) changes.push({ factKey: "schedule_change", subjectType: "SCHEDULE_CHANGE", subjectId: duty.id, value: { ...baseChange, changeType, plannedValue, executedValue, deltaMinutes: clockMinutes(executedValue)! - clockMinutes(plannedValue)! }, sourceType: "CALCULATED", confidence: "HIGH", provenance: { algorithm: "matchDutyByDateAndAirports", algorithmVersion: FLIGHT_FACTS_VERSION } }); }
        const plannedDayMap = new Map((plannedDays.data ?? []).map((day) => [String(day.id), String(day.schedule_date)])); const plannedEventKeys = new Set((plannedEvents.data ?? []).map((event) => `${plannedDayMap.get(String(event.schedule_day_id))}:${event.event_type}:${event.event_code}:${event.start_time_local}:${event.end_time_local}`));
        const plannedEventRows = (plannedEvents.data ?? []).map((event) => ({ ...event, scheduleDate: plannedDayMap.get(String(event.schedule_day_id)) ?? null }));
        for (const event of input.events) { const key = `${event.schedule_date}:${event.event_type}:${event.event_code}:${event.start_time_local}:${event.end_time_local}`; if (plannedEventKeys.has(key)) continue; const candidates = plannedEventRows.filter((candidate) => candidate.scheduleDate === event.schedule_date && candidate.event_type === event.event_type && candidate.event_code === event.event_code); if (candidates.length === 1) { const candidate = candidates[0]; changes.push({ factKey: "schedule_change", subjectType: "SCHEDULE_CHANGE", subjectId: event.id, value: { plannedImportId: planned.data.id, executedImportId: source.id, changeType: "EVENT_CHANGED", plannedReference: candidate.id, executedReference: event.id, plannedValue: { startAt: candidate.start_time_local, endAt: candidate.end_time_local, sourceCode: candidate.event_code, semanticType: candidate.event_type }, executedValue: { startAt: event.start_time_local, endAt: event.end_time_local, sourceCode: event.event_code, semanticType: event.event_type, location: event.location_airport }, affectedStart: event.schedule_date, affectedEnd: event.schedule_date, detected: true, origin: "UNKNOWN", voluntary: "UNKNOWN", reason: null, confirmedByUser: false }, sourceType: "CALCULATED", confidence: "HIGH", provenance: { algorithm: "matchEventByDateTypeAndCode", algorithmVersion: FLIGHT_FACTS_VERSION } }); } else changes.push({ factKey: "schedule_change", subjectType: "SCHEDULE_CHANGE", subjectId: event.id, value: { plannedImportId: planned.data.id, executedImportId: source.id, changeType: "EVENT_ADDED", plannedReference: null, executedReference: event.id, plannedValue: null, executedValue: key, affectedStart: event.schedule_date, affectedEnd: event.schedule_date, detected: true, origin: "UNKNOWN", voluntary: "UNKNOWN", reason: null, confirmedByUser: false, matchingStatus: candidates.length > 1 ? "AMBIGUOUS" : "UNMATCHED" }, sourceType: "CALCULATED", confidence: "HIGH", provenance: { algorithm: "comparePlannedToExecution", algorithmVersion: FLIGHT_FACTS_VERSION } }); }
        result.facts.push(...changes); Object.assign(result.summary, { scheduleChanges: changes.length });
        const changedDuties = changes.filter((change) => change.value.changeType === "DUTY_CHANGED");
        const plannedDutyFactsResult = await supabase.from("flight_fact_records").select("subject_id,value").eq("import_id", planned.data.id).eq("fact_key", "duty");
        const externalFactsResult = await supabase.from("flight_external_facts").select("fact_key,value").eq("import_id", source.id).in("fact_key", ["REPROGRAMMING_AT", "FITNESS_DECLARATION", "UNEXPECTED_OPERATIONAL_CIRCUMSTANCE", "COMMANDER_EXTENSION_DECISION"]);
        if (!plannedDutyFactsResult.error) {
          const plannedFactById = new Map((plannedDutyFactsResult.data ?? []).map((fact) => [String(fact.subject_id), fact.value as Record<string, unknown>]));
          const executedFactById = new Map(result.facts.filter((fact) => fact.factKey === "duty" && fact.subjectId).map((fact) => [String(fact.subjectId), fact.value]));
          const externalFacts: ReprogrammingExternalFact[] = externalFactsResult.error ? [] : (externalFactsResult.data ?? []).flatMap((fact) => { const value = fact.value as Record<string, unknown>; const dutyId = typeof value.dutyId === "string" ? value.dutyId : null; return ["REPROGRAMMING_AT", "FITNESS_DECLARATION", "UNEXPECTED_OPERATIONAL_CIRCUMSTANCE", "COMMANDER_EXTENSION_DECISION"].includes(fact.fact_key) ? [{ factKey: fact.fact_key as ReprogrammingExternalFact["factKey"], dutyId, value: value.value ?? value }] : []; });
          const dutyProgramming = (id: string, value: Record<string, unknown>): DutyProgramming => ({ id, operatingLegCount: typeof value.operatingLegCount === "number" ? value.operatingLegCount : null, totalLegCount: typeof value.totalLegCount === "number" ? value.totalLegCount : null, dutyMinutes: typeof value.durationMinutes === "number" ? value.durationMinutes : null, flightTimeMinutes: typeof value.flightTimeMinutes === "number" ? value.flightTimeMinutes : null, presentationAt: typeof value.presentationAt === "string" ? value.presentationAt : null });
          for (const change of changedDuties) { const plannedId = typeof change.value.plannedReference === "string" ? change.value.plannedReference : null; const executedId = typeof change.value.executedReference === "string" ? change.value.executedReference : null; const plannedValue = plannedId ? plannedFactById.get(plannedId) ?? null : null; const executedValue = executedId ? executedFactById.get(executedId) ?? null : null; const plannedDuty = plannedId && plannedValue ? dutyProgramming(plannedId, plannedValue) : null; const executedDuty = executedId && executedValue ? dutyProgramming(executedId, executedValue) : null; const value = deriveReprogrammingFact(plannedDuty, executedDuty, Boolean(plannedId && executedId), externalFacts); const external = (key: ReprogrammingExternalFact["factKey"]) => externalFacts.find((fact) => fact.factKey === key && fact.dutyId === executedId)?.value; const extension = deriveExtensionFacts({ plannedDutyId: plannedId, executedDutyId: executedId, plannedDutyMinutes: plannedDuty?.dutyMinutes ?? null, executedDutyMinutes: executedDuty?.dutyMinutes ?? null, plannedFlightTimeMinutes: plannedDuty?.flightTimeMinutes ?? null, executedFlightTimeMinutes: executedDuty?.flightTimeMinutes ?? null, plannedOperatingLegCount: plannedDuty?.operatingLegCount ?? null, executedOperatingLegCount: executedDuty?.operatingLegCount ?? null, normalDutyLimitMinutes: null, normalFlightTimeLimitMinutes: null, matched: Boolean(plannedId && executedId), unexpectedOperationalCircumstance: external("UNEXPECTED_OPERATIONAL_CIRCUMSTANCE"), commanderExtensionDecision: external("COMMANDER_EXTENSION_DECISION") }); result.facts.push({ factKey: "duty_reprogramming", subjectType: "DUTY", subjectId: executedId, value, sourceType: "CALCULATED", confidence: value.reprogrammingDetected === "UNKNOWN" ? "LOW" : "HIGH", provenance: { algorithm: "deriveDutyReprogramming", algorithmVersion: FLIGHT_FACTS_VERSION, derivedFrom: { plannedDutyId: plannedId, executedDutyId: executedId } } }, { factKey: "duty_extension", subjectType: "DUTY", subjectId: executedId, value: extension, sourceType: "CALCULATED", confidence: "LOW", provenance: { algorithm: "deriveDutyExtensionFacts", algorithmVersion: FLIGHT_FACTS_VERSION, derivedFrom: { plannedDutyId: plannedId, executedDutyId: executedId } } }); }
        }
      }
    }
  }
  if (source.schedule_role === "EXECUTION_SNAPSHOT" || source.schedule_role === "FINAL_EXECUTED") {
    const plannedImport = await supabase.from("flight_schedule_imports").select("id").eq("schedule_month_id", source.schedule_month_id).eq("schedule_role", "PLANNED").maybeSingle();
    if (plannedImport.data) {
      const plannedFactsResult = await supabase.from("flight_fact_records").select("subject_id,value").eq("import_id", plannedImport.data.id).eq("fact_key", "off_period");
      if (plannedFactsResult.error) throw new Error("Não foi possível carregar os períodos OFF planejados.");
      const asOffPeriod = (id: string | null, value: Record<string, unknown>): OffPeriodForMatching | null => typeof id === "string" && typeof value.startDate === "string" && typeof value.endDate === "string" && Array.isArray(value.sourceEventIds) ? { id, startDate: value.startDate, endDate: value.endDate, startAt: typeof value.startAt === "string" ? value.startAt : null, endAt: typeof value.endAt === "string" ? value.endAt : null, sourceEventIds: value.sourceEventIds.map(String) } : null;
      const planned = (plannedFactsResult.data ?? []).flatMap((fact) => { const period = asOffPeriod(fact.subject_id, fact.value as Record<string, unknown>); return period ? [period] : []; });
      const executed = result.facts.filter((fact) => fact.factKey === "off_period").flatMap((fact) => { const period = asOffPeriod(fact.subjectId, fact.value); return period ? [period] : []; });
      const plannedById = new Map(planned.map((period) => [period.id, period]));
      const executedById = new Map(executed.map((period) => [period.id, period]));
      const dutyFacts = result.facts.filter((fact) => fact.factKey === "duty");
      for (const match of matchOffPeriods(planned, executed)) {
        result.facts.push({ factKey: "off_period_match", subjectType: "OFF_PERIOD_MATCH", subjectId: match.executedOffPeriodId, value: { ...match, origin: "UNKNOWN", voluntary: "UNKNOWN", reason: null }, sourceType: "CALCULATED", confidence: match.matchingConfidence, provenance: { algorithm: "matchOffPeriods", algorithmVersion: FLIGHT_FACTS_VERSION, derivedFrom: { plannedOffPeriodId: match.plannedOffPeriodId, executedOffPeriodId: match.executedOffPeriodId, plannedSourceEventIds: match.plannedSourceEventIds, executedSourceEventIds: match.executedSourceEventIds } } });
        const plannedPeriod = match.plannedOffPeriodId ? plannedById.get(match.plannedOffPeriodId) ?? null : null;
        const executedPeriod = executedById.get(match.executedOffPeriodId) ?? null;
        const activityStarts = dutyFacts.map((fact) => typeof fact.value.presentationAt === "string" ? fact.value.presentationAt : null).filter((value): value is string => value !== null);
        const occupied = plannedPeriod?.startAt && plannedPeriod.endAt ? activityStarts.some((start) => Date.parse(start) >= Date.parse(plannedPeriod.startAt!) && Date.parse(start) < Date.parse(plannedPeriod.endAt!)) : null;
        const facts = deriveOffSubstitutionFacts({ matchingStatus: match.matchingStatus, plannedOffPeriodId: match.plannedOffPeriodId, executedOffPeriodId: match.executedOffPeriodId, deltaStartMinutes: match.deltaStartMinutes, deltaEndMinutes: match.deltaEndMinutes, plannedIsSingle: plannedPeriod ? plannedPeriod.startDate === plannedPeriod.endDate : null, executedIsSingle: executedPeriod ? executedPeriod.startDate === executedPeriod.endDate : false, activityOccupiedPlannedOff: occupied });
        result.facts.push({ factKey: "off_substitution", subjectType: "OFF_SUBSTITUTION", subjectId: match.executedOffPeriodId, value: { ...facts, plannedOffPeriodId: match.plannedOffPeriodId, executedOffPeriodId: match.executedOffPeriodId, affectedInterval: { plannedStartAt: match.plannedStartAt, plannedEndAt: match.plannedEndAt, executedStartAt: match.executedStartAt, executedEndAt: match.executedEndAt } }, sourceType: "CALCULATED", confidence: match.matchingStatus === "MATCHED" ? "HIGH" : "LOW", provenance: { algorithm: "deriveOffSubstitutionFacts", algorithmVersion: FLIGHT_FACTS_VERSION, derivedFrom: { plannedOffPeriodId: match.plannedOffPeriodId, executedOffPeriodId: match.executedOffPeriodId } } });
      }
    }
  }
  const validation = validateFactsForPersistence(result.facts);
  if (!validation.valid) throw new Error(`Facts inválidos: ${validation.errors.join(" ")}`);
  const removedFacts = await supabase.from("flight_fact_records").delete().eq("import_id", scheduleImportId);
  if (removedFacts.error) throw new Error(removedFacts.error.message);
  const removedRuns = await supabase.from("flight_fact_runs").delete().eq("import_id", scheduleImportId).eq("engine_version", FLIGHT_FACTS_VERSION);
  if (removedRuns.error) throw new Error(removedRuns.error.message);
  const createdRun = await supabase.from("flight_fact_runs").insert({ import_id: scheduleImportId, engine_version: FLIGHT_FACTS_VERSION, parser_version: source.parser_version, summary: result.summary }).select("id").single();
  if (createdRun.error || !createdRun.data) throw new Error(createdRun.error?.message ?? "Não foi possível criar a execução de facts.");
  const persistedFacts = await supabase.from("flight_fact_records").insert(result.facts.map((fact) => ({ run_id: createdRun.data.id, import_id: scheduleImportId, fact_key: fact.factKey, subject_type: fact.subjectType, subject_id: fact.subjectId, value: fact.value, source_type: fact.sourceType, confidence: fact.confidence, schedule_state: source.schedule_role, fact_engine_version: FLIGHT_FACTS_VERSION, provenance: fact.provenance })));
  if (persistedFacts.error) throw new Error(persistedFacts.error.message);
  return { runId: createdRun.data.id, ...result.summary, factCount: result.facts.length };
}
