import assert from "node:assert/strict";
import test from "node:test";
import { deriveOffSubstitutionFacts } from "./off-substitution-facts";

const base = { matchingStatus: "MATCHED" as const, plannedOffPeriodId: "planned", executedOffPeriodId: "executed", deltaStartMinutes: 0, deltaEndMinutes: 0, plannedIsSingle: false, executedIsSingle: false, activityOccupiedPlannedOff: false };
test("identifies planned off surrendered to flight or deadhead program", () => { assert.equal(deriveOffSubstitutionFacts({ ...base, activityOccupiedPlannedOff: true }).offWasSurrenderedForProgram, "TRUE"); assert.equal(deriveOffSubstitutionFacts({ ...base, activityOccupiedPlannedOff: true }).programSubstitution, "TRUE"); });
test("keeps mere off displacement factual without proving surrender", () => { const facts = deriveOffSubstitutionFacts({ ...base, deltaStartMinutes: 30, activityOccupiedPlannedOff: false }); assert.equal(facts.offWasAffected, "TRUE"); assert.equal(facts.offWasSurrenderedForProgram, "FALSE"); assert.equal(facts.programSubstitution, "UNKNOWN"); });
test("derives generated single only from a matched substituted compound", () => { assert.equal(deriveOffSubstitutionFacts({ ...base, plannedIsSingle: false, executedIsSingle: true, activityOccupiedPlannedOff: true }).generatedSingleOff, "TRUE"); assert.equal(deriveOffSubstitutionFacts({ ...base, plannedIsSingle: true, executedIsSingle: true }).generatedSingleOff, "FALSE"); });
test("preserves unknown matching, boundary deltas and external voluntary context", () => { const unknown = deriveOffSubstitutionFacts({ ...base, matchingStatus: "AMBIGUOUS", activityOccupiedPlannedOff: null }); assert.equal(unknown.offWasAffected, "UNKNOWN"); assert.equal(deriveOffSubstitutionFacts({ ...base, deltaStartMinutes: null, deltaEndMinutes: null }).offWasAffected, "UNKNOWN"); assert.equal(unknown.changeVoluntary, "UNKNOWN"); assert.equal(deriveOffSubstitutionFacts({ ...base, changeVoluntary: "TRUE", changeOrigin: "PORTAL_TRADE" }).changeOrigin, "PORTAL_TRADE"); });
