import { createClient } from "@supabase/supabase-js";
import { consecutiveNightEarlyOccurrences, evaluateAccumulatedLimit, evaluateCghGruAdditionalRest, evaluateConsecutiveSingle, evaluateContractualBase, evaluateDifferentAirportBothRest, evaluateDifferentAirportPostRest, evaluateDifferentAirportPreRest, evaluateEarlyStartClassification, evaluateExceptionalOffDelay, evaluateGroundTime, evaluateInterairportTransportRequirement, evaluateMinimumRestAfterDuty, evaluateMonthlyOff, evaluateNightEarly168hLimit, evaluateNightEarly48hReset, evaluateNightEarlyConsecutiveLimit, evaluateNightOperationClassification, evaluateOffDelay, evaluateRbacBAcclimatizedLimit, evaluateRbacRegimeGate, evaluateRbacAfterTwoNights, evaluateRbacNightReset, evaluateRbacPostFourNights, evaluateReserveAccommodationTrigger, evaluateReserveDuration, evaluateRestTransportDelay, evaluateSingleExceptionAvailability, evaluateSingleNights, evaluateSingleReport, evaluateSingleRolling, evaluateStandbyDuration, evaluateStandbyMonthlyLimit, evaluateStandbyUncalledRest, evaluateThirdConsecutiveNightException, evaluateTimezoneCrossingRestIncrement, evaluateUnknownAcclimatizationReduction, evaluateVirtualBaseStandbyReserveLocation, evaluateVoluntary168hException, evaluateWeekendOff, FLIGHT_RULES_ENGINE_VERSION, isNightOrEarlyOccurrence, type EvaluationStatus, type RuleEvaluation } from "./rules-engine";
import { evaluateRbacAugmentedCrew, evaluateRbacExtension, evaluateRbacInDutyReprogramming, evaluateRbacInterruptedDuty } from "./rules-engine";
import { evaluateDeadheadRule } from "./rules-engine";
import { evaluateResidualRule } from "./rules-engine";

const RULESET_VERSION = "gol-operational-ruleset/2026.1";
const ACT_INSTRUMENT_ID = "a49d8597-8372-4682-9e3b-4f97d4b21944";
const ACT_EFFECTIVE_FROM = "2025-10-01";
const ACT_EFFECTIVE_TO = "2026-09-30";
type ScheduleState = "PLANNED" | "EXECUTION_SNAPSHOT" | "FINAL_EXECUTED";
type Confidence = "HIGH" | "MEDIUM" | "LOW";
type FactValue = Record<string, unknown>;
type RuleFact = { fact_key: string; subject_type: string; subject_id: string | null; value: FactValue; confidence: Confidence };
type RulesContext = { documentContractualBase: string | null; profileContractualBase: string | null; virtualBase: string | null; virtualBaseActive: unknown };

export type PersistedRuleEvaluation = { ruleKey: string; subjectType: string; subjectId: string | null; status: EvaluationStatus; evaluationContext: "NORMAL" | "TRIGGER" | "EXCEPTION"; severity: "INFO" | "MEDIUM" | "HIGH"; confidence: Confidence; factsSnapshot: FactValue; explanation: string; sourceReferences: Array<Record<string, string>> };

function factualMinutes(value: FactValue) { return typeof value.durationMinutes === "number" ? value.durationMinutes : typeof value.minutes === "number" ? value.minutes : null; }
function confidenceFor(facts: RuleFact[]): Confidence { return facts.some((fact) => fact.confidence === "LOW") ? "LOW" : facts.some((fact) => fact.confidence === "MEDIUM") ? "MEDIUM" : "HIGH"; }
function withinActEffectivePeriod(periodStart: string | null) { return periodStart !== null && periodStart >= ACT_EFFECTIVE_FROM && periodStart <= ACT_EFFECTIVE_TO; }
function sourceFor(ruleKey: string) { if (ruleKey.startsWith("RBAC117_")) return [{ instrumentType: "RBAC", instrument: "RBAC 117 EMD 01", section: "Madrugada/Fadiga" }]; const clause = ruleKey === "GOL_VOLUNTARY_168H_EXCEPTION" ? "7.4 §10" : ruleKey === "GOL_VOLUNTARY_TRADE_SINGLE_OFF_EXCEPTION" ? "7.4 §6" : ruleKey === "GOL_MONTHLY_GROUPED_WEEKEND_OFF" ? "6.3" : ruleKey === "GOL_OFF_START_DELAY" || ruleKey === "GOL_OFF_EXCEPTIONAL_START_DELAY" ? "6.4" : ruleKey === "GOL_OFF_MONTH_ATTRIBUTION" ? "6.7" : ruleKey.includes("SINGLE_OFF") || ruleKey.includes("CONSECUTIVE_SINGLE") ? "6.10" : ruleKey.startsWith("GOL_NIGHT_") || ruleKey === "GOL_EARLY_START_CLASSIFICATION" || ruleKey === "GOL_THIRD_CONSECUTIVE_NIGHT_EXCEPTION" ? "5.16" : ruleKey === "GOL_GROUND_TIME_BETWEEN_LEGS" ? "5.15" : ruleKey === "GOL_RESERVE_DURATION" || ruleKey === "GOL_RESERVE_ACCOMMODATION_TRIGGER" ? "5.14" : ruleKey === "GOL_STANDBY_DURATION" ? "5.13" : "7.4 §3"; return [{ instrumentId: ACT_INSTRUMENT_ID, clause }]; }
function packageSixSourceFor(ruleKey: string) { if (ruleKey.startsWith("LAW_")) return [{ instrumentType: "LAW", instrument: "Lei 13.475/2017", section: ruleKey === "LAW_TIMEZONE_CROSSING_REST_INCREMENT" ? "cruzamento de fusos" : "repouso" }]; if (["GOL_CONTRACTUAL_BASE_CLASSIFICATION", "GOL_DIFFERENT_AIRPORT_PRE_REST_INCREMENT", "GOL_DIFFERENT_AIRPORT_POST_REST_INCREMENT", "GOL_DIFFERENT_AIRPORT_BOTH_REST_INCREMENT", "GOL_CGH_GRU_ADDITIONAL_REST", "GOL_INTERAIRPORT_TRANSPORT_REQUIREMENT"].includes(ruleKey)) return [{ instrumentId: ACT_INSTRUMENT_ID, clause: "5.17" }]; if (ruleKey === "GOL_VIRTUAL_BASE_STANDBY_RESERVE_LOCATION") return [{ instrumentId: ACT_INSTRUMENT_ID, clause: "5.19" }]; return sourceFor(ruleKey); }
function severityFor(ruleKey: string): PersistedRuleEvaluation["severity"] { if (["GOL_STANDBY_UNCALLED_REST", "GOL_NIGHT_EARLY_CONSECUTIVE_LIMIT", "GOL_NIGHT_EARLY_168H_LIMIT", "GOL_MONTHLY_OFF_MINIMUM", "GOL_SINGLE_OFF_TWO_LOCAL_NIGHTS", "GOL_SINGLE_OFF_NEXT_REPORT_TIME", "GOL_SINGLE_OFF_ROLLING_30D_LIMIT", "GOL_CONSECUTIVE_SINGLE_OFF_PROHIBITION"].includes(ruleKey)) return "HIGH"; if (ruleKey === "GOL_STANDBY_MONTHLY_LIMIT" || ruleKey === "GOL_MONTHLY_GROUPED_WEEKEND_OFF" || ruleKey === "GOL_OFF_START_DELAY" || ruleKey === "GOL_OFF_EXCEPTIONAL_START_DELAY") return "MEDIUM"; if (ruleKey === "GOL_RESERVE_ACCOMMODATION_TRIGGER" || ruleKey === "GOL_NIGHT_OPERATION_CLASSIFICATION" || ruleKey === "GOL_EARLY_START_CLASSIFICATION" || ruleKey === "GOL_NIGHT_EARLY_48H_RESET" || ruleKey === "GOL_OFF_MONTH_ATTRIBUTION") return "INFO"; return "MEDIUM"; }
function packageSixSeverityFor(ruleKey: string): PersistedRuleEvaluation["severity"] { if (["LAW_MINIMUM_REST_AFTER_DUTY", "GOL_DIFFERENT_AIRPORT_PRE_REST_INCREMENT", "GOL_DIFFERENT_AIRPORT_POST_REST_INCREMENT", "GOL_DIFFERENT_AIRPORT_BOTH_REST_INCREMENT", "GOL_CGH_GRU_ADDITIONAL_REST", "LAW_TIMEZONE_CROSSING_REST_INCREMENT"].includes(ruleKey)) return "HIGH"; if (["LAW_REST_TRANSPORT_DELAY", "GOL_VIRTUAL_BASE_STANDBY_RESERVE_LOCATION"].includes(ruleKey)) return "MEDIUM"; if (["GOL_INTERAIRPORT_TRANSPORT_REQUIREMENT", "GOL_CONTRACTUAL_BASE_CLASSIFICATION"].includes(ruleKey)) return "INFO"; return severityFor(ruleKey); }
function recordFrom(evaluation: RuleEvaluation, fact: RuleFact | null, factsSnapshot: FactValue, confidence: Confidence): PersistedRuleEvaluation { return { ruleKey: evaluation.ruleKey, subjectType: fact?.subject_type ?? "IMPORT", subjectId: fact?.subject_id ?? null, status: evaluation.status, evaluationContext: evaluation.evaluationContext ?? "NORMAL", severity: packageSixSeverityFor(evaluation.ruleKey), confidence, factsSnapshot: { ...factsSnapshot, legalLimit: evaluation.limit, reason: evaluation.explanation }, explanation: evaluation.explanation, sourceReferences: packageSixSourceFor(evaluation.ruleKey) }; }
function nextDutyStart(standbyEnd: string | null, dutyFacts: RuleFact[]) { if (!standbyEnd) return null; return dutyFacts.map((fact) => typeof fact.value.presentationAt === "string" ? fact.value.presentationAt : null).filter((start): start is string => start !== null && Date.parse(start) > Date.parse(standbyEnd)).sort((left, right) => Date.parse(left) - Date.parse(right))[0] ?? null; }
function localMinute(instant: unknown, timezone: unknown) { if (typeof instant !== "string" || typeof timezone !== "string") return null; try { const parts = new Intl.DateTimeFormat("en-GB", { timeZone: timezone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(instant)); const h=Number(parts.find(part=>part.type==="hour")?.value);const m=Number(parts.find(part=>part.type==="minute")?.value);return Number.isInteger(h)&&Number.isInteger(m)?h*60+m:null;}catch{return null;} }

export function buildFlightRuleEvaluations(scheduleState: ScheduleState, facts: RuleFact[], documentPeriodStart = "2026-08-01", context: RulesContext = { documentContractualBase: null, profileContractualBase: null, virtualBase: null, virtualBaseActive: "UNKNOWN" }, importSubjectId?: string): PersistedRuleEvaluation[] {
  const active = withinActEffectivePeriod(documentPeriodStart);
  const standbyFacts = facts.filter((fact) => fact.fact_key === "standby" && fact.value.regime === "REGULAR");
  const dutyFacts = facts.filter((fact) => fact.fact_key === "duty");
  const perFact = facts.flatMap((fact) => {
    if (fact.fact_key === "standby") {
      const duration = evaluateStandbyDuration(factualMinutes(fact.value));
      const uncalled = evaluateStandbyUncalledRest(fact.value.called, typeof fact.value.endAt === "string" ? fact.value.endAt : null, nextDutyStart(typeof fact.value.endAt === "string" ? fact.value.endAt : null, dutyFacts));
      return [recordFrom(duration, fact, fact.value, fact.confidence), recordFrom(uncalled, fact, { ...fact.value, nextActivityStart: nextDutyStart(typeof fact.value.endAt === "string" ? fact.value.endAt : null, dutyFacts) }, fact.confidence)];
    }
    if (fact.fact_key === "reserve") {
      const duration = evaluateReserveDuration(factualMinutes(fact.value));
      const trigger = evaluateReserveAccommodationTrigger(factualMinutes(fact.value), active);
      return [recordFrom(duration, fact, fact.value, fact.confidence), recordFrom(trigger, fact, { ...fact.value, requirementTriggered: factualMinutes(fact.value) === null ? "UNKNOWN" : factualMinutes(fact.value)! > 180, accommodationProvided: "UNKNOWN" }, fact.confidence)];
    }
    if (fact.fact_key === "ground_interval") {
      const classification = fact.value.classification === "DAY" || fact.value.classification === "NIGHT" ? fact.value.classification : null;
      return [recordFrom(evaluateGroundTime(scheduleState, factualMinutes(fact.value), classification), fact, fact.value, fact.confidence)];
    }
    return [];
  });
  const monthly = evaluateStandbyMonthlyLimit(standbyFacts.map((fact) => ({ id: fact.subject_id ?? "unknown", voluntaryTradeContext: fact.value.voluntaryTradeContext, origin: fact.value.origin })), active);
  const orderedDuties = [...dutyFacts].sort((left, right) => String(left.value.presentationAt ?? "").localeCompare(String(right.value.presentationAt ?? "")));
  const occurrenceStates = orderedDuties.map((fact) => isNightOrEarlyOccurrence({ isNightOperation: fact.value.isNightOperation, isEarlyStart: fact.value.isEarlyStart }));
  const withinDocumentConsecutive = consecutiveNightEarlyOccurrences(occurrenceStates);
  const rollingFact = facts.find((fact) => fact.fact_key === "rolling_window" && fact.value.windowType === "night_early_count_168h");
  const historyComplete = rollingFact?.value.historyComplete === true;
  const rollingCount = typeof rollingFact?.value.value === "number" ? rollingFact.value.value : null;
  const resetFact = facts.find((fact) => fact.fact_key === "free_interval_48h");
  const resetValue = resetFact?.value.freeInterval48h ?? resetFact?.value.value ?? "UNKNOWN";
  const thirdDuty = withinDocumentConsecutive !== null && withinDocumentConsecutive > 2 ? orderedDuties.find((fact) => isNightOrEarlyOccurrence({ isNightOperation: fact.value.isNightOperation, isEarlyStart: fact.value.isEarlyStart }) === true) ?? null : null;
  const thirdFacts = { extraService: thirdDuty?.value.extraService ?? "UNKNOWN", returnToContractualBase: thirdDuty?.value.returnToContractualBase ?? "UNKNOWN", endsDuty: thirdDuty?.value.endsDuty ?? "UNKNOWN", noOperatingCrewBeforeThirdOccurrenceInSameDuty: thirdDuty?.value.noOperatingCrewBeforeThirdOccurrenceInSameDuty ?? "UNKNOWN" };
  const thirdException = evaluateThirdConsecutiveNightException(withinDocumentConsecutive !== null && withinDocumentConsecutive > 2, thirdFacts);
  const changeFacts = facts.filter((fact) => fact.fact_key === "schedule_change");
  const voluntaryFacts = { changeVoluntary: changeFacts.every((fact) => fact.value.voluntary === true) && changeFacts.length > 0 ? true : changeFacts.some((fact) => fact.value.voluntary === false) ? false : "UNKNOWN", changeOrigin: changeFacts.length === 1 ? changeFacts[0].value.origin ?? "UNKNOWN" : "UNKNOWN", purpose: "UNKNOWN", operationalDisruption: "UNKNOWN", unplannedNightWindowInserted: "UNKNOWN" };
  const voluntaryException = evaluateVoluntary168hException(rollingCount, voluntaryFacts);
  const regimeFact = facts.find((fact) => fact.fact_key === "operator.rbac117_regime");
  const regime = regimeFact?.value.value ?? "UNKNOWN";
  const rbacAfterTwo = evaluateRbacAfterTwoNights(regime, withinDocumentConsecutive, historyComplete, null, voluntaryFacts.changeVoluntary === true);
  const rbacPostFour = evaluateRbacPostFourNights(regime, null, historyComplete, null);
  const rbacReset = evaluateRbacNightReset(regime, resetValue, null);
  const packageSevenRules: PersistedRuleEvaluation[] = [recordFrom(evaluateRbacRegimeGate(regime), regimeFact ?? null, { regime }, regimeFact?.confidence ?? "LOW")];
  for (const duty of dutyFacts) { const presentation=localMinute(duty.value.presentationAt,duty.value.startTimezone); const crew=duty.value.crewComposition ?? "UNKNOWN"; const acclimatization=duty.value.acclimatizationState ?? "UNKNOWN"; packageSevenRules.push(recordFrom(evaluateRbacBAcclimatizedLimit(regime,crew,acclimatization,presentation,typeof duty.value.operatingLegCount==="number"?duty.value.operatingLegCount:null,factualMinutes(duty.value),typeof duty.value.flightTimeMinutes==="number"?duty.value.flightTimeMinutes:null),duty,duty.value,duty.confidence),recordFrom(evaluateUnknownAcclimatizationReduction(regime,acclimatization,presentation,typeof duty.value.operatingLegCount==="number"?duty.value.operatingLegCount:null),duty,duty.value,duty.confidence)); }
  for(const [windowType,ruleKey,limit] of [["flight_time_28d","RBAC117_FLIGHT_TIME_28D_LIMIT",5400],["flight_time_365d","RBAC117_FLIGHT_TIME_365D_LIMIT",54000],["work_time_7d","RBAC117_WORK_TIME_7D_LIMIT",3600],["work_time_14d","RBAC117_WORK_TIME_14D_LIMIT",6000]] as const){const fact=facts.find(item=>item.fact_key==="rolling_window"&&item.value.windowType===windowType)??null;packageSevenRules.push(recordFrom(evaluateAccumulatedLimit(ruleKey,regime,fact?.value.value,fact?.value.historyComplete,limit),fact,fact?.value??{},fact?.confidence??"LOW"));}
  const work=facts.find(item=>item.fact_key==="work_components")??null; packageSevenRules.push(recordFrom(evaluateAccumulatedLimit("LAW_MONTHLY_WORK_LIMIT",null,work?.value.monthlyWorkMinutes,work?.value.monthlyWorkComplete,10560,false),work,work?.value??{},work?.confidence??"LOW"));
  const trainingFacts = facts.filter((fact) => fact.fact_key === "training");
  for (const training of trainingFacts) packageSevenRules.push(recordFrom(evaluateResidualRule("LAW_GROUND_TRAINING_WORK_TIME_CLASSIFICATION", training.value), training, training.value, training.confidence), recordFrom(evaluateResidualRule("LAW_SIMULATOR_WORK_TIME_CLASSIFICATION", training.value), training, training.value, training.confidence));
  const augmentedByDuty = new Map(facts.filter((fact) => fact.fact_key === "augmented_crew" && fact.subject_id).map((fact) => [fact.subject_id!, fact]));
  const extensionByDuty = new Map(facts.filter((fact) => fact.fact_key === "duty_extension" && fact.subject_id).map((fact) => [fact.subject_id!, fact]));
  const reprogrammingByDuty = new Map(facts.filter((fact) => fact.fact_key === "duty_reprogramming" && fact.subject_id).map((fact) => [fact.subject_id!, fact]));
  const interruptedByDuty = new Map(facts.filter((fact) => fact.fact_key === "interrupted_duty" && fact.subject_id).map((fact) => [fact.subject_id!, fact]));
  const transportByDuty = new Map(facts.filter((fact) => fact.fact_key === "duty_transport" && fact.subject_id).map((fact) => [fact.subject_id!, fact]));
  for (const duty of dutyFacts) {
    const augmented = duty.subject_id ? augmentedByDuty.get(duty.subject_id) ?? null : null;
    const extension = duty.subject_id ? extensionByDuty.get(duty.subject_id) ?? null : null;
    const reprogramming = duty.subject_id ? reprogrammingByDuty.get(duty.subject_id) ?? null : null;
    const interrupted = duty.subject_id ? interruptedByDuty.get(duty.subject_id) ?? null : null;
    const transport = duty.subject_id ? transportByDuty.get(duty.subject_id) ?? null : null;
    const crew = augmented?.value.crewComposition ?? "UNKNOWN";
    const limitsWithin = typeof duty.value.durationMinutes === "number" && typeof duty.value.flightTimeMinutes === "number" ? true : "UNKNOWN";
    packageSevenRules.push(
      recordFrom(evaluateRbacAugmentedCrew(regime, augmented?.value ?? {}, localMinute(duty.value.presentationAt, duty.value.startTimezone), typeof duty.value.durationMinutes === "number" ? duty.value.durationMinutes : null, typeof duty.value.flightTimeMinutes === "number" ? duty.value.flightTimeMinutes : null), augmented ?? duty, { duty: duty.value, augmented: augmented?.value ?? {}, actual: duty.value.durationMinutes ?? null }, confidenceFor([duty, ...(augmented ? [augmented] : [])])),
      recordFrom(evaluateRbacExtension("RBAC117_DUTY_EXTENSION", regime, crew, extension?.value.dutyExtensionMinutes, extension?.value.unexpectedOperationalCircumstance, extension?.value.commanderExtensionDecision), extension ?? duty, extension?.value ?? {}, extension?.confidence ?? "LOW"),
      recordFrom(evaluateRbacExtension("RBAC117_FLIGHT_TIME_EXTENSION", regime, crew, extension?.value.flightTimeExtensionMinutes, extension?.value.unexpectedOperationalCircumstance, extension?.value.commanderExtensionDecision), extension ?? duty, extension?.value ?? {}, extension?.confidence ?? "LOW"),
      recordFrom(evaluateRbacExtension("RBAC117_ADDITIONAL_LEG_EXTENSION", regime, crew, extension?.value.additionalOperatingLegs, extension?.value.unexpectedOperationalCircumstance, extension?.value.commanderExtensionDecision), extension ?? duty, extension?.value ?? {}, extension?.confidence ?? "LOW"),
      recordFrom(evaluateRbacInDutyReprogramming(regime, reprogramming?.value ?? {}, limitsWithin), reprogramming ?? duty, { ...(reprogramming?.value ?? {}), limitsWithin }, reprogramming?.confidence ?? "LOW"),
      recordFrom(evaluateRbacInterruptedDuty(regime, interrupted?.value ?? {}, typeof duty.value.durationMinutes === "number" ? duty.value.durationMinutes : null), interrupted ?? duty, { ...(interrupted?.value ?? {}), dutyMinutes: duty.value.durationMinutes ?? null }, interrupted?.confidence ?? "LOW"),
      ...["LAW_DEADHEAD_WORK_TIME_CLASSIFICATION", "GOL_DEADHEAD_ONLY_DOMESTIC_DUTY_LIMIT", "GOL_POST_SIMULATOR_DEADHEAD_LIMIT", "GOL_PRE_SIMULATOR_DEADHEAD_PROHIBITION", "GOL_DEADHEAD_ONLY_INTERNATIONAL_DUTY_LIMIT", "GOL_DEADHEAD_ONLY_INTERNATIONAL_14H_TRIGGER", "GOL_EXTRA_SERVICE_REST_TRIGGER", "GOL_THIRD_NIGHT_EXTRA_SERVICE_RETURN_EXCEPTION", "GOL_SDU_GROUP_CLASSIFICATION", "GOL_B737_CREW_REST_CLASS3_CLASSIFICATION"].map((ruleKey) => recordFrom(evaluateDeadheadRule(ruleKey, transport?.value ?? {}, typeof duty.value.durationMinutes === "number" ? duty.value.durationMinutes : null), transport ?? duty, { ...(transport?.value ?? {}), dutyMinutes: duty.value.durationMinutes ?? null }, transport?.confidence ?? "LOW")),
    );
  }
  const offFacts = facts.filter((fact) => fact.fact_key === "off_period"); const offMatches = facts.filter((fact) => fact.fact_key === "off_period_match"); const substitutions = facts.filter((fact) => fact.fact_key === "off_substitution"); const rollingSingles = facts.filter((fact) => fact.fact_key === "single_off_count_30d");
  for (const off of offFacts) packageSevenRules.push(recordFrom(evaluateResidualRule("GOL_GROUND_TRAINING_NEXT_ACTIVITY_CLASSIFICATION", off.value), off, off.value, off.confidence));
  const scheduleFact = facts.find((fact) => fact.fact_key === "schedule") ?? null;
  packageSevenRules.push(recordFrom(evaluateResidualRule("GOL_SCHEDULE_PUBLICATION_MINIMUM_NOTICE", { periodStart: documentPeriodStart, publicationAt: scheduleFact?.value.officialPublicationAt ?? null }), scheduleFact, scheduleFact?.value ?? {}, scheduleFact?.confidence ?? "LOW"));
  for (const ruleKey of ["GOL_INSTRUCTOR_DUTY_CLASSIFICATION", "GOL_INSTRUCTOR_POST_TRAINING_LIMIT", "GOL_VACATION_PRE_REST_REQUIREMENT", "GOL_VACATION_INTRUSION_POST_RETURN_REQUIREMENT", "GOL_DIRECTED_SCHEDULE_CLASSIFICATION", "GOL_SAL_CLASSIFICATION", "GOL_PART_TIME_CLASSIFICATION", "RULESET_RESIDUAL_COVERAGE_DIAGNOSTIC"]) packageSevenRules.push(recordFrom(evaluateResidualRule(ruleKey, {}), null, { status: "DOCUMENTARY_ONLY" }, "LOW"));
  const offDays = offFacts.length && offFacts.every((fact) => typeof fact.value.offDayCount === "number") ? offFacts.reduce((total, fact) => total + Number(fact.value.offDayCount), 0) : null; const offVoluntary = substitutions.some((fact) => fact.value.changeVoluntary === "TRUE") ? "TRUE" : substitutions.some((fact) => fact.value.changeVoluntary === "FALSE") ? "FALSE" : "UNKNOWN";
  const weekendOff = offFacts.find((fact) => fact.value.isWeekendGroupedCandidate === true);
  const weekendStartsByNoon = weekendOff ? typeof weekendOff.value.startAt === "string" ? (() => { try { const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "America/Sao_Paulo", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(weekendOff.value.startAt)); const hour = Number(parts.find((part) => part.type === "hour")?.value); const minute = Number(parts.find((part) => part.type === "minute")?.value); return Number.isInteger(hour) && Number.isInteger(minute) ? hour * 60 + minute <= 720 : null; } catch { return null; } })() : null : offFacts.length ? false : null;
  const offRules: PersistedRuleEvaluation[] = [recordFrom(evaluateMonthlyOff(offDays, offVoluntary), null, { offDays, voluntary: offVoluntary }, confidenceFor(offFacts)), recordFrom(evaluateWeekendOff(weekendOff ? true : offFacts.length ? false : null, weekendStartsByNoon), weekendOff ?? null, { offPeriodIds: offFacts.map((fact) => fact.subject_id), startsByNoon: weekendStartsByNoon }, confidenceFor(offFacts))];
  for (const match of offMatches.filter((fact) => fact.value.matchingStatus === "MATCHED" && fact.value.matchingConfidence === "HIGH")) { const exceptional = evaluateExceptionalOffDelay(typeof match.value.deltaStartMinutes === "number" ? match.value.deltaStartMinutes : null, match.value.reason ?? "UNKNOWN"); offRules.push(recordFrom(exceptional, match, match.value, match.confidence), recordFrom(evaluateOffDelay(typeof match.value.deltaStartMinutes === "number" ? match.value.deltaStartMinutes : null, exceptional.status), match, match.value, match.confidence)); }
  for (const off of offFacts.filter((fact) => fact.value.isSingleOff === true)) { const substitution = substitutions.find((fact) => fact.subject_id === off.subject_id); const rolling = rollingSingles.find((fact) => fact.subject_id === off.subject_id); const nextActivityStart = typeof off.value.nextActivityStartAt === "string" ? off.value.nextActivityStartAt : null; const nextActivityTimezone = typeof off.value.nextActivityTimezone === "string" ? off.value.nextActivityTimezone : null; const normalReport = evaluateSingleReport(off.value.nextActivityType, nextActivityStart, nextActivityTimezone, "FAIL"); const normalConsecutive = evaluateConsecutiveSingle(off.value.isConsecutiveSingleOff, documentPeriodStart, "FAIL"); const normalRolling = evaluateSingleRolling(rolling?.value.value, rolling?.value.historyComplete, documentPeriodStart, "FAIL"); const normalStatuses = [normalReport.status, normalConsecutive.status, normalRolling.status]; const exceptionNeeded = normalStatuses.includes("FAIL") ? true : normalStatuses.includes("UNKNOWN") ? null : false; const exception = evaluateSingleExceptionAvailability(substitution?.value.changeVoluntary ?? "UNKNOWN", substitution?.value.programSubstitution ?? "UNKNOWN", substitution?.value.generatedSingleOff ?? "UNKNOWN", exceptionNeeded); offRules.push(recordFrom(exception.evaluation, off, { ...(substitution?.value ?? {}), exceptionNeeded }, substitution?.confidence ?? "LOW"), recordFrom(evaluateSingleNights(off.value.localNightsCount), off, off.value, off.confidence), recordFrom(evaluateSingleReport(off.value.nextActivityType, nextActivityStart, nextActivityTimezone, exception.compositionStatus), off, off.value, off.confidence), recordFrom(evaluateConsecutiveSingle(off.value.isConsecutiveSingleOff, documentPeriodStart, exception.compositionStatus), off, off.value, off.confidence), recordFrom(evaluateSingleRolling(rolling?.value.value, rolling?.value.historyComplete, documentPeriodStart, exception.compositionStatus), rolling ?? off, rolling?.value ?? {}, rolling?.confidence ?? "LOW"), recordFrom({ ruleKey: "GOL_OFF_MONTH_ATTRIBUTION", status: typeof off.value.monthAttribution === "string" ? "PASS" : "UNKNOWN", limit: "mês de início", fact: null, explanation: "Atribuição mensal factual do período OFF." }, off, off.value, off.confidence)); }
  const restFacts = facts.filter((fact) => fact.fact_key === "rest_interval");
  const dutiesById = new Map(dutyFacts.flatMap((fact) => fact.subject_id ? [[fact.subject_id, fact] as const] : []));
  const baseClassification = evaluateContractualBase(context.documentContractualBase, context.profileContractualBase);
  const contractualBase = baseClassification.status === "PASS" ? context.documentContractualBase : null;
  const restRules: PersistedRuleEvaluation[] = [recordFrom(baseClassification, null, { documentContractualBase: context.documentContractualBase, profileContractualBase: context.profileContractualBase }, context.profileContractualBase ? "HIGH" : "LOW")];
  for (const rest of restFacts) {
    const previousDuty = typeof rest.value.previousDutyId === "string" ? dutiesById.get(rest.value.previousDutyId) ?? null : null;
    const nextDuty = typeof rest.value.nextDutyId === "string" ? dutiesById.get(rest.value.nextDutyId) ?? null : null;
    const restMinutes = factualMinutes(rest.value);
    const previousEndAirport = previousDuty?.value.endAirport ?? null;
    const nextStartAirport = nextDuty?.value.startAirport ?? null;
    const transportAvailableAt = typeof rest.value.transportAvailableAt === "string" ? rest.value.transportAvailableAt : null;
    const timezoneCount = typeof rest.value.timezonesCrossed === "number" ? rest.value.timezonesCrossed : null;
    const returnedToBase = rest.value.returnedToContractualBase ?? "UNKNOWN";
    restRules.push(
      recordFrom(evaluateMinimumRestAfterDuty(factualMinutes(previousDuty?.value ?? {}), restMinutes), rest, { previousDuty: previousDuty?.value ?? null, rest: rest.value }, confidenceFor([rest, ...(previousDuty ? [previousDuty] : [])])),
      recordFrom(evaluateDifferentAirportPreRest(nextStartAirport, contractualBase), rest, { contractualBase, nextStartAirport, nextDutyId: rest.value.nextDutyId ?? null, requiredIncrementMinutes: 60 }, confidenceFor([rest, ...(nextDuty ? [nextDuty] : [])])),
      recordFrom(evaluateDifferentAirportPostRest(previousEndAirport, contractualBase), rest, { contractualBase, previousEndAirport, previousDutyId: rest.value.previousDutyId ?? null, requiredIncrementMinutes: 60 }, confidenceFor([rest, ...(previousDuty ? [previousDuty] : [])])),
      recordFrom(evaluateDifferentAirportBothRest(previousEndAirport, nextStartAirport, contractualBase), rest, { contractualBase, previousEndAirport, nextStartAirport, requiredIncrementMinutes: 120 }, confidenceFor([rest, ...(previousDuty ? [previousDuty] : []), ...(nextDuty ? [nextDuty] : [])])),
      recordFrom(evaluateCghGruAdditionalRest(documentPeriodStart || null, context.documentContractualBase, [previousEndAirport, nextStartAirport], "UNKNOWN", "UNKNOWN"), rest, { contractualBase: context.documentContractualBase, previousEndAirport, nextStartAirport, changeVoluntary: "UNKNOWN", changeOrigin: "UNKNOWN", requiredIncrementMinutes: 60 }, rest.confidence),
      recordFrom(evaluateTimezoneCrossingRestIncrement(timezoneCount, returnedToBase), rest, { timezoneCount, returnedToBase }, rest.confidence),
      recordFrom(evaluateRestTransportDelay(typeof rest.value.startAt === "string" ? rest.value.startAt : null, transportAvailableAt), rest, { dutyEnd: rest.value.startAt ?? null, transportAvailableAt, effectiveRestStart: transportAvailableAt }, rest.confidence),
    );
  }
  for (const duty of dutyFacts) restRules.push(recordFrom(evaluateInterairportTransportRequirement(contractualBase, duty.value.startAirport, duty.value.endAirport), duty, { contractualBase, startAirport: duty.value.startAirport ?? null, endAirport: duty.value.endAirport ?? null, transportProvided: "UNKNOWN" }, duty.confidence));
  for (const event of facts.filter((fact) => fact.fact_key === "standby" || fact.fact_key === "reserve")) restRules.push(recordFrom(evaluateVirtualBaseStandbyReserveLocation(context.virtualBaseActive, context.virtualBase, event.value.location, event.value.assignedProgramStartAirport ?? null), event, { virtualBaseActive: context.virtualBaseActive, virtualBase: context.virtualBase, location: event.value.location ?? null, assignedProgramStartAirport: event.value.assignedProgramStartAirport ?? null }, event.confidence));
  const classifications = orderedDuties.flatMap((fact) => [recordFrom(evaluateNightOperationClassification(fact.value.isNightOperation), fact, fact.value, fact.confidence), recordFrom(evaluateEarlyStartClassification(fact.value.isEarlyStart), fact, fact.value, fact.confidence)]);
  const consecutive = recordFrom(evaluateNightEarlyConsecutiveLimit(withinDocumentConsecutive, historyComplete, thirdException.status), null, { occurrences: occurrenceStates, withinDocumentConsecutive, historyComplete, exceptionStatus: thirdException.status }, confidenceFor([...dutyFacts, ...(rollingFact ? [rollingFact] : [])]));
  const rolling = recordFrom(evaluateNightEarly168hLimit(rollingCount, historyComplete, voluntaryException.status), rollingFact ?? null, { ...(rollingFact?.value ?? { count: null, historyComplete: false }), exceptionStatus: voluntaryException.status }, rollingFact?.confidence ?? "LOW");
  const reset = recordFrom(evaluateNightEarly48hReset(resetValue), resetFact ?? null, resetFact?.value ?? { freeInterval48h: "UNKNOWN" }, resetFact?.confidence ?? "LOW");
  return [...perFact, ...offRules, ...restRules, ...packageSevenRules, recordFrom(monthly, null, { monthlyCount: standbyFacts.length, standbyIds: standbyFacts.map((fact) => fact.subject_id), voluntaryOrigin: standbyFacts.map((fact) => ({ id: fact.subject_id, voluntary: fact.value.voluntaryTradeContext ?? "UNKNOWN", origin: fact.value.origin ?? "UNKNOWN" })), limit: 8 }, confidenceFor(standbyFacts)), ...classifications, recordFrom(thirdException, thirdDuty, { thirdConsecutiveOccurrence: withinDocumentConsecutive !== null && withinDocumentConsecutive > 2, ...thirdFacts }, thirdDuty?.confidence ?? "LOW"), consecutive, recordFrom(voluntaryException, null, { normalCount: rollingCount, ...voluntaryFacts }, confidenceFor(changeFacts)), rolling, reset, recordFrom(rbacAfterTwo, null, { regime, reason: regime === "UNKNOWN" ? "OPERATOR_RBAC117_REGIME_UNKNOWN" : null }, regimeFact?.confidence ?? "LOW"), recordFrom(rbacPostFour, null, { regime, reason: regime === "UNKNOWN" ? "OPERATOR_RBAC117_REGIME_UNKNOWN" : null }, regimeFact?.confidence ?? "LOW"), recordFrom(rbacReset, null, { regime, freeInterval48h: resetValue, localNights: "UNKNOWN", reason: regime === "UNKNOWN" ? "OPERATOR_RBAC117_REGIME_UNKNOWN" : null }, regimeFact?.confidence ?? "LOW")].map((evaluation) => evaluation.subjectId === null && importSubjectId ? { ...evaluation, subjectType: "IMPORT", subjectId: importSubjectId } : evaluation);
}

export async function evaluateFlightRules(scheduleImportId: string, ownerUserId?: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceRoleKey) throw new Error("As credenciais de servidor do Supabase não foram configuradas.");
  const supabase = createClient(url, serviceRoleKey, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } });
  const imported = await supabase.from("flight_schedule_imports").select("id,user_id,schedule_role,document_period_start,home_base").eq("id", scheduleImportId).maybeSingle();
  const source = imported.data as { id: string; user_id: string; schedule_role: ScheduleState; document_period_start: string | null; home_base: string | null } | null;
  if (imported.error || !source || (ownerUserId && source.user_id !== ownerUserId)) throw new Error("Importação de escala não encontrada.");
  const [factsResult, profileResult] = await Promise.all([
    supabase.from("flight_fact_records").select("fact_key,subject_type,subject_id,value,confidence").eq("import_id", scheduleImportId).in("fact_key", ["schedule", "training", "standby", "reserve", "ground_interval", "rest_interval", "duty", "rolling_window", "work_components", "free_interval_48h", "schedule_change", "operator.rbac117_regime", "off_period", "off_period_match", "off_substitution", "single_off_count_30d", "augmented_crew", "duty_extension", "duty_reprogramming", "interrupted_duty", "duty_transport"]),
    supabase.from("flight_legal_profile_facts").select("document_contractual_base,profile_contractual_base,virtual_base,virtual_base_active").eq("user_id", source.user_id).order("updated_at", { ascending: false }).limit(1).maybeSingle(),
  ]);
  if (factsResult.error) throw new Error("Não foi possível carregar os fatos da escala.");
  if (profileResult.error) throw new Error(profileResult.error.message);
  const profile = profileResult.data as { document_contractual_base: string | null; profile_contractual_base: string | null; virtual_base: string | null; virtual_base_active: string | null } | null;
  const evaluations = buildFlightRuleEvaluations(source.schedule_role, (factsResult.data ?? []) as unknown as RuleFact[], source.document_period_start ?? "", { documentContractualBase: profile?.document_contractual_base ?? source.home_base, profileContractualBase: profile?.profile_contractual_base ?? null, virtualBase: profile?.virtual_base ?? null, virtualBaseActive: profile?.virtual_base_active ?? "UNKNOWN" }, source.id);
  const removed = await supabase.from("flight_rule_evaluations").delete().eq("schedule_import_id", scheduleImportId);
  if (removed.error) throw new Error(removed.error.message);
  if (evaluations.length) {
    const inserted = await supabase.from("flight_rule_evaluations").insert(evaluations.map((evaluation) => ({ schedule_import_id: source.id, rule_key: evaluation.ruleKey, rule_version: 1, rules_engine_version: FLIGHT_RULES_ENGINE_VERSION, ruleset_version: RULESET_VERSION, schedule_state: source.schedule_role, subject_type: evaluation.subjectType, subject_id: evaluation.subjectId, evaluation_status: evaluation.status, evaluation_context: evaluation.evaluationContext, severity: evaluation.severity, confidence: evaluation.confidence, facts_snapshot: evaluation.factsSnapshot, explanation: evaluation.explanation, source_references: evaluation.sourceReferences })));
    if (inserted.error) throw new Error(inserted.error.message);
  }
  const counts = evaluations.reduce<Record<EvaluationStatus, number>>((result, evaluation) => { result[evaluation.status] += 1; return result; }, { PASS: 0, FAIL: 0, UNKNOWN: 0, NOT_APPLICABLE: 0 });
  return { importId: source.id, rulesEngineVersion: FLIGHT_RULES_ENGINE_VERSION, rulesetVersion: RULESET_VERSION, evaluationCount: evaluations.length, counts };
}
