import type { ParsedDuty, ParsedLeg } from "./flight-structure-parser";
import type { ExtractedPdfDocument, PdfTextItem } from "@/modules/finance/invoice-import/types";

export type InternationalDiemRateGroup = "SOUTH_AMERICA" | "PUJ" | "CCS" | "CARIBBEAN_OTHER" | "NORTH_AMERICA" | "MEXICO" | "EUROPE" | "UNITED_KINGDOM" | "OTHER_COUNTRIES";
export type Airport = { iata: string; timezone: string; country: string; city: string; internationalDiemRateGroup?: InternationalDiemRateGroup };
export const flightAirports: Airport[] = [
  { iata: "NAT", timezone: "America/Fortaleza", country: "BR", city: "Natal" },
  { iata: "BSB", timezone: "America/Sao_Paulo", country: "BR", city: "Brasília" }, { iata: "CGH", timezone: "America/Sao_Paulo", country: "BR", city: "São Paulo" }, { iata: "GRU", timezone: "America/Sao_Paulo", country: "BR", city: "São Paulo" }, { iata: "GIG", timezone: "America/Sao_Paulo", country: "BR", city: "Rio de Janeiro" }, { iata: "SDU", timezone: "America/Sao_Paulo", country: "BR", city: "Rio de Janeiro" }, { iata: "POA", timezone: "America/Sao_Paulo", country: "BR", city: "Porto Alegre" }, { iata: "IGU", timezone: "America/Sao_Paulo", country: "BR", city: "Foz do Iguaçu" }, { iata: "VIX", timezone: "America/Sao_Paulo", country: "BR", city: "Vitória" },
  { iata: "RBR", timezone: "America/Rio_Branco", country: "BR", city: "Rio Branco" }, { iata: "CZS", timezone: "America/Rio_Branco", country: "BR", city: "Cruzeiro do Sul" }, { iata: "MAO", timezone: "America/Manaus", country: "BR", city: "Manaus" }, { iata: "MIA", timezone: "America/New_York", country: "US", city: "Miami", internationalDiemRateGroup: "NORTH_AMERICA" }, { iata: "MCO", timezone: "America/New_York", country: "US", city: "Orlando", internationalDiemRateGroup: "NORTH_AMERICA" }, { iata: "SSA", timezone: "America/Bahia", country: "BR", city: "Salvador" }, { iata: "MCZ", timezone: "America/Maceio", country: "BR", city: "Maceió" }, { iata: "REC", timezone: "America/Recife", country: "BR", city: "Recife" }, { iata: "BEL", timezone: "America/Belem", country: "BR", city: "Belém" }, { iata: "MCP", timezone: "America/Belem", country: "BR", city: "Macapá" },
  { iata: "PUJ", timezone: "America/Santo_Domingo", country: "DO", city: "Punta Cana", internationalDiemRateGroup: "PUJ" }, { iata: "CCS", timezone: "America/Caracas", country: "VE", city: "Caracas", internationalDiemRateGroup: "CCS" }, { iata: "LHR", timezone: "Europe/London", country: "GB", city: "London", internationalDiemRateGroup: "UNITED_KINGDOM" }, { iata: "CDG", timezone: "Europe/Paris", country: "FR", city: "Paris", internationalDiemRateGroup: "EUROPE" }, { iata: "EZE", timezone: "America/Argentina/Buenos_Aires", country: "AR", city: "Buenos Aires", internationalDiemRateGroup: "SOUTH_AMERICA" }, { iata: "MEX", timezone: "America/Mexico_City", country: "MX", city: "Mexico City", internationalDiemRateGroup: "MEXICO" },
];
const airportTimezones = new Map(flightAirports.map(airport => [airport.iata, airport.timezone]));
export const minutes = (value: string | null | undefined) => { if (!value || !/^\d{1,3}:\d{2}$/.test(value)) return null; const [hours, mins] = value.split(":").map(Number); return hours * 60 + mins; };
export const displayMinutes = (value: number | null) => value === null ? null : `${Math.floor(value / 60).toString().padStart(2, "0")}:${(value % 60).toString().padStart(2, "0")}`;
function localParts(timestamp: number, timeZone: string) { const values = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" }).formatToParts(new Date(timestamp)); const part = (type: string) => Number(values.find(value => value.type === type)?.value); return { year: part("year"), month: part("month"), day: part("day"), hour: part("hour"), minute: part("minute"), second: part("second") }; }
export function localAtUtc(date: string, time: string, timeZone: string) { const [year, month, day] = date.split("-").map(Number); const [hour, minute] = time.split(":").map(Number); const desired = Date.UTC(year, month - 1, day, hour, minute); let result = desired; for (let step = 0; step < 2; step += 1) { const actual = localParts(result, timeZone); result += desired - Date.UTC(actual.year, actual.month - 1, actual.day, actual.hour, actual.minute, actual.second); } return new Date(result).toISOString(); }
export type ParsedTimeMetric = { dutySequence: number | null; scheduleDate: string; officialFlightTimeMinutes: number | null; officialFlightTimeRaw: string | null; officialDutyTimeMinutes: number | null; officialDutyTimeRaw: string | null; officialRestMinutes: number | null; officialRestRaw: string | null; reason: string | null };
export type ParsedAccumulator = { scheduleDate: string; valueMinutes: number; rawValue: string; rawText: string };
export type ParsedFooter = { flightTimeMinutes: number | null; dutyTimeMinutes: number | null; offDays: number | null; offClaim: number | null };
function sameBaseline(item: PdfTextItem, y: number) { return Math.abs(item.y - y) <= 3; }
function valueFor(items: PdfTextItem[], label: PdfTextItem) { const value = items.filter(item => sameBaseline(item, label.y) && item.x > label.x && item.x - label.x < 55).map(item => item.text.match(/^(\d{1,3}:\d{2})\]$/)?.[1]).find((item): item is string => Boolean(item)); return value ?? null; }
export function parseSpatialDutyMetrics(document: ExtractedPdfDocument, duties: ParsedDuty[]) {
  const result = new Map<number, Pick<ParsedTimeMetric, 'officialFlightTimeMinutes'|'officialFlightTimeRaw'|'officialDutyTimeMinutes'|'officialDutyTimeRaw'|'officialRestMinutes'|'officialRestRaw'>>();
  for (const page of document.pages) {
    const closings = page.items.filter(item => item.text === 'C/O');
    for (const closing of closings) {
      const row = page.items.filter(item => sameBaseline(item, closing.y)).map(item => item.text).join(' ');
      const duty = duties.find(candidate => !result.has(candidate.sequence) && candidate.checkOutAirport && candidate.checkOutTimeLocal && row.includes(candidate.checkOutAirport) && row.includes(candidate.checkOutTimeLocal.replace(':', '')));
      if (!duty) continue;
      const zone = Math.floor(closing.x / 267); const left = zone * 267;
      const labels = page.items.filter(item => item.x >= left + 225 && item.x < left + 265 && item.y >= closing.y - 3 && item.y <= closing.y + 16);
      const metric: Pick<ParsedTimeMetric, 'officialFlightTimeMinutes'|'officialFlightTimeRaw'|'officialDutyTimeMinutes'|'officialDutyTimeRaw'|'officialRestMinutes'|'officialRestRaw'> = { officialFlightTimeMinutes: null, officialFlightTimeRaw: null, officialDutyTimeMinutes: null, officialDutyTimeRaw: null, officialRestMinutes: null, officialRestRaw: null };
      for (const label of labels) { const value = valueFor(page.items, label); if (!value) continue; if (label.text === '[FT') { metric.officialFlightTimeRaw = value; metric.officialFlightTimeMinutes = minutes(value); } if (label.text === '[DT') { metric.officialDutyTimeRaw = value; metric.officialDutyTimeMinutes = minutes(value); } if (label.text === '[RT') { metric.officialRestRaw = value; metric.officialRestMinutes = minutes(value); } }
      if (!result.has(duty.sequence) && (metric.officialFlightTimeMinutes !== null || metric.officialDutyTimeMinutes !== null || metric.officialRestMinutes !== null)) result.set(duty.sequence, metric);
    }
  }
  return result;
}
export function parseSpatialDocumentaryMetrics(document: ExtractedPdfDocument, days: Array<{ scheduleDate: string; rawText: string }>) {
  const result: ParsedTimeMetric[] = [];
  for (const day of days) {
    if (/\bC\/[IO]\b/.test(day.rawText)) continue;
    const flight = day.rawText.match(/DH\/G3\s+(\d+)/)?.[1]; if (!flight) continue;
    let found: ParsedTimeMetric | null = null;
    for (const page of document.pages) {
      const dh = page.items.find(item => item.text === 'DH/G3' && page.items.some(candidate => sameBaseline(candidate, item.y) && candidate.text === flight));
      if (!dh) continue;
      const left = Math.floor(dh.x / 267) * 267;
      const labels = page.items.filter(item => item.x >= left + 225 && item.x < left + 265 && item.y >= dh.y - 3 && item.y <= dh.y + 16);
      const metric: ParsedTimeMetric = { dutySequence: null, scheduleDate: day.scheduleDate, officialFlightTimeMinutes: null, officialFlightTimeRaw: null, officialDutyTimeMinutes: null, officialDutyTimeRaw: null, officialRestMinutes: null, officialRestRaw: null, reason: 'NO_DOCUMENT_CI_CO' };
      for (const label of labels) { const value = valueFor(page.items, label); if (!value) continue; if (label.text === '[FT') { metric.officialFlightTimeRaw = value; metric.officialFlightTimeMinutes = minutes(value); } if (label.text === '[DT') { metric.officialDutyTimeRaw = value; metric.officialDutyTimeMinutes = minutes(value); } if (label.text === '[RT') { metric.officialRestRaw = value; metric.officialRestMinutes = minutes(value); } }
      if (metric.officialFlightTimeMinutes !== null || metric.officialDutyTimeMinutes !== null || metric.officialRestMinutes !== null) found = metric;
      break;
    }
    if (found) result.push(found);
  }
  return result;
}
export function parseTimeMetrics(days: Array<{ scheduleDate: string; rawText: string }>, duties: ParsedDuty[]) { const byStart = new Map(duties.map(duty => [duty.startDate, duty])); const values: ParsedTimeMetric[] = []; const accumulators: ParsedAccumulator[] = []; for (const day of days) { let active = byStart.get(day.scheduleDate)?.sequence ?? null; let last: number | null = null; let documentary: ParsedTimeMetric | null = null; for (const raw of day.rawText.split(/\r?\n/)) { const line = raw.trim(); if (/\bC\/I\b/.test(line)) active = byStart.get(day.scheduleDate)?.sequence ?? active; if (/\bC\/O\b/.test(line)) { last = active; active = null; } const rolling = line.match(/\[FT\s+28\s+days\s+(\d{1,3}:\d{2})\]/i); if (rolling) { const value = minutes(rolling[1]); if (value !== null) accumulators.push({ scheduleDate: day.scheduleDate, valueMinutes: value, rawValue: rolling[1], rawText: line }); continue; } const ft = line.match(/\[FT\s+(\d{1,3}:\d{2})\]/i)?.[1] ?? null; const dt = line.match(/\[DT\s+(\d{1,3}:\d{2})\]/i)?.[1] ?? null; const rt = line.match(/\[RT\s+(\d{1,3}:\d{2})\]/i)?.[1] ?? null; if (!ft && !dt && !rt) continue; const sequence = active ?? last; const target = sequence === null ? (documentary ??= { dutySequence: null, scheduleDate: day.scheduleDate, officialFlightTimeMinutes: null, officialFlightTimeRaw: null, officialDutyTimeMinutes: null, officialDutyTimeRaw: null, officialRestMinutes: null, officialRestRaw: null, reason: "NO_DOCUMENT_CI_CO" }) : (values.find(value => value.dutySequence === sequence) ?? (() => { const value = { dutySequence: sequence, scheduleDate: day.scheduleDate, officialFlightTimeMinutes: null, officialFlightTimeRaw: null, officialDutyTimeMinutes: null, officialDutyTimeRaw: null, officialRestMinutes: null, officialRestRaw: null, reason: null }; values.push(value); return value; })()); if (ft) { target.officialFlightTimeRaw = ft; target.officialFlightTimeMinutes = minutes(ft); } if (dt) { target.officialDutyTimeRaw = dt; target.officialDutyTimeMinutes = minutes(dt); } if (rt) { target.officialRestRaw = rt; target.officialRestMinutes = minutes(rt); } } if (documentary) values.push(documentary); } return { metrics: values, accumulators }; }
export function parseFooter(text: string): ParsedFooter { const flight = text.match(/Flight\s+time\s+(\d{1,3}:\d{2})/i)?.[1] ?? null; const duty = text.match(/Duty\s+time\s+(\d{1,3}:\d{2})/i)?.[1] ?? null; const offDays = text.match(/Off\s+days\s+(\d+)/i)?.[1] ?? null; const offClaim = text.match(/Off\s+claim\s+(\d+)/i)?.[1] ?? null; return { flightTimeMinutes: minutes(flight), dutyTimeMinutes: minutes(duty), offDays: offDays ? Number(offDays) : null, offClaim: offClaim ? Number(offClaim) : null }; }
export function calculateStructure(legs: ParsedLeg[], duties: ParsedDuty[]) { const calculatedLegs = legs.map(leg => { const departureTimezone = airportTimezones.get(leg.origin); const arrivalTimezone = airportTimezones.get(leg.destination); if (!departureTimezone || !arrivalTimezone) return { sequence: leg.sequence, departureAtUtc: null, arrivalAtUtc: null, durationMinutes: null, timezoneMissing: !departureTimezone ? leg.origin : leg.destination }; const departureAtUtc = localAtUtc(leg.departureDate, leg.departureTimeLocal, departureTimezone); const arrivalAtUtc = localAtUtc(leg.arrivalDate, leg.arrivalTimeLocal, arrivalTimezone); const durationMinutes = Math.round((Date.parse(arrivalAtUtc) - Date.parse(departureAtUtc)) / 60000); return { sequence: leg.sequence, departureAtUtc, arrivalAtUtc, durationMinutes, timezoneMissing: null }; }); const calculatedDuties = duties.map(duty => { if (!duty.endDate || !duty.checkInAirport || !duty.checkOutAirport || !duty.checkInTimeLocal || !duty.checkOutTimeLocal) return { sequence: duty.sequence, durationMinutes: null }; const startZone = airportTimezones.get(duty.checkInAirport); const endZone = airportTimezones.get(duty.checkOutAirport); if (!startZone || !endZone) return { sequence: duty.sequence, durationMinutes: null }; return { sequence: duty.sequence, durationMinutes: Math.round((Date.parse(localAtUtc(duty.endDate, duty.checkOutTimeLocal, endZone)) - Date.parse(localAtUtc(duty.startDate, duty.checkInTimeLocal, startZone))) / 60000) }; }); return { calculatedLegs, calculatedDuties }; }
