import { FlightShell } from "@/components/flight/flight-shell";
import { ScheduleMonthView } from "@/components/flight/schedule-month-view";
import { FlightFactsDiagnostics, type FlightFactsDiagnostic } from "@/components/flight/flight-facts-diagnostics";
import { RulesEngineDiagnostics, type RulesEngineDiagnostic } from "@/components/flight/rules-engine-diagnostics";
import { FinancialUnitsDiagnostics, type FinancialUnitsDiagnostic } from "@/components/flight/financial-units-diagnostics";
import { FinancialSpecialTimeDiagnostics, type FinancialSpecialTimeDiagnostic } from "@/components/flight/financial-special-time-diagnostics";
import { FinancialEntitlementsDiagnostics, type FinancialEntitlementDiagnostic } from "@/components/flight/financial-entitlements-diagnostics";
import { FinancialGuaranteeDiagnostics, type FinancialGuaranteeDiagnostic } from "@/components/flight/financial-guarantee-diagnostics";
import { FinancialClosureDiagnostics, type FinancialClosureDiagnostic } from "@/components/flight/financial-closure-diagnostics";
import { PayrollStatement } from "@/components/flight/payroll-statement";
import { FlightMonthOverview } from "@/components/flight/flight-month-overview";
import { throwSupabaseError } from "@/lib/errors";
import { getFlightShellData, requireFlightAccess } from "@/modules/flight/access";
import { deriveEvaluationSemantics, summarizeCompliance } from "@/modules/flight/evaluation-semantics";
import type { FlightScheduleImport } from "@/modules/flight/types";

export const dynamic = "force-dynamic";

export default async function FlightSchedulePage() {
  const access = await requireFlightAccess();
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const [shellData, monthResult] = await Promise.all([
    getFlightShellData(access),
    access.supabase.from("flight_schedule_months").select("id,planned_import_id,current_execution_import_id")
      .eq("user_id", access.user.id).eq("year", year).eq("month", month).maybeSingle(),
  ]);
  if (monthResult.error) throwSupabaseError(monthResult.error, "carregar mês operacional", "Não foi possível carregar o mês operacional.");
  const ids = [monthResult.data?.planned_import_id, monthResult.data?.current_execution_import_id].filter((id): id is string => typeof id === "string");
  const importsResult = monthResult.data ? await access.supabase.from("flight_schedule_imports")
    .select("id,schedule_role,snapshot_number,original_filename,file_size,uploaded_at,status,parser_version,document_type,crew_id,crew_name,home_base,document_period_start,document_period_end,document_generated_at,processing_warnings,official_month_flight_time_minutes,official_month_duty_time_minutes,official_off_days")
    .eq("schedule_month_id", monthResult.data.id)
    .order("uploaded_at", { ascending: false }) : { data: [], error: null };
  if (importsResult.error) throwSupabaseError(importsResult.error, "carregar importações de escala", "Não foi possível carregar as escalas importadas.");
  const imports = (importsResult.data ?? []) as FlightScheduleImport[];
  const [eventsResult, legendsResult, daysResult, factRunsResult, factRecordsResult, ruleEvaluationsResult, financialFactsResult, financialSegmentsResult, financialEntitlementsResult, financialGuaranteesResult, financialClosuresResult] = ids.length ? await Promise.all([
    access.supabase.from("flight_schedule_events").select("import_id,schedule_day_id,event_type,event_code,event_label,start_time_local,end_time_local,location_airport,raw_text,raw_metadata").in("import_id", ids),
    access.supabase.from("flight_schedule_legends").select("import_id,code,description").in("import_id", ids),
    access.supabase.from("flight_schedule_days").select("id,import_id,schedule_date,raw_text").in("import_id", ids).order("schedule_date"),
    access.supabase.from("flight_fact_runs").select("id,import_id,summary").in("import_id", ids),
    access.supabase.from("flight_fact_records").select("run_id,fact_key,value,confidence").in("import_id", ids),
    access.supabase.from("flight_rule_evaluations").select("schedule_import_id,rule_key,rule_version,ruleset_version,subject_type,subject_id,evaluation_status,evaluation_context,severity,confidence,explanation,facts_snapshot,source_references").in("schedule_import_id", ids),
    access.supabase.from("flight_financial_facts").select("import_id,financial_fact_type,actual_seconds,normal_operating_candidate_seconds,deadhead_candidate_seconds,standby_equivalent_numerator_seconds,standby_equivalent_denominator,reserve_candidate_seconds,special_time_pending_seconds").in("import_id", ids),
    access.supabase.from("flight_financial_segments").select("import_id,activity_type,duration_seconds,is_night,is_sunday,holiday_status,night_equivalent_numerator_seconds").in("import_id", ids),
    access.supabase.from("flight_financial_entitlements").select("import_id,entitlement_type,entitlement_date,eligibility_status,currency,amount_minor_units,location,reason").in("import_id", ids),
    access.supabase.from("flight_financial_guarantee_decisions").select("executed_import_id,financial_component,planned_quantity,executed_quantity,quantity_unit,decision,reason,voluntary_status,confidence").in("executed_import_id", ids),
    access.supabase.from("flight_financial_monthly_closures").select("id,year,month,known_total_brl,final_total_brl,final_total_status,flight_financial_monthly_lines(component_type,amount_minor_units,calculation_status,reason,source_import)").in("executed_import_id", ids),
  ]) : [{ data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }, { data: [], error: null }];
  if (eventsResult.error || legendsResult.error || daysResult.error || financialEntitlementsResult.error || financialGuaranteesResult.error || financialClosuresResult.error) throwSupabaseError(eventsResult.error ?? legendsResult.error ?? daysResult.error ?? financialEntitlementsResult.error ?? financialGuaranteesResult.error ?? financialClosuresResult.error!, "carregar diagnóstico de atividades", "Não foi possível carregar as atividades da escala.");
  const activityData = ids.reduce<Record<string, { counts: Record<string, number>; codes: Record<string, number>; legends: Array<{ code: string; description: string | null }>; days: Array<{ id: string; date: string; rawText: string; events: Array<{ type: string; code: string; label: string | null; start: string | null; end: string | null; location: string | null; rawText: string; outsideHomebaseTimezone: boolean }> }> }>>((result, id) => { result[id] = { counts: {}, codes: {}, legends: [], days: [] }; return result; }, {});
  const daysById = new Map<string, { events: Array<{ type: string; code: string; label: string | null; start: string | null; end: string | null; location: string | null; rawText: string; outsideHomebaseTimezone: boolean }> }>();
  for (const day of daysResult.data ?? []) { const target = activityData[day.import_id]; if (target) { const value = { id: day.id, date: day.schedule_date, rawText: day.raw_text, events: [] }; target.days.push(value); daysById.set(day.id, value); } }
  for (const event of eventsResult.data ?? []) { const target = activityData[event.import_id]; const day = daysById.get(event.schedule_day_id); if (target) { target.counts[event.event_type] = (target.counts[event.event_type] ?? 0) + 1; target.codes[event.event_code] = (target.codes[event.event_code] ?? 0) + 1; } if (day) { const metadata = event.raw_metadata && typeof event.raw_metadata === "object" ? event.raw_metadata as { outsideHomebaseTimezone?: boolean } : {}; day.events.push({ type:event.event_type, code:event.event_code, label:event.event_label, start:event.start_time_local, end:event.end_time_local, location:event.location_airport, rawText:event.raw_text, outsideHomebaseTimezone: metadata.outsideHomebaseTimezone === true }); } }
  for (const legend of legendsResult.data ?? []) { activityData[legend.import_id]?.legends.push({ code: legend.code, description: legend.description }); }
  const planned = imports.find(item => item.id === ids[0]) ?? null;
  const current = imports.find(item => item.id === ids[1]) ?? null;
  const snapshots = imports.filter(item => item.schedule_role === "EXECUTION_SNAPSHOT");
  const facts = (factRunsResult.data ?? []).flatMap(run => { const imported = imports.find(item => item.id === run.import_id); if (!imported) return []; const records = (factRecordsResult.data ?? []).filter(record => record.run_id === run.id); const confidence: Record<string,number> = {}; for (const record of records) confidence[record.confidence] = (confidence[record.confidence] ?? 0) + 1; const changes = records.filter(record => record.fact_key === "schedule_change").map(record => ({ type: String((record.value as { changeType?: string }).changeType ?? "UNKNOWN"), value: record.value as Record<string, unknown> })); const rolling = records.filter(record => record.fact_key === "rolling_window").map(record => record.value as Record<string, unknown>); return [{ importId: imported.id, filename: imported.original_filename, summary: run.summary as Record<string, unknown>, changes, rolling, unknown: Array.isArray((run.summary as { unknownCriticalFacts?: unknown }).unknownCriticalFacts) ? (run.summary as { unknownCriticalFacts: unknown[] }).unknownCriticalFacts.map(String) : [], confidence } satisfies FlightFactsDiagnostic]; });
  const ruleDiagnostics = ids.flatMap((importId) => { const imported = imports.find(item => item.id === importId); if (!imported) return []; const evaluations = (ruleEvaluationsResult.data ?? []).filter(item => item.schedule_import_id === importId).map(item => { const factsSnapshot = item.facts_snapshot as Record<string, unknown>; const semantics = deriveEvaluationSemantics({ ruleKey: item.rule_key, status: item.evaluation_status as "PASS" | "FAIL" | "UNKNOWN" | "NOT_APPLICABLE", evaluationContext: item.evaluation_context as "NORMAL" | "TRIGGER" | "EXCEPTION", reason: factsSnapshot.reason ?? item.explanation }); return { ruleKey: item.rule_key, title: item.rule_key.replaceAll("_", " "), status: item.evaluation_status, evaluationContext: item.evaluation_context, behaviorType: semantics.behaviorType, complianceBucket: semantics.complianceBucket, severity: item.severity, confidence: item.confidence, subjectType: item.subject_type, subjectId: item.subject_id, explanation: item.explanation, missingFacts: semantics.missingFacts, factsSnapshot, sourceReferences: item.source_references, rulesetVersion: item.ruleset_version, ruleVersion: item.rule_version }; }); return [{ importId, filename: imported.original_filename, compliance: summarizeCompliance(evaluations), evaluations } satisfies RulesEngineDiagnostic]; });
  const financialDiagnostics = ids.flatMap((importId) => { const imported = imports.find(item => item.id === importId); const accumulator = (financialFactsResult.data ?? []).find(item => item.import_id === importId && item.financial_fact_type === "PRELIMINARY_GUARANTEE_ACCUMULATOR"); if (!imported || !accumulator) return []; const standbyActualSeconds = (financialFactsResult.data ?? []).filter(item => item.import_id === importId && item.financial_fact_type === "STANDBY_GUARANTEE_EQUIVALENT").reduce((sum, item) => sum + item.actual_seconds, 0); return [{ importId, filename: imported.original_filename, operatingSeconds: accumulator.normal_operating_candidate_seconds, deadheadSeconds: accumulator.deadhead_candidate_seconds, standbyActualSeconds, standbyNumeratorSeconds: accumulator.standby_equivalent_numerator_seconds, standbyDenominator: accumulator.standby_equivalent_denominator, reserveSeconds: accumulator.reserve_candidate_seconds, specialPendingSeconds: accumulator.special_time_pending_seconds } satisfies FinancialUnitsDiagnostic]; });
  const specialTimeDiagnostics = ids.flatMap(importId => { const imported = imports.find(item => item.id === importId); if (!imported) return []; return ["OPERATING", "DEADHEAD"].map(activity => { const segments = (financialSegmentsResult.data ?? []).filter(item => item.import_id === importId && item.activity_type === activity); const sum = (predicate: (item: typeof segments[number]) => boolean) => segments.filter(predicate).reduce((value, item) => value + item.duration_seconds, 0); return { importId, filename: imported.original_filename, activity, normalSeconds: sum(item => !item.is_night && !item.is_sunday && item.holiday_status === "FALSE"), nightSeconds: sum(item => item.is_night), nightNumeratorSeconds: segments.filter(item => item.is_night).reduce((value, item) => value + item.night_equivalent_numerator_seconds, 0), sundaySeconds: sum(item => item.is_sunday), holidaySeconds: sum(item => item.holiday_status === "TRUE"), nightSundaySeconds: sum(item => item.is_night && item.is_sunday), nightHolidaySeconds: sum(item => item.is_night && item.holiday_status === "TRUE"), holidayPending: segments.some(item => item.holiday_status === "UNKNOWN") } satisfies FinancialSpecialTimeDiagnostic; }); });
  const entitlementDiagnostics = ids.flatMap(importId => { const imported = imports.find(item => item.id === importId); return imported ? [{ importId, filename: imported.original_filename, items: (financialEntitlementsResult.data ?? []).filter(item => item.import_id === importId).map(item => ({ entitlementType: item.entitlement_type, eligibilityStatus: item.eligibility_status, currency: item.currency, amountMinorUnits: item.amount_minor_units, location: item.location, reason: item.reason })) } satisfies FinancialEntitlementDiagnostic] : []; });
  const guaranteeDiagnostics = ids.flatMap(importId => { const imported = imports.find(item => item.id === importId); const decisions = (financialGuaranteesResult.data ?? []).filter(item => item.executed_import_id === importId); return imported && decisions.length ? [{ filename: imported.original_filename, items: decisions.map(item => ({ component: item.financial_component, planned: item.planned_quantity, executed: item.executed_quantity, unit: item.quantity_unit, decision: item.decision, reason: item.reason, voluntary: item.voluntary_status, confidence: item.confidence })) } satisfies FinancialGuaranteeDiagnostic] : []; });
  const closureViews = (financialClosuresResult.data ?? []).map(item => ({ year: item.year, month: item.month, knownTotalBrl: item.known_total_brl, finalTotalBrl: item.final_total_brl, status: item.final_total_status, lines: ((item.flight_financial_monthly_lines ?? []) as Array<{ component_type: string; amount_minor_units: number | null; calculation_status: string; reason: string | null; source_import: "PLANNED" | "EXECUTED" | "ADDITIVE" | "MIXED" | "NONE" }>).map(line => ({ component: line.component_type, amount: line.amount_minor_units, status: line.calculation_status, reason: line.reason, sourceImport: line.source_import })) }));
  const closureDiagnostics = closureViews.map(item => ({ year: item.year, month: item.month, knownTotalBrl: item.knownTotalBrl, finalTotalBrl: item.finalTotalBrl, status: item.status, lines: item.lines.map(line => ({ component: line.component, amount: line.amount, status: line.status, reason: line.reason })) } satisfies FinancialClosureDiagnostic));
  const label = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" }).format(new Date(year, month - 1, 1));
  const currentRules = current ? ruleDiagnostics.find(item => item.importId === current.id)?.compliance : null;
  const [cyclesResult, legsResult, dutiesResult, payrollEstimateResult, taxEstimateResult, overnightsResult] = current ? await Promise.all([
    access.supabase.from("flight_diem_payment_cycles").select("payment_date,currency,known_minor_units,status").eq("import_id", current.id).order("payment_date"),
    access.supabase.from("flight_legs").select("id,duty_id,sequence,flight_number,aircraft_code,departure_date,leg_type,origin,destination,departure_time_local,arrival_time_local,arrival_date").eq("import_id", current.id).order("sequence"),
    access.supabase.from("flight_duties").select("id,sequence,start_date,end_date,check_in_airport,check_out_airport,check_in_time_local,check_out_time_local,calculated_duty_time_minutes").eq("import_id", current.id).order("sequence"),
    access.supabase.from("flight_payroll_final_estimates").select("id,gross_amount_minor_units,estimate_status,reconciliation_status").eq("import_id", current.id).maybeSingle(),
    access.supabase.from("flight_payroll_tax_estimates").select("gross_amount_minor_units,inss_amount_minor_units,irrf_amount_minor_units,personal_deductions_minor_units,net_amount_minor_units,tax_status,provenance").eq("import_id", current.id).maybeSingle(),
    access.supabase.from("flight_trip_overnights").select("id,start_at,location").eq("import_id", current.id).order("start_at"),
  ]) : [{ data: [] }, { data: [] }, { data: [] }, { data: null }, { data: null }, { data: [] }];
  if (payrollEstimateResult.error || taxEstimateResult.error || overnightsResult.error) throwSupabaseError(payrollEstimateResult.error ?? taxEstimateResult.error ?? overnightsResult.error!, "carregar demonstrativo final", "Não foi possível carregar o demonstrativo final da escala.");
  const payrollLinesResult = payrollEstimateResult.data ? await access.supabase.from("flight_payroll_final_lines").select("estimate_id,line_key,payroll_reference,exact_seconds,amount_minor_units,metadata").eq("estimate_id", payrollEstimateResult.data.id).order("line_key") : { data: [], error: null };
  if (payrollLinesResult.error) throwSupabaseError(payrollLinesResult.error, "carregar rubricas finais", "Não foi possível carregar as rubricas finais da escala.");
  const mealLabels: Record<string, string> = { DOMESTIC_BREAKFAST: "Café", DOMESTIC_LUNCH: "Almoço", DOMESTIC_DINNER: "Jantar", DOMESTIC_SUPPER: "Ceia", INTERNATIONAL_BREAKFAST: "Café", INTERNATIONAL_LUNCH: "Almoço", INTERNATIONAL_DINNER: "Jantar", INTERNATIONAL_SUPPER: "Ceia" };
  const diems = current ? (financialEntitlementsResult.data ?? []).filter(item => item.import_id === current.id && item.eligibility_status === "ELIGIBLE" && item.entitlement_date && mealLabels[item.entitlement_type]).map(item => ({ date: item.entitlement_date!, label: mealLabels[item.entitlement_type], currency: item.currency, amount: item.amount_minor_units })) : [];
  const personal = taxEstimateResult.data?.provenance && typeof taxEstimateResult.data.provenance === "object" ? (taxEstimateResult.data.provenance as { personal?: Array<{ name?: unknown; amountCents?: unknown }> }).personal ?? [] : [];
  const overview = <FlightMonthOverview label={label} planned={planned} current={current} activity={current ? activityData[current.id] : undefined} legs={(legsResult.data ?? []).filter(leg => leg.departure_date !== null).map(leg => ({ id: leg.id, dutyId: leg.duty_id, sequence: leg.sequence, flightNumber: leg.flight_number, aircraft: leg.aircraft_code, scheduleDate: leg.departure_date!, legType: leg.leg_type, origin: leg.origin, destination: leg.destination, departure: leg.departure_time_local?.slice(0,5) ?? null, arrival: leg.arrival_time_local?.slice(0,5) ?? null, arrivalDate: leg.arrival_date }))} duties={(dutiesResult.data ?? []).map(duty => ({ id: duty.id, sequence: duty.sequence, startDate: duty.start_date, endDate: duty.end_date, checkInAirport: duty.check_in_airport, checkOutAirport: duty.check_out_airport, checkIn: duty.check_in_time_local?.slice(0,5) ?? null, checkOut: duty.check_out_time_local?.slice(0,5) ?? null, durationMinutes: duty.calculated_duty_time_minutes }))} overnights={(overnightsResult.data ?? []).map(overnight => ({ id: overnight.id, date: new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo" }).format(new Date(overnight.start_at)), location: overnight.location }))} audit={{ pass: currentRules?.confirmedCompliant ?? 0, fail: currentRules?.confirmedViolations ?? 0, unknown: currentRules?.notEvaluable ?? 0, notApplicable: currentRules?.notApplicable ?? 0 }} payroll={payrollEstimateResult.data ? { estimateId: payrollEstimateResult.data.id, gross: payrollEstimateResult.data.gross_amount_minor_units, lines: (payrollLinesResult.data ?? []).map(line => ({ key: line.line_key, amount: line.amount_minor_units, reference: line.payroll_reference, metadata: line.metadata })), inss: taxEstimateResult.data?.inss_amount_minor_units ?? null, irrf: taxEstimateResult.data?.irrf_amount_minor_units ?? null, personalDeductions: personal.filter(item => typeof item.name === "string" && typeof item.amountCents === "number").map(item => ({ name: item.name as string, amount: item.amountCents as number })), personalDeductionTotal: taxEstimateResult.data?.personal_deductions_minor_units ?? null, net: taxEstimateResult.data?.net_amount_minor_units ?? null, base: "EXECUTED" } : null} cycles={(cyclesResult.data ?? []).map(cycle => ({ paymentDate: cycle.payment_date, currency: cycle.currency, amount: cycle.known_minor_units, status: cycle.status }))} diems={diems} />;
  return <FlightShell profile={access.profile} modules={shellData.modules} providerHealth={shellData.providerHealth}><section className="relative z-10 mx-auto my-8 grid w-full max-w-7xl gap-5 px-4 sm:px-0">{overview}<details className="rounded-2xl border border-[var(--atlas-border)] bg-[var(--atlas-surface)] p-4"><summary className="cursor-pointer text-sm font-semibold">Painel técnico e diagnósticos avançados</summary><div className="mt-5 grid gap-6"><ScheduleMonthView year={year} month={month} planned={planned} current={current} snapshots={snapshots} activityData={activityData} /><PayrollStatement /><FlightFactsDiagnostics items={facts} /><FinancialUnitsDiagnostics items={financialDiagnostics} /><FinancialSpecialTimeDiagnostics items={specialTimeDiagnostics} /><FinancialEntitlementsDiagnostics items={entitlementDiagnostics} /><FinancialGuaranteeDiagnostics items={guaranteeDiagnostics} /><FinancialClosureDiagnostics items={closureDiagnostics} /><RulesEngineDiagnostics items={ruleDiagnostics} /></div></details></section></FlightShell>;
}
