import { EmptyState } from "@/components/finance/empty-state";
import { SubmitButton } from "@/components/finance/submit-button";
import { archiveCard,createCard } from "@/modules/finance/actions";
import { requireFinanceAccess } from "@/modules/finance/access";
import { formatCurrency,formatDate } from "@/modules/finance/format";
import { getFinanceData } from "@/modules/finance/queries";

export default async function Page(){const {supabase,user}=await requireFinanceAccess();const data=await getFinanceData(supabase,user.id);return <>
 <section className="finance-panel"><header><div><p className="eyebrow">Crédito e faturas</p><h2>Cartões</h2></div></header>{data.cards.length?<div className="finance-card-grid">{data.cards.map(card=><article key={card.id} className={card.status==="archived"?"archived":""}><div className="finance-credit-visual"><small>{card.institution_name||card.brand||"Atlas"}</small><b>{card.name}</b><span>•••• {card.last_four_digits||"••••"}</span></div><p>Limite <strong>{formatCurrency(Number(card.credit_limit))}</strong></p><p>Saldo/fatura <strong>{formatCurrency(Math.abs(Number(card.current_balance)))}</strong></p><small>Fecha dia {card.closing_day} · vence dia {card.due_day}{card.last_sync_at?` · atualizado ${formatDate(card.last_sync_at)}`:""}</small>{card.status==="active"?<form action={archiveCard}><input type="hidden" name="id" value={card.id}/><button>Arquivar</button></form>:null}</article>)}</div>:<EmptyState title="Nenhum cartão" description="Cadastre um cartão ou conecte a Pluggy para importar compras."/>}</section>
 <section id="novo" className="finance-panel"><header><h2>Novo cartão</h2></header><form action={createCard} className="finance-form"><label>Nome<input name="name" required/></label><label>Instituição<input name="institution_name"/></label><label>Bandeira<input name="brand"/></label><label>Últimos 4 dígitos<input name="last_four_digits" inputMode="numeric" pattern="[0-9]{4}" maxLength={4}/></label><label>Limite<input name="credit_limit" inputMode="decimal" required/></label><label>Fechamento<input name="closing_day" type="number" min="1" max="31" required/></label><label>Vencimento<input name="due_day" type="number" min="1" max="31" required/></label><label>Conta de pagamento<select name="linked_account_id"><option value="">Não vinculada</option>{data.accounts.map(account=><option value={account.id} key={account.id}>{account.name}</option>)}</select></label><SubmitButton>Criar cartão</SubmitButton></form></section>
 </>}
