import { EmptyState } from "@/components/finance/empty-state";
import { SubmitButton } from "@/components/finance/submit-button";
import { createTransaction,deleteTransaction,updateTransactionStatus } from "@/modules/finance/actions";
import { requireFinanceAccess } from "@/modules/finance/access";
import { formatCurrency,formatDate } from "@/modules/finance/format";
import { getFinanceData } from "@/modules/finance/queries";

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;type?:string;status?:string}>}){
 const filters=await searchParams;const {supabase,user}=await requireFinanceAccess();const data=await getFinanceData(supabase,user.id);
 let rows=data.transactions;if(filters.q)rows=rows.filter(item=>item.description.toLowerCase().includes(filters.q!.toLowerCase()));if(filters.type)rows=rows.filter(item=>item.transaction_type===filters.type);if(filters.status)rows=rows.filter(item=>item.status===filters.status);
 const today=new Date().toISOString().slice(0,10);
 return <>
  <section className="finance-panel"><header><div><p className="eyebrow">Histórico completo</p><h2>Movimentações</h2></div></header>
   <form className="finance-filters"><input name="q" placeholder="Buscar descrição" defaultValue={filters.q}/><select name="type" defaultValue={filters.type||""}><option value="">Todos os tipos</option><option value="income">Receitas</option><option value="expense">Despesas</option><option value="transfer">Transferências</option></select><select name="status" defaultValue={filters.status||""}><option value="">Todos os status</option><option value="forecast">Previsto</option><option value="pending">Pendente</option><option value="realized">Realizado</option></select><button className="finance-button">Filtrar</button></form>
   {rows.length?<div className="finance-transactions">{rows.map(item=><article key={item.id}><div><b>{item.description}</b><small>{item.financial_categories?.name||"Sem categoria"} · {item.financial_accounts?.name||item.credit_cards?.name||"Conta"} · {formatDate(item.competence_date)}</small><span className="status">{item.status} · {item.source}{item.review_status==="pending"?" · revisar":""}{item.visibility==="workspace"?" · compartilhado":""}</span></div><strong className={item.transaction_type==="expense"?"negative":"positive"}>{item.transaction_type==="expense"?"−":"+"} {formatCurrency(Number(item.amount))}</strong><div className="finance-row-actions">{item.status!=="realized"&&item.status!=="cancelled"?<form action={updateTransactionStatus}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="status" value="realized"/><button>Realizar</button></form>:null}<form action={deleteTransaction}><input type="hidden" name="id" value={item.id}/><button className="danger">Excluir</button></form></div></article>)}</div>:<EmptyState title="Nenhuma movimentação" description="Registre uma receita, despesa ou transferência para começar."/>}
  </section>
  <section id="nova" className="finance-panel"><header><div><p className="eyebrow">Ação rápida</p><h2>Nova movimentação</h2></div></header>{data.accounts.length?<form action={createTransaction} className="finance-form"><label>Tipo<select name="transaction_type" required><option value="expense">Despesa</option><option value="income">Receita</option><option value="transfer">Transferência</option></select></label><label>Descrição<input name="description" required maxLength={160}/></label><label>Valor em reais<input name="amount" inputMode="decimal" placeholder="0,00" required/></label><label>Conta<select name="account_id" required>{data.accounts.filter(item=>item.status==="active").map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Destino (transferência)<select name="destination_account_id"><option value="">Selecione</option>{data.accounts.filter(item=>item.status==="active").map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Categoria<select name="category_id"><option value="">Sem categoria</option>{data.categories.map(category=><option value={String(category.id)} key={String(category.id)}>{String(category.name)}</option>)}</select></label><label>Competência<input name="competence_date" type="date" defaultValue={today} required/></label><label>Vencimento<input name="due_date" type="date"/></label><label>Status<select name="status"><option value="pending">Pendente</option><option value="forecast">Previsto</option><option value="realized">Realizado</option></select></label><SubmitButton>Salvar movimentação</SubmitButton></form>:<EmptyState title="Crie uma conta primeiro" description="Toda movimentação precisa estar vinculada a uma conta." href="/financeiro/contas#nova" label="Criar conta"/>}</section>
 </>;
}
