import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createClient } from "@supabase/supabase-js";

const importId = process.argv[2];
if (!importId) throw new Error("Usage: export-flight-diem-audit.mts <schedule-import-id>");
const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) throw new Error("Supabase server credentials are required.");
const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
const [source, entitlementsResult, cyclesResult] = await Promise.all([
  supabase.from("flight_schedule_imports").select("id,original_filename,document_period_start,document_period_end").eq("id", importId).maybeSingle(),
  supabase.from("flight_financial_entitlements").select("id,subject_id,entitlement_type,entitlement_date,location,country,domesticity,currency,amount_minor_units,eligibility_status,reason,start_at,end_at,provenance").eq("import_id", importId).order("entitlement_date").order("start_at"),
  supabase.from("flight_diem_payment_cycles").select("payment_date,half_month,currency,known_minor_units,entitlement_count,status").eq("import_id", importId).order("payment_date"),
]);
if (source.error || !source.data || entitlementsResult.error || cyclesResult.error) throw new Error(source.error?.message ?? entitlementsResult.error?.message ?? cyclesResult.error?.message ?? "Unable to export diem audit.");

type Row = NonNullable<typeof entitlementsResult.data>[number];
const rows = entitlementsResult.data ?? []; const start = source.data.document_period_start ?? "2026-08-01"; const end = source.data.document_period_end ?? "2026-08-31";
const dates: string[] = []; for (let date = start; date <= end; date = new Date(Date.parse(`${date}T12:00:00Z`) + 86400000).toISOString().slice(0, 10)) dates.push(date);
const byDate = new Map<string, Row[]>(); for (const row of rows) byDate.set(row.entitlement_date, [...(byDate.get(row.entitlement_date) ?? []), row]);
const sum = (items: readonly Row[], currency: string) => items.filter(item => item.eligibility_status === "ELIGIBLE" && item.currency === currency).reduce((total, item) => total + (item.amount_minor_units ?? 0), 0);
const half = (date: string) => Number(date.slice(8, 10)) <= 15 ? "FIRST_HALF" : "SECOND_HALF";
const summaries = ["FIRST_HALF", "SECOND_HALF"].map(keyPart => { const items = rows.filter(item => half(item.entitlement_date) === keyPart); const paymentDate = keyPart === "FIRST_HALF" ? `${start.slice(0, 8)}25` : `${new Date(Date.UTC(Number(start.slice(0, 4)), Number(start.slice(5, 7)), 10)).toISOString().slice(0, 10)}`; const currencies = ["BRL", "USD", "EUR", "GBP"].map(currency => ({ currency, dailyKnownMinorUnits: sum(items, currency), cycleKnownMinorUnits: (cyclesResult.data ?? []).filter(cycle => cycle.half_month === keyPart && cycle.currency === currency).reduce((total, cycle) => total + cycle.known_minor_units, 0) })); return { half: keyPart, paymentDate, unknownCount: items.filter(item => item.eligibility_status === "UNKNOWN").length, currencies }; });
const report = { generatedAt: new Date().toISOString(), import: source.data, days: dates.map(date => ({ date, entries: byDate.get(date) ?? [] })), summaries, cycles: cyclesResult.data ?? [], reconciliation: summaries.flatMap(summary => summary.currencies.map(currency => ({ half: summary.half, currency: currency.currency, dailyKnownMinorUnits: currency.dailyKnownMinorUnits, cycleKnownMinorUnits: currency.cycleKnownMinorUnits, deltaMinorUnits: currency.dailyKnownMinorUnits - currency.cycleKnownMinorUnits, status: currency.dailyKnownMinorUnits === currency.cycleKnownMinorUnits ? "RECONCILED" : "RECONCILIATION_ERROR" }))) };
const output = join(process.cwd(), "tmp", "pdfs"); await mkdir(output, { recursive: true }); await writeFile(join(output, "atlas-diarias-auditoria-2026-08.json"), JSON.stringify(report, null, 2));
const escape = (value: unknown) => String(value ?? "-").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
const money = (currency: string | null, value: number | null) => value === null || !currency ? "PENDENTE" : new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value / 100);
const labels: Record<string, string> = { DOMESTIC_BREAKFAST: "Café", DOMESTIC_LUNCH: "Almoço", DOMESTIC_DINNER: "Jantar", DOMESTIC_SUPPER: "Ceia", INTERNATIONAL_BREAKFAST: "Café", INTERNATIONAL_LUNCH: "Almoço", INTERNATIONAL_DINNER: "Jantar", INTERNATIONAL_SUPPER: "Ceia", MADRUGADA_TRANSPORT_REIMBURSEMENT: "Transporte madrugada" };
const status: Record<string, string> = { ELIGIBLE: "DEVIDO", NOT_ELIGIBLE: "NÃO DEVIDO", UNKNOWN: "PENDENTE" };
const reasonLabels: Record<string, string> = { ELIGIBLE_TRAINING_OVERLAP: "atividade de treinamento", ELIGIBLE_DEADHEAD_OVERLAP: "deadhead a serviço", ELIGIBLE_RESERVE_OVERLAP: "reserva", ELIGIBLE_SERVICE_OVERLAP: "serviço documentado", NOT_ELIGIBLE_NO_SERVICE_IN_WINDOW: "sem serviço na janela", NOT_ELIGIBLE_HOTEL_BREAKFAST: "café fornecido pelo hotel", AT_CONTRACTUAL_BASE: "na base contratual", UNKNOWN_LOCATION: "localização não confirmada", UNKNOWN_HOTEL_STATUS: "hotel não confirmado", UNKNOWN_STANDBY_DOCUMENTARY_POLICY: "política documental de standby pendente" };
const daily = report.days.map(day => { const entries = day.entries; const locations = [...new Set(entries.map(entry => entry.location).filter((value): value is string => Boolean(value)))].join(" / ") || "Sem localização documental na janela"; const totals = new Map<string, number>(); for (const entry of entries.filter(entry => entry.eligibility_status === "ELIGIBLE" && entry.currency && entry.amount_minor_units !== null)) totals.set(entry.currency!, (totals.get(entry.currency!) ?? 0) + entry.amount_minor_units!); const pending = entries.filter(entry => entry.eligibility_status === "UNKNOWN").length; const rows = entries.map(entry => { const provenance = entry.provenance && typeof entry.provenance === "object" ? entry.provenance as Record<string, unknown> : {}; const reason = entry.reason ?? "Sem reason code"; return `<tr><td>${escape(labels[entry.entitlement_type] ?? entry.entitlement_type)}</td><td><strong>${escape(status[entry.eligibility_status] ?? entry.eligibility_status)}</strong></td><td>${escape(String(provenance.timelineActivityKind ?? "OFF").replaceAll("_", " "))}<br><small>${escape(entry.start_at)} - ${escape(entry.end_at)} · ${escape(entry.location)}</small></td><td>${escape(reason)}<br><small>${escape(reasonLabels[reason] ?? "descrição não catalogada")}; hotel usado=${escape(provenance.hotelUsed ?? "UNKNOWN")}; dispensado=${escape(provenance.hotelWaived ?? "UNKNOWN")}</small></td><td>${escape(money(entry.currency, entry.amount_minor_units))}</td></tr>`; }).join("") || `<tr><td colspan="5">Sem entitlement persistido. Ausência de linha não é conclusão jurídica.</td></tr>`; const technical = entries.map(entry => { const provenance = entry.provenance && typeof entry.provenance === "object" ? entry.provenance as Record<string, unknown> : {}; return `id=${entry.id}; subject=${entry.subject_id}; source=${String(provenance.timelineActivityId ?? "none")}`; }).join(" | ") || "Sem IDs de entitlement neste dia."; return `<article><h2>${escape(day.date.slice(8, 10))}/${escape(day.date.slice(5, 7))}/2026 <span>${escape(locations)}</span></h2><p>Total conhecido: <strong>${escape([...totals.entries()].map(([currency, value]) => money(currency, value)).join(" · ") || "R$ 0,00")}</strong> · Pendências: ${pending} · Pagamento previsto: ${Number(day.date.slice(8, 10)) <= 15 ? "25/08/2026" : "10/09/2026"}</p><table><thead><tr><th>Item</th><th>Status</th><th>Atividade / horário / local</th><th>Motivo</th><th>Valor</th></tr></thead><tbody>${rows}</tbody></table><p class="technical">Técnico: ${escape(technical)}</p></article>`; }).join("\n");
const summaryRows = report.summaries.map(summary => { const currencies = new Map(summary.currencies.map(currency => [currency.currency, currency.dailyKnownMinorUnits])); return `<tr><td>${summary.half === "FIRST_HALF" ? "01-15" : "16-31"}</td><td>${summary.paymentDate}</td><td>${money("BRL", currencies.get("BRL") ?? 0)}</td><td>${money("USD", currencies.get("USD") ?? 0)}</td><td>${money("EUR", currencies.get("EUR") ?? 0)}</td><td>${money("GBP", currencies.get("GBP") ?? 0)}</td><td>${summary.unknownCount}</td></tr>`; }).join("");
const reconciliationRows = report.reconciliation.map(row => `<tr><td>${row.half === "FIRST_HALF" ? "01-15" : "16-31"}</td><td>${row.currency}</td><td>${money(row.currency, row.dailyKnownMinorUnits)}</td><td>${money(row.currency, row.cycleKnownMinorUnits)}</td><td>${money(row.currency, row.deltaMinorUnits)}</td><td>${row.status}</td></tr>`).join("");
const html = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Atlas - Auditoria de Diárias - Agosto 2026</title><style>@page{size:A4;margin:13mm}body{font-family:Arial,sans-serif;color:#132238;font-size:10px;line-height:1.35}h1{font-size:23px;margin:0}h2{font-size:14px;margin:15px 0 4px;border-bottom:1px solid #b9c8d8;padding-bottom:3px}h2 span{font-weight:normal;color:#516477;font-size:11px}table{width:100%;border-collapse:collapse;margin:7px 0 3px}th{background:#173b64;color:#fff;text-align:left}th,td{border:1px solid #cbd5df;padding:5px;vertical-align:top}small,.technical{color:#52606d;font-size:8px}.technical{overflow-wrap:anywhere}.summary{margin:12px 0 18px}article{break-inside:avoid}</style></head><body><h1>Atlas Flight - Auditoria de Diárias</h1><p>Agosto/2026 · import ${escape(report.import.id)} · arquivo ${escape(report.import.original_filename)}<br>Fonte única: entitlements persistidos pelo motor. Gerado em ${escape(report.generatedAt)}.</p><section class="summary"><h2>Resumo por pagamento</h2><table><thead><tr><th>Período</th><th>Pagamento</th><th>BRL</th><th>USD</th><th>EUR</th><th>GBP</th><th>Pendências</th></tr></thead><tbody>${summaryRows}</tbody></table><h2>Reconciliação diário × ciclo</h2><table><thead><tr><th>Período</th><th>Moeda</th><th>Soma diária</th><th>Ciclo</th><th>Delta</th><th>Status</th></tr></thead><tbody>${reconciliationRows}</tbody></table></section>${daily}</body></html>`;
const artifactDirectory = join(process.cwd(), "artifacts", "flight"); await mkdir(artifactDirectory, { recursive: true }); const htmlPath = join(artifactDirectory, "atlas-diarias-auditoria-2026-08.html"); await writeFile(htmlPath, html, "utf8");
console.log(JSON.stringify({ json: join(output, "atlas-diarias-auditoria-2026-08.json"), html: htmlPath }));
