-- Atlas Flight 3C.6: fechamento por linhas, sem total final quando houver dependências desconhecidas.
create table if not exists public.flight_financial_monthly_closures(
 id uuid primary key, user_id uuid not null references auth.users(id) on delete cascade, year integer not null, month smallint not null check(month between 1 and 12), planned_import_id uuid not null references public.flight_schedule_imports(id) on delete cascade, executed_import_id uuid not null references public.flight_schedule_imports(id) on delete cascade, known_total_brl bigint not null default 0, final_total_brl bigint, final_total_status text not null check(final_total_status in ('COMPLETE','INCOMPLETE','PROVISIONAL')), engine_version text not null, provenance jsonb not null default '{}'::jsonb check(jsonb_typeof(provenance)='object'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(executed_import_id)
);
create table if not exists public.flight_financial_monthly_lines(
 id uuid primary key, closure_id uuid not null references public.flight_financial_monthly_closures(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, component_type text not null, source_import text not null check(source_import in ('PLANNED','EXECUTED','ADDITIVE','MIXED','NONE')), quantity bigint not null check(quantity>=0), quantity_unit text not null, rate_minor_units bigint, currency char(3), multiplier_numerator bigint not null default 1, multiplier_denominator bigint not null default 1 check(multiplier_denominator>0), amount_minor_units bigint, calculation_status text not null check(calculation_status in ('CALCULATED','UNKNOWN','NOT_APPLICABLE','PROVISIONAL')), decision_id uuid references public.flight_financial_guarantee_decisions(id) on delete set null, economic_parameter_id uuid references public.flight_economic_parameters(id) on delete set null, source_instrument_id uuid references public.flight_legal_instruments(id) on delete restrict, source_clause text, reason text, confidence text not null check(confidence in ('HIGH','MEDIUM','LOW')), payroll_mapping_key text, provenance jsonb not null default '{}'::jsonb check(jsonb_typeof(provenance)='object'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(closure_id,component_type)
);
do $$ begin create trigger flight_financial_monthly_closures_set_updated_at before update on public.flight_financial_monthly_closures for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger flight_financial_monthly_lines_set_updated_at before update on public.flight_financial_monthly_lines for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
alter table public.flight_financial_monthly_closures enable row level security; alter table public.flight_financial_monthly_lines enable row level security;
create policy flight_financial_monthly_closures_owner_read on public.flight_financial_monthly_closures for select to authenticated using(user_id=auth.uid());
create policy flight_financial_monthly_lines_owner_read on public.flight_financial_monthly_lines for select to authenticated using(user_id=auth.uid() and exists(select 1 from public.flight_financial_monthly_closures closure where closure.id=closure_id and closure.user_id=auth.uid()));
grant select on public.flight_financial_monthly_closures,public.flight_financial_monthly_lines to authenticated;
grant select,insert,update,delete on public.flight_financial_monthly_closures,public.flight_financial_monthly_lines to service_role;
