-- Atlas Flight 3C.3: segmentação temporal, sem dinheiro, diárias ou regra jurídica.
create table if not exists public.flight_holiday_calendar_years(
 id uuid primary key default gen_random_uuid(), year integer not null, country char(2) not null default 'BR', base_code text, status text not null check(status in ('VERIFIED','PENDING_VERIFICATION','INCOMPLETE','UNKNOWN')), source_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique nulls not distinct(year,country,base_code)
);
create table if not exists public.flight_holidays(
 id uuid primary key default gen_random_uuid(), holiday_date date not null, name text not null, scope text not null check(scope in ('NATIONAL','BASE_STATE','BASE_MUNICIPAL')), country char(2) not null default 'BR', state text, city text, base_code text, year integer not null, legal_source_type text not null, legal_source_number text, legal_source_issuer text, legal_source_reference text not null, verified boolean not null default false, lifecycle text not null check(lifecycle in ('DRAFT','REVIEWED','ACTIVE','RETIRED','REVIEW_REQUIRED')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(extract(year from holiday_date)=year), unique nulls not distinct(holiday_date,scope,base_code,name)
);
create table if not exists public.flight_financial_segments(
 id uuid primary key, import_id uuid not null references public.flight_schedule_imports(id) on delete cascade, subject_type text not null check(subject_type='LEG'), subject_id uuid not null, activity_type text not null check(activity_type in ('OPERATING','DEADHEAD')), start_at timestamptz not null, end_at timestamptz not null, duration_seconds bigint not null check(duration_seconds>0), is_night boolean not null, is_sunday boolean not null, holiday_status text not null check(holiday_status in ('TRUE','FALSE','UNKNOWN')), holiday_id uuid references public.flight_holidays(id) on delete set null, holiday_name text, holiday_scope text, reference_timezone text not null check(reference_timezone='UTC'), reference_location text, normal_equivalent_seconds bigint not null check(normal_equivalent_seconds>=0), night_equivalent_numerator_seconds bigint not null check(night_equivalent_numerator_seconds>=0), night_equivalent_denominator smallint not null check(night_equivalent_denominator>0), provenance jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(end_at>start_at), unique(import_id,subject_id,start_at,end_at)
);
create index if not exists flight_financial_segments_import_idx on public.flight_financial_segments(import_id,activity_type,start_at);
do $$ begin create trigger flight_holiday_calendar_years_set_updated_at before update on public.flight_holiday_calendar_years for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger flight_holidays_set_updated_at before update on public.flight_holidays for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
do $$ begin create trigger flight_financial_segments_set_updated_at before update on public.flight_financial_segments for each row execute function public.set_updated_at(); exception when duplicate_object then null; end $$;
alter table public.flight_holiday_calendar_years enable row level security; alter table public.flight_holidays enable row level security; alter table public.flight_financial_segments enable row level security;
create policy flight_holiday_calendar_years_read on public.flight_holiday_calendar_years for select to authenticated using(true);
create policy flight_holidays_read on public.flight_holidays for select to authenticated using(true);
create policy flight_financial_segments_owner_read on public.flight_financial_segments for select to authenticated using(exists(select 1 from public.flight_schedule_imports schedule_import where schedule_import.id=import_id and schedule_import.user_id=auth.uid()));
grant select on public.flight_holiday_calendar_years,public.flight_holidays,public.flight_financial_segments to authenticated;
grant select,insert,update,delete on public.flight_holiday_calendar_years,public.flight_holidays,public.flight_financial_segments to service_role;
insert into public.flight_holiday_calendar_years(year,country,base_code,status,source_reference) values (2026,'BR',null,'PENDING_VERIFICATION','3C.3: aguardando carga de fonte oficial nacional e bases GOL suportadas.') on conflict (year,country,base_code) do nothing;
insert into public.flight_economic_parameters(parameter_key,role,value_unit,lifecycle,source_type,derived,seniority_applicable,metadata,source_reference) values ('NIGHT_SUNDAY_HOLIDAY_COMPOSITION',null,'POLICY','REVIEW_REQUIRED','SYSTEM_DERIVED',false,false,'{"status":"PROVISIONAL","interpretation":"NIGHT_CONVERSION_THEN_SUNDAY_HOLIDAY_MULTIPLIER","payslipReconciliation":"PENDING"}'::jsonb,'Política provisória 3C.3; não utilizada para cálculo monetário.') on conflict (parameter_key,role,effective_from) do nothing;
