alter table public.flight_duties add column if not exists metric_association_status text not null default 'UNRESOLVED' check(metric_association_status in('ASSOCIATED','UNRESOLVED','AMBIGUOUS')), add column if not exists metric_confidence text check(metric_confidence in('HIGH','MEDIUM','LOW'));
alter table public.flight_schedule_documentary_metrics add column if not exists association_status text not null default 'ASSOCIATED' check(association_status in('ASSOCIATED','UNRESOLVED','AMBIGUOUS')), add column if not exists confidence text check(confidence in('HIGH','MEDIUM','LOW'));
create table if not exists public.flight_schedule_unresolved_metrics(id uuid primary key default gen_random_uuid(),import_id uuid not null references public.flight_schedule_imports(id) on delete cascade,metric_type text not null check(metric_type in('FT','DT','RT')),raw_label text not null,raw_value text,page_number integer,x numeric,y numeric,schedule_day_id uuid references public.flight_schedule_days(id) on delete set null,candidate_duty_sequences jsonb not null default '[]'::jsonb,reason text not null,raw_metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.flight_schedule_ambiguous_metrics(id uuid primary key default gen_random_uuid(),import_id uuid not null references public.flight_schedule_imports(id) on delete cascade,metric_type text not null check(metric_type in('FT','DT','RT')),raw_label text not null,raw_value text,candidate_duty_sequences jsonb not null default '[]'::jsonb,reason text not null,raw_metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.flight_schedule_unresolved_metrics enable row level security; alter table public.flight_schedule_ambiguous_metrics enable row level security;
create policy flight_schedule_unresolved_metrics_owner_read on public.flight_schedule_unresolved_metrics for select to authenticated using(exists(select 1 from public.flight_schedule_imports i where i.id=import_id and i.user_id=auth.uid()));
create policy flight_schedule_ambiguous_metrics_owner_read on public.flight_schedule_ambiguous_metrics for select to authenticated using(exists(select 1 from public.flight_schedule_imports i where i.id=import_id and i.user_id=auth.uid()));
create or replace function public.persist_flight_metric_audit(p_import_id uuid,p_duty_audit jsonb,p_documentary_audit jsonb,p_unresolved jsonb,p_ambiguous jsonb) returns void language plpgsql security definer set search_path='' as $$
declare is_service boolean:=auth.role()='service_role'; begin
 if (auth.uid() is null and not is_service) or not exists(select 1 from public.flight_schedule_imports where id=p_import_id and (is_service or user_id=auth.uid())) then raise exception 'Acesso negado.' using errcode='42501'; end if;
 delete from public.flight_schedule_unresolved_metrics where import_id=p_import_id; delete from public.flight_schedule_ambiguous_metrics where import_id=p_import_id;
 update public.flight_duties d set metric_association_status=x.association_status,metric_confidence=x.confidence from jsonb_to_recordset(coalesce(p_duty_audit,'[]'::jsonb)) x(sequence smallint,association_status text,confidence text) where d.import_id=p_import_id and d.sequence=x.sequence;
 update public.flight_schedule_documentary_metrics m set association_status=x.association_status,confidence=x.confidence from jsonb_to_recordset(coalesce(p_documentary_audit,'[]'::jsonb)) x(schedule_date date,association_status text,confidence text) join public.flight_schedule_days d on d.import_id=p_import_id and d.schedule_date=x.schedule_date where m.import_id=p_import_id and m.schedule_day_id=d.id;
 insert into public.flight_schedule_unresolved_metrics(import_id,metric_type,raw_label,raw_value,page_number,x,y,reason,raw_metadata) select p_import_id,x.metric_type,x.raw_label,x.raw_value,x.page_number,x.x,x.y,x.reason,coalesce(x.raw_metadata,'{}'::jsonb) from jsonb_to_recordset(coalesce(p_unresolved,'[]'::jsonb)) x(metric_type text,raw_label text,raw_value text,page_number integer,x numeric,y numeric,reason text,raw_metadata jsonb);
 insert into public.flight_schedule_ambiguous_metrics(import_id,metric_type,raw_label,raw_value,candidate_duty_sequences,reason,raw_metadata) select p_import_id,x.metric_type,x.raw_label,x.raw_value,coalesce(x.candidate_duty_sequences,'[]'::jsonb),x.reason,coalesce(x.raw_metadata,'{}'::jsonb) from jsonb_to_recordset(coalesce(p_ambiguous,'[]'::jsonb)) x(metric_type text,raw_label text,raw_value text,candidate_duty_sequences jsonb,reason text,raw_metadata jsonb);
end $$;
grant execute on function public.persist_flight_metric_audit(uuid,jsonb,jsonb,jsonb,jsonb) to authenticated,service_role;
grant select on public.flight_schedule_unresolved_metrics,public.flight_schedule_ambiguous_metrics to authenticated,service_role;
