create table if not exists public.flight_payroll_bucket_runs(
 id uuid primary key, user_id uuid not null references auth.users(id) on delete cascade, import_id uuid not null references public.flight_schedule_imports(id) on delete cascade, bucket text not null check(bucket in ('NORMAL','NIGHT_NORMAL','SUNDAY_HOLIDAY_DAY','SUNDAY_HOLIDAY_NIGHT')), source_activity text not null check(source_activity in ('OPERATING','DEADHEAD','STANDBY','RESERVE')), actual_seconds bigint not null check(actual_seconds>=0), equivalent_numerator_seconds bigint not null check(equivalent_numerator_seconds>=0), equivalent_denominator smallint not null check(equivalent_denominator>0), payroll_reference numeric(12,2) not null, provenance jsonb not null default '{}'::jsonb, unique(import_id,bucket,source_activity)
);
create table if not exists public.flight_diem_payment_cycles(
 id uuid primary key, user_id uuid not null references auth.users(id) on delete cascade, import_id uuid not null references public.flight_schedule_imports(id) on delete cascade, payment_date date not null, half_month text not null check(half_month in ('FIRST_HALF','SECOND_HALF')), currency char(3), known_minor_units bigint not null default 0, entitlement_count integer not null default 0, status text not null check(status in ('ESTIMATED','CLOSED','PARTIAL','UNKNOWN')), provenance jsonb not null default '{}'::jsonb, unique(import_id,payment_date,currency)
);
create table if not exists public.flight_personal_payroll_components(
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, component_key text not null, name text not null, component_type text not null check(component_type in ('PERSONAL_PAYROLL_COMPONENT','LEGAL_AUTOMATIC','PERSONAL_FIXED','PERSONAL_PERCENTAGE','PERSONAL_VARIABLE')), amount_minor_units bigint, percentage numeric(8,4), base_type text, effective_from date not null, effective_to date, active boolean not null default true, source_type text not null check(source_type in ('PAYROLL_CONFIRMED','USER_CONFIRMED','DOCUMENT_SOURCE')), notes text, unique(user_id,component_key,effective_from)
);
alter table public.flight_payroll_bucket_runs enable row level security; alter table public.flight_diem_payment_cycles enable row level security; alter table public.flight_personal_payroll_components enable row level security;
create policy flight_payroll_bucket_runs_owner_read on public.flight_payroll_bucket_runs for select to authenticated using(user_id=auth.uid());
create policy flight_diem_payment_cycles_owner_read on public.flight_diem_payment_cycles for select to authenticated using(user_id=auth.uid());
create policy flight_personal_payroll_components_owner_read on public.flight_personal_payroll_components for select to authenticated using(user_id=auth.uid());
grant select,insert,update,delete on public.flight_payroll_bucket_runs,public.flight_diem_payment_cycles,public.flight_personal_payroll_components to service_role;
grant select on public.flight_payroll_bucket_runs,public.flight_diem_payment_cycles,public.flight_personal_payroll_components to authenticated;
insert into public.flight_personal_payroll_components(user_id,component_key,name,component_type,amount_minor_units,effective_from,source_type,notes)
select distinct user_id,'FAM_REIMBURSEMENT','Reembolso FAM','PERSONAL_PAYROLL_COMPONENT',10000,document_period_start,'PAYROLL_CONFIRMED','Componente pessoal confirmado em folha; não generalizável.' from public.flight_schedule_imports where schedule_role='PLANNED' and document_period_start is not null on conflict do nothing;
