alter table public.flight_schedule_imports add column if not exists official_month_flight_time_minutes integer, add column if not exists official_month_duty_time_minutes integer, add column if not exists official_off_days integer, add column if not exists official_off_claim integer;
alter table public.flight_duties add column if not exists official_flight_time_minutes integer, add column if not exists official_flight_time_raw text, add column if not exists official_duty_time_minutes integer, add column if not exists official_duty_time_raw text, add column if not exists official_rest_minutes integer, add column if not exists official_rest_raw text, add column if not exists calculated_flight_time_minutes integer, add column if not exists calculated_duty_time_minutes integer, add column if not exists calculated_rest_minutes integer;
alter table public.flight_legs add column if not exists departure_at_utc timestamptz, add column if not exists arrival_at_utc timestamptz, add column if not exists calculated_duration_minutes integer;
create table if not exists public.flight_schedule_accumulators(id uuid primary key default gen_random_uuid(),import_id uuid not null references public.flight_schedule_imports(id) on delete cascade,schedule_day_id uuid references public.flight_schedule_days(id) on delete set null,accumulator_type text not null check(accumulator_type='ROLLING_FLIGHT_TIME'),period_days smallint not null check(period_days>0),value_minutes integer not null,raw_value text not null,raw_text text not null,created_at timestamptz not null default now(),unique(import_id,schedule_day_id,accumulator_type,period_days,raw_text));
create table if not exists public.flight_schedule_documentary_metrics(id uuid primary key default gen_random_uuid(),import_id uuid not null references public.flight_schedule_imports(id) on delete cascade,schedule_day_id uuid not null references public.flight_schedule_days(id) on delete cascade,reason text not null,official_flight_time_minutes integer,official_flight_time_raw text,official_duty_time_minutes integer,official_duty_time_raw text,official_rest_minutes integer,official_rest_raw text,created_at timestamptz not null default now(),unique(import_id,schedule_day_id,reason));
create table if not exists public.flight_schedule_validations(id uuid primary key default gen_random_uuid(),import_id uuid not null references public.flight_schedule_imports(id) on delete cascade,duty_id uuid references public.flight_duties(id) on delete cascade,leg_id uuid references public.flight_legs(id) on delete cascade,validation_type text not null,severity text not null check(severity in('info','warning','error')),official_value integer,calculated_value integer,difference integer,message text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists flight_schedule_validations_import_idx on public.flight_schedule_validations(import_id);
alter table public.flight_schedule_accumulators enable row level security; alter table public.flight_schedule_documentary_metrics enable row level security; alter table public.flight_schedule_validations enable row level security;
create policy flight_schedule_accumulators_owner_read on public.flight_schedule_accumulators for select to authenticated using(exists(select 1 from public.flight_schedule_imports i where i.id=import_id and i.user_id=auth.uid()));
create policy flight_schedule_documentary_metrics_owner_read on public.flight_schedule_documentary_metrics for select to authenticated using(exists(select 1 from public.flight_schedule_imports i where i.id=import_id and i.user_id=auth.uid()));
create policy flight_schedule_validations_owner_read on public.flight_schedule_validations for select to authenticated using(exists(select 1 from public.flight_schedule_imports i where i.id=import_id and i.user_id=auth.uid()));
create or replace function public.persist_flight_time_metrics(p_import_id uuid,p_footer jsonb,p_leg_metrics jsonb,p_duty_metrics jsonb,p_accumulators jsonb,p_documentary jsonb,p_validations jsonb) returns void language plpgsql security definer set search_path='' as $$
declare is_service boolean:=auth.role()='service_role'; begin
 if (auth.uid() is null and not is_service) or not exists(select 1 from public.flight_schedule_imports where id=p_import_id and (is_service or user_id=auth.uid())) then raise exception 'Acesso negado.' using errcode='42501'; end if;
 delete from public.flight_schedule_accumulators where import_id=p_import_id; delete from public.flight_schedule_documentary_metrics where import_id=p_import_id; delete from public.flight_schedule_validations where import_id=p_import_id;
 update public.flight_schedule_imports set official_month_flight_time_minutes=(p_footer->>'flight_time_minutes')::integer,official_month_duty_time_minutes=(p_footer->>'duty_time_minutes')::integer,official_off_days=(p_footer->>'off_days')::integer,official_off_claim=(p_footer->>'off_claim')::integer where id=p_import_id;
 update public.flight_legs l set departure_at_utc=x.departure_at_utc,arrival_at_utc=x.arrival_at_utc,calculated_duration_minutes=x.duration_minutes from jsonb_to_recordset(coalesce(p_leg_metrics,'[]'::jsonb)) x(sequence smallint,departure_at_utc timestamptz,arrival_at_utc timestamptz,duration_minutes integer) where l.import_id=p_import_id and l.sequence=x.sequence;
 update public.flight_duties d set official_flight_time_minutes=x.official_flight_time_minutes,official_flight_time_raw=x.official_flight_time_raw,official_duty_time_minutes=x.official_duty_time_minutes,official_duty_time_raw=x.official_duty_time_raw,official_rest_minutes=x.official_rest_minutes,official_rest_raw=x.official_rest_raw,calculated_flight_time_minutes=x.calculated_flight_time_minutes,calculated_duty_time_minutes=x.calculated_duty_time_minutes from jsonb_to_recordset(coalesce(p_duty_metrics,'[]'::jsonb)) x(sequence smallint,official_flight_time_minutes integer,official_flight_time_raw text,official_duty_time_minutes integer,official_duty_time_raw text,official_rest_minutes integer,official_rest_raw text,calculated_flight_time_minutes integer,calculated_duty_time_minutes integer) where d.import_id=p_import_id and d.sequence=x.sequence;
 insert into public.flight_schedule_accumulators(import_id,schedule_day_id,accumulator_type,period_days,value_minutes,raw_value,raw_text) select p_import_id,d.id,'ROLLING_FLIGHT_TIME',28,x.value_minutes,x.raw_value,x.raw_text from jsonb_to_recordset(coalesce(p_accumulators,'[]'::jsonb)) x(schedule_date date,value_minutes integer,raw_value text,raw_text text) join public.flight_schedule_days d on d.import_id=p_import_id and d.schedule_date=x.schedule_date;
 insert into public.flight_schedule_documentary_metrics(import_id,schedule_day_id,reason,official_flight_time_minutes,official_flight_time_raw,official_duty_time_minutes,official_duty_time_raw,official_rest_minutes,official_rest_raw) select p_import_id,d.id,x.reason,x.official_flight_time_minutes,x.official_flight_time_raw,x.official_duty_time_minutes,x.official_duty_time_raw,x.official_rest_minutes,x.official_rest_raw from jsonb_to_recordset(coalesce(p_documentary,'[]'::jsonb)) x(schedule_date date,reason text,official_flight_time_minutes integer,official_flight_time_raw text,official_duty_time_minutes integer,official_duty_time_raw text,official_rest_minutes integer,official_rest_raw text) join public.flight_schedule_days d on d.import_id=p_import_id and d.schedule_date=x.schedule_date;
 insert into public.flight_schedule_validations(import_id,validation_type,severity,official_value,calculated_value,difference,message,metadata) select p_import_id,x.validation_type,'warning',x.official_value,x.calculated_value,x.difference,x.message,coalesce(x.metadata,'{}'::jsonb) from jsonb_to_recordset(coalesce(p_validations,'[]'::jsonb)) x(validation_type text,official_value integer,calculated_value integer,difference integer,message text,metadata jsonb);
end $$;
grant execute on function public.persist_flight_time_metrics(uuid,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb) to authenticated,service_role;
grant select on public.flight_schedule_accumulators,public.flight_schedule_documentary_metrics,public.flight_schedule_validations to authenticated,service_role;
